<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Sun, 26 Apr 2015 09:37:18 +0000
// --------------------------------------------------------------------------------

$l['mybbirckeditor_lang'] = 'עברית';
$l['mybbirckeditor_dir'] = 'שמאל לימין';
$l['mybbirckeditor_name'] = 'עורך CKEditor WYSIWYG ';
$l['mybbirckeditor_description'] = 'עורך MyCode מתקדם לMyBB';
$l['mybbirckeditor_settings'] = 'הגדרות עורך CKEditor WYSIWYG ';
$l['mybbirckeditor_enable'] = 'להפעיל את CKEditor?';
$l['mybbirckeditor_mycodeeditor'] = 'להשתמש בעורך MyCode?';
$l['mybbirckeditor_mycodeeditor_d'] = 'אם לא - MyBB ישתמש ב-HTML CKEditor';
$l['mybbirckeditor_editorcolor'] = 'צבע סרגל הכלים';
$l['mybbirckeditor_editorskin'] = 'מראה (סקין) העורך';
$l['mybbirckeditor_fonts'] = 'פונטים';
$l['mybbirckeditor_fonts_d'] = 'he list of fonts names to be displayed in the Font combo in the toolbar. Entries are separated by semi-colons (";"), while it is possible to have more than one font for each entry, in the HTML way (separated by comma).';
$l['mybbirckeditor_migiclinecolor'] = 'Color of Migicline';
$l['mybbirckeditor_editorinnewthread'] = 'Enabled CKEditor in New Thread page?';
$l['mybbirckeditor_editorinnewreply'] = 'Enabled CKEditor in New Reply page?';
$l['mybbirckeditor_editorinusercp'] = 'Enabled CKEditor in UserCp page?';
$l['mybbirckeditor_editorinpm'] = 'לאפשר CKEditor בהודעות פרטיות?';
$l['mybbirckeditor_editorineditpost'] = 'לאפשר CKEditor  בעריכת פוסטים?';
$l['mybbirckeditor_editorinmodcp'] = 'Enabled CKEditor in ModCp page?';
$l['mybbirckeditor_editorincalendar'] = 'לאפשר CKEditor בלוח שנה?';
$l['mybbirckeditor_editorinwarnings'] = 'לאפשר CKEditor בדפי אזהרה?';
$l['mybbirckeditor_editorinquickreply'] = 'Enabled CKEditor in Quick Reply Box';
$l['mybbirckeditor_quickreplys_off'] = 'לא';
$l['mybbirckeditor_quickreplys_full'] = 'עורך מלא';
$l['mybbirckeditor_quickreplys_mini'] = 'מיני עורך (מצומצם)';
$l['mybbirckeditor_smilies'] = 'להראות בחירת סמיילים?';
$l['mybbirckeditor_maxheight'] = 'גובה מקסימלי של העורך';
$l['mybbirckeditor_enableautosave'] = 'לאפשר שמירה אוטומטית?';
$l['mybbirckeditor_autosave'] = 'כל כמה שניות הטקסט נשמר אוטומטית?';
$l['mybbirckeditor_contextmenu'] = 'לאפשר תפריט לחצן ימני?';
$l['mybbirckeditor_width'] = 'אורך של CKEditor ';
$l['mybbirckeditor_height'] = 'גובה של CKEditor ';
$l['mybbirckeditor_minimenu'] = 'Source of MiniEditor ToolBar';
$l['mybbirckeditor_fullmenu'] = 'Source of FullEditor ToolBar';
$l['mybbirckeditor_toolbarlocation'] = 'מיקום סרגל הכלים';
$l['mybbirckeditor_top'] = 'Toop';
$l['mybbirckeditor_bottom'] = 'תחתית';
