<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Fri, 01 May 2015 12:21:11 +0000
// --------------------------------------------------------------------------------

$l['spiders_bots'] = 'ספיירדס (זחלני רשת) / בוטים';
$l['spiders_bots_desc'] = 'אזור זה מאפשר לך לנהל את ספיירדס מנועי החיפוש ובוטים שזוהו אוטומטית ע"י הפורום שלך.
אתה יכול גם לראות מתי בוט מסויים ביקר לאחרונה.';
$l['add_new_bot'] = 'הוסף בוט חדש';
$l['add_new_bot_desc'] = 'כאן תוכל להוסיף בוט חדש שאתה תוכל לזהות ע"י הפורום שלך.';
$l['edit_bot'] = 'ערוך בוט';
$l['edit_bot_desc'] = 'כאן תוכל לערוך בוט קיים.';
$l['bot'] = 'בוט';
$l['last_visit'] = 'ביקור אחרון';
$l['no_bots'] = 'אין זחלנים או ספיירדס מנועי חיפוש שעוקבים אחרי הפורום הזה.';
$l['name'] = 'שם';
$l['name_desc'] = 'Enter the name of this bot which you want to identify it by';
$l['user_agent'] = 'User Agent String';
$l['user_agent_desc'] = 'Enter the string which will be matched against the bots user agent (partial matches are accepted)';
$l['language_str'] = 'שפה';
$l['language_desc'] = 'Select the language pack the bot will use when viewing the board.';
$l['theme'] = 'ערכת נושא';
$l['theme_desc'] = 'Select the theme the bot will use when viewing the board.';
$l['user_group'] = 'קבוצת משתמשים';
$l['user_group_desc'] = 'Select the user group permissions will be applied from for this board (Note: It is not recommended you change this from the default Guests group)';
$l['save_bot'] = 'שמור בוט';
$l['use_board_default'] = 'השתמש בלוח ברירת מחדל.';
$l['error_invalid_bot'] = 'The specified bot does not exist.';
$l['error_missing_name'] = 'You did not enter a name for this bot';
$l['error_missing_agent'] = 'You did not enter a user agent string for this bot';
$l['success_bot_created'] = 'The bot has been created successfully.';
$l['success_bot_updated'] = 'The bot has been updated successfully.';
$l['success_bot_deleted'] = 'The selected bot has been deleted successfully.';
$l['confirm_bot_deletion'] = 'Are you sure you wish to delete this bot?';
