<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Tue, 28 Apr 2015 17:15:57 +0000
// --------------------------------------------------------------------------------

$l['banning'] = 'הרחקה';
$l['banned_ips'] = 'IP מושעים';
$l['banned_ips_desc'] = 'כאן תוכל לנהל כתובות IP המורחקות מלגשת אל הלוח שלך.';
$l['banned_accounts'] = 'חשבונות מושעים';
$l['disallowed_usernames'] = 'שמות משתמשים אסורים';
$l['disallowed_usernames_desc'] = 'כאן תוכל לנהל רשימת שמות משתמשים שלא ניתן להירשם איתם או להשתמש בהם.
אופציה זו שימושית במיוחד עבור שמירה מראש של שמות משתמשים.';
$l['disallowed_email_addresses'] = 'אי-מיילים אסורים';
$l['disallowed_email_addresses_desc'] = 'כאן תוכל לנהל רשימת כתובות אימייל שלא ניתן להירשם איתן או להשתמש בהן במשתמשים.';
$l['banned_ip_addresses'] = 'כתובות IP מורחקות';
$l['username'] = 'שם משתמש';
$l['date_disallowed'] = 'תאריך בלתי מורשה';
$l['last_attempted_use'] = 'נסיון אחרון לשימוש';
$l['email_address'] = 'כתובת אימייל';
$l['ip_address'] = 'כתובת IP';
$l['ban_date'] = 'תאריך הרחקה';
$l['last_access'] = 'גישה אחרונה';
$l['no_bans'] = 'אין הרחקות נכון לעכשיו';
$l['add_disallowed_username'] = 'הוסף שם משתמש אסור';
$l['username_desc'] = 'Note: To indicate a wild card match, use *';
$l['disallow_username'] = 'אסור על שם משתמש זה';
$l['add_disallowed_email_address'] = 'הוסף כתובת אי-מייל אסורה';
$l['email_address_desc'] = 'Note: To indicate a wild card match, use *';
$l['disallow_email_address'] = 'אסור כתובת אימייל זו';
$l['ban_an_ip_address'] = 'הרחק כתובת IP';
$l['ip_address_desc'] = 'הערה: כדי להרחיק טווח של כתובות IP התשמש בכוכבית:
למשל: 127.0.0.* 
או בCIDR:
127.0.0.0/8';
$l['ban_ip_address'] = 'הרחק כתובת IP';
$l['error_missing_ban_input'] = 'לא הכנסת ערך עבורו להרחיק';
$l['error_invalid_filter'] = 'הסינון שצויין לא קיים';
$l['error_filter_already_banned'] = 'הסינון שציינת כבר קיים';
$l['success_ip_banned'] = 'כתובת הIP הורחקה בהצלחה';
$l['success_username_disallowed'] = 'שם משתמש זה כעת אסור לשימוש!';
$l['success_email_disallowed'] = 'כתובת אי מייל זו נאסרה בהצלחה!';
$l['success_ban_deleted'] = 'ההרחקה המדוברת הוסרה בהצלחה!';
$l['confirm_ban_deletion'] = 'האם אתה בטוח שברצונך להסיר הרחקה זו?';
