<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Sun, 26 Apr 2015 12:33:04 +0000
// --------------------------------------------------------------------------------

$l['mp_myprofile'] = 'הפרופיל שלי';
$l['mp_myprofile_desc'] = '';
$l['mp_myprofile_comments'] = 'תגובות הפרופיל שלי';
$l['mp_myprofile_comments_desc'] = '';
$l['mp_myprofile_comments_enabled'] = 'תגובות הפרופיל שלי מופעלות';
$l['mp_myprofile_comments_enabled_desc'] = '';
$l['mp_myprofile_comments_ajax_enabled'] = 'AJAX מופעל';
$l['mp_myprofile_comments_ajax_enabled_desc'] = '';
$l['mp_myprofile_comments_notification'] = 'מערכת התראות';
$l['mp_myprofile_comments_notification_desc'] = '';
$l['mp_myprofile_comments_notification_myalerts_alertbar'] = '';
$l['mp_myprofile_comments_notification_myalerts'] = '';
$l['mp_myprofile_comments_notification_alertbar'] = '';
$l['mp_myprofile_comments_notification_none'] = 'כלום';
$l['mp_myprofile_comments_perpage'] = '';
$l['mp_myprofile_comments_perpage_desc'] = '';
$l['mp_myprofile_comments_min_length'] = '';
$l['mp_myprofile_comments_min_length_desc'] = '';
$l['mp_myprofile_comments_max_length'] = '';
$l['mp_myprofile_comments_max_length_desc'] = '';
$l['mp_myprofile_comments_ignore'] = '';
$l['mp_myprofile_comments_ignore_desc'] = '';
$l['mp_myprofile_comments_edit_time'] = '';
$l['mp_myprofile_comments_edit_time_desc'] = '';
$l['mp_myprofile_comments_flood_time'] = '';
$l['mp_myprofile_comments_flood_time_desc'] = '';
$l['mp_myprofile_comments_status_enabled'] = '';
$l['mp_myprofile_comments_status_enabled_desc'] = '';
$l['mp_myprofile_comments_allow_img'] = '';
$l['mp_myprofile_comments_allow_img_desc'] = '';
$l['mp_myprofile_comments_allow_video'] = '';
$l['mp_myprofile_comments_allow_video_desc'] = '';
$l['mp_myprofile_comments_allow_smilies'] = '';
$l['mp_myprofile_comments_allow_smilies_desc'] = '';
$l['mp_myprofile_comments_allow_mycode'] = '';
$l['mp_myprofile_comments_allow_mycode_desc'] = '';
$l['mp_myprofile_comments_filter_badwords'] = '';
$l['mp_myprofile_comments_filter_badwords_desc'] = '';
$l['mp_myprofile_comments_allow_html'] = '';
$l['mp_myprofile_comments_allow_html_desc'] = '';
$l['mp_myprofile_comments_show_wysiwyg'] = 'הצג WYSIWYG בתגובות פרופיל';
$l['mp_myprofile_comments_show_wysiwyg_desc'] = '';
$l['mp_myprofile_comments_closed_on_banned'] = '';
$l['mp_myprofile_comments_closed_on_banned_desc'] = '';
$l['mp_myprofile_comments_show_stats'] = '';
$l['mp_myprofile_comments_show_stats_desc'] = '';
$l['mp_myprofile_visitors'] = '';
$l['mp_myprofile_visitors_desc'] = '';
$l['mp_myprofile_visitors_enabled'] = '';
$l['mp_myprofile_visitors_enabled_desc'] = '';
$l['mp_myprofile_visitors_record'] = '';
$l['mp_myprofile_visitors_record_desc'] = '';
$l['mp_myprofile_buddylist'] = '';
$l['mp_myprofile_buddylist_desc'] = '';
$l['mp_myprofile_buddylist_enabled'] = '';
$l['mp_myprofile_buddylist_enabled_desc'] = '';
$l['mp_myprofile_buddylist_record'] = '';
$l['mp_myprofile_buddylist_record_desc'] = '';
$l['mp_myprofile_buddylist_avatar_max_dimensions'] = '';
$l['mp_myprofile_buddylist_avatar_max_dimensions_desc'] = '';
$l['mp_options_can_use_image_background'] = '';
$l['mp_options_can_manage_comments'] = '';
$l['mp_options_can_send_comments'] = '';
$l['mp_options_can_edit_own_comments'] = '';
$l['mp_options_can_delete_own_comments'] = '';
