<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Fri, 01 May 2015 12:14:53 +0000
// --------------------------------------------------------------------------------

$l['mod_tools'] = 'כלי משגיח (מנהל)';
$l['thread_tools'] = 'כלים לנושא (אשכול)';
$l['thread_tools_desc'] = 'כלי השגחה מותאמים אישית מאפשרים לך ליצור שילוב של פעולות ניהול שיהיה ניתן להשתמש בהן בפוסטים או בנושאים. ניתן להשתמש באלה אחר כך ככלי ברירת מחדל כשמנהלים את הפורום שלך. כאן תוכל לנהל את הכלים המותאמים אישית שלך.';
$l['add_thread_tool'] = 'הוסף כלי נושא';
$l['add_new_thread_tool'] = 'הוסף כלי נושא חדש';
$l['add_thread_tool_desc'] = 'כאן תוכל להוסיף כלי ניהול מותאם אישית חדש. כלי זה יהיה זמין גם מ"ניהול מהיר" של נושא וגם בתוך הנושאים עצמם,
רשומים כחלק מכלי הניהול הרגילים.';
$l['post_tools'] = 'כלי פוסט';
$l['post_tools_desc'] = 'כלי השגחה מותאמים אישית מאפשרים לך ליצור שילוב של פעולות ניהול שיהיה ניתן להשתמש בהן בפוסטים או בנושאים. ניתן להשתמש באלה אחר כך ככלי ברירת מחדל כשמנהלים את הפורום שלך. כאן תוכל לנהל את הכלים המותאמים אישית שלך <i> עבור פוסטים </i>.';
$l['add_post_tool'] = 'הוסף כלי פוסט';
$l['add_new_post_tool'] = 'הוסף כלי פוסט חדש';
$l['add_post_tool_desc'] = 'כאן תוכל להוסיף כלי ניהול פוסט חדש. כלי זה יהיה זמין מהנושאים עצמם, יופיעו יחד עם כלי הניהול הרגילים.';
$l['edit_post_tool'] = 'ערוך כלי פוסט';
$l['edit_post_tool_desc'] = 'כאן תוכל לערוך את כלי הפוסטים - הגדרותיהם ופעולותיהם.';
$l['edit_thread_tool'] = 'ערוך כלי אשכול';
$l['edit_thread_tool_desc'] = 'כאן תוכל לערוך הגדרות ופעולות כלי נושאים.';
$l['no_thread_tools'] = 'אין כלי נושאים מוגדרים בפורום שלך.';
$l['no_post_tools'] = 'אין כלי פוסטים מוגדרים בפורום שלך.';
$l['confirm_thread_tool_deletion'] = 'Are you sure you want to delete this thread tool?';
$l['confirm_post_tool_deletion'] = 'Are you sure you want to delete this post tool?';
$l['success_post_tool_deleted'] = 'The selected post moderation tool has been deleted successfully.';
$l['success_thread_tool_deleted'] = 'The selected thread moderation tool has been deleted successfully.';
$l['error_invalid_post_tool'] = 'The specified post tool does not exist.';
$l['error_invalid_thread_tool'] = 'The specified thread tool does not exist.';
$l['general_options'] = 'אפשרויות כלליות';
$l['short_description'] = 'תיאור קצר';
$l['available_in_forums'] = 'זמין בפורומים';
$l['available_to_groups'] = 'זמן לקבוצות';
$l['show_confirmation'] = 'הראה עמוד אישור';
$l['save_thread_tool'] = 'שמור כלי נושא';
$l['title'] = 'כותרת';
$l['thread_moderation'] = 'ניהול נושא';
$l['approve_unapprove'] = 'לאשר / לבטל אישור נושא?';
$l['no_change'] = 'אין שינוי';
$l['approve'] = 'אשר';
$l['unapprove'] = 'ביטול אישור';
$l['stick'] = 'נעץ';
$l['unstick'] = 'הורד מנעיצה';
$l['open'] = 'פתח';
$l['close'] = 'סגור';
$l['toggle'] = 'Toggle';
$l['days'] = 'ימים';
$l['no_prefix'] = 'אין קידומת';
$l['restore'] = 'שחזר';
$l['softdelete'] = 'מחיקה';
$l['forum_to_move_to'] = 'פורום להעביר ממנו:';
$l['leave_redirect'] = 'להשאיר הפנייה?';
$l['delete_redirect_after'] = 'למחוק הפנייה אחרי';
$l['do_not_move_thread'] = 'אל תעביר נושא';
$l['do_not_copy_thread'] = 'אל תעתיק נושא';
$l['move_thread'] = 'נושא הועבר?';
$l['move_thread_desc'] = 'If moving the thread(s), the "delete redirect after... days" is only to be filled in if a redirect will be left.';
$l['forum_to_copy_to'] = 'פורום להעתיק ממנו:';
$l['copy_thread'] = 'העתק נושא?';
$l['open_close_thread'] = 'פתח/סגור נושא?';
$l['stick_unstick_thread'] = 'נעץ/בטל נעיצת נושא?';
$l['softdelete_restore_thread'] = 'מחק/שחזר נושא?';
$l['delete_thread'] = 'מחק נושא לצמיתות?';
$l['merge_thread'] = 'מזג נושא?';
$l['merge_thread_desc'] = 'רק אם השתמש בניהול מהיר';
$l['delete_poll'] = 'מחק סקר?';
$l['delete_redirects'] = 'הפניית מחיקה?';
$l['remove_subscriptions'] = 'מחק רישומי נושא?';
$l['recount_rebuild'] = 'ספור מחדש ובנה מחדש?';
$l['apply_thread_prefix'] = 'החל קידומת נושא?';
$l['new_subject'] = 'נושא חדש?';
$l['new_subject_desc'] = '{subject} represents the original subject. {username} represents the moderator\'s username.';
$l['add_new_reply'] = 'הוסף תגובה חדשה';
$l['add_new_reply_desc'] = 'השאר ריק כדי שלא תהיה תגובה';
$l['reply_subject'] = 'נושא התגובה';
$l['reply_subject_desc'] = 'Only used if a reply was made.<br />{subject} represents the original subject. {username} represents the moderator\'s username.';
$l['success_mod_tool_created'] = 'The moderation tool has been created successfully.';
$l['success_mod_tool_updated'] = 'The moderation tool has been updated successfully.';
$l['inline_post_moderation'] = 'ניהול פוסטים מהיר';
$l['delete_posts'] = 'מחק פוסטים לצמיתות?';
$l['merge_posts'] = 'מזג פוסטים?';
$l['merge_posts_desc'] = 'רק אם נעשה דרך "ניהול מהיר"';
$l['approve_unapprove_posts'] = 'אשר/בטל אישור פוסט?';
$l['softdelete_restore_posts'] = 'מחק/שחזר פוסט?';
$l['split_posts'] = 'הפרד פוסטים';
$l['split_posts2'] = 'הפרד פוסטים?';
$l['do_not_split'] = 'אל תפריד פוסטים';
$l['split_to_same_forum'] = 'הפרד לאותו הפורום';
$l['close_split_thread'] = 'סגור נושאים מופרדים?';
$l['stick_split_thread'] = 'נעת נושא מופרד?';
$l['unapprove_split_thread'] = 'בטל אישור נושא מופרד?';
$l['split_thread_prefix'] = 'קידומת נושא מופרד';
$l['split_thread_subject'] = 'כותרת הנושא המפוצל';
$l['split_thread_subject_desc'] = '{subject} represents the original subject. Only required if splitting posts.';
$l['add_new_split_reply'] = 'הוסף תגובה לנושא המפוצל';
$l['add_new_split_reply_desc'] = 'השאר ריק עמ"נ לא להשאיר תגובה';
$l['split_reply_subject'] = 'נושא התגובה';
$l['split_reply_subject_desc'] = 'אך ורק אם נעשית תגובה';
$l['save_post_tool'] = 'שמור כלי פוסט';
$l['send_private_message'] = 'שלח הודעה פרטית';
$l['private_message_message'] = 'הודעה';
$l['private_message_message_desc'] = 'Message to send to the author of the thread. Leave empty to disable this feature.';
$l['private_message_subject'] = 'נושא';
$l['private_message_subject_desc'] = 'הכנס את נושא ההודעה הפרטית';
$l['error_missing_title'] = 'Please enter a name for this tool.';
$l['error_missing_description'] = 'Please enter a short description for this tool.';
$l['error_no_forums_selected'] = 'Please select the forums in which this tool will be available.';
$l['error_no_groups_selected'] = 'Please select the groups to which this tool will be available.';
$l['error_forum_is_category'] = 'You can\'t pick a category-type forum as a destination forum.';
