<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Mon, 27 Apr 2015 19:26:15 +0000
// --------------------------------------------------------------------------------

$l['languages'] = 'שפות';
$l['languages_desc'] = 'חבילות השפה שהתקנת על הפורום שלך מופיעות למטה.
אתה יכול לבחור לערוך קבצי שפה, לערוך קבצים בשפה אחרת או לערוך את מאפייני השפה.';
$l['find_language_packs'] = 'מצא חבילת שפה';
$l['language_files'] = 'קבצי שפה';
$l['language_files_desc'] = 'למטה נמצאים הקבצים של השפה הנבחרת, עבור משתמש הקצה ופאנל הניהול של האדמין. כאן אתה יכול לבחור לערוך קבצים אלו.';
$l['quick_phrases'] = 'ביטויים מהירים';
$l['quick_phrases_desc'] = 'Quick access to commonly modified language phrases.';
$l['edit_with'] = 'ערוך עם {1}';
$l['edit_language_variables'] = 'ערוך משתני שפה';
$l['edit_language_variables_desc'] = 'ערוך את מחרוזות השפה כרצונך';
$l['edit_properties_desc'] = 'כאן אתה יכול לערוך את מאפייני חבילת השפה';
$l['installed_language_packs'] = 'חבילות שפה מותקנות';
$l['front_end'] = 'משתמש קצה';
$l['admin_cp'] = 'פאנל ניהול';
$l['save_language_file'] = 'שמור קבצי שפה';
$l['nav_editing_set'] = 'Editing Language Set Properties';
$l['edit_properties'] = 'ערוך מאפייני חבילת שפה';
$l['friendly_name'] = 'שם ידידותי';
$l['language_in_html'] = 'שפה ב- &lt;html&gt; tag';
$l['charset'] = 'קידוד (חבילת תווים)';
$l['admin'] = 'מכיל משתני שפה עבור פאנל הניהול?';
$l['rtl'] = 'ימין-לשמאל?';
$l['quickphrases_agreement'] = 'תנאי שימוש - כותרת';
$l['quickphrases_agreement_1'] = 'תנאי שימוש - פסקה 1';
$l['quickphrases_agreement_2'] = 'תנאי שימוש - פסקה 2';
$l['quickphrases_agreement_3'] = 'תנאי שימוש - פסקה 3';
$l['quickphrases_agreement_4'] = 'תנאי שימוש - פסקה 4';
$l['quickphrases_agreement_5'] = 'תנאי שימוש - פסקה 5';
$l['quickphrases_error_nopermission_guest_1'] = 'הודעת "אין גישה" - פסקה 1';
$l['quickphrases_error_nopermission_guest_2'] = 'הודעת "אין גישה" - פסקה 2';
$l['quickphrases_error_nopermission_guest_3'] = 'הודעת "אין גישה" - פסקה 3';
$l['quickphrases_error_nopermission_guest_4'] = 'הודעת "אין גישה" - פסקה 4';
$l['no_languages'] = 'אין שפות';
$l['no_language_files_front_end'] = 'There are no Front End Language files found.';
$l['no_language_files_admin_cp'] = 'לא נמצאו קבצי שפה עבור פאנל הניהול.';
$l['error_invalid_set'] = 'חבילת שפה לא תקינה נבחרה';
$l['error_invalid_file'] = 'קובץ שפה לא תקין נבחר';
$l['error_cannot_write_to_file'] = 'לא ניתן לכתוב לקובץ זה, אנא בדוק הרשאות לחבילת שפה זו ונסה שוב';
$l['error_folders_fail'] = 'There was problem accessing requested language pack folders. Please make sure they exists and are writable.';
$l['alert_note_cannot_write'] = 'Before you can edit the language file, you must CHMOD the files in this language set so that the server has permission to write to them.';
$l['success_langfile_updated'] = 'קובץ השפה עודכן בהצלחה';
$l['success_langprops_updated'] = 'מאפייני השפה עודכנו בהצלחה';
$l['success_quickphrases_updated'] = 'ביטויי שפה מהירים עודכנו בהצלחה!';
$l['issues'] = 'בעיות';
$l['phrases'] = 'ביטויים';
$l['issues_ok'] = 'נראה שהכל הולך כשורה';
$l['issues_nothingtocompare'] = 'אין מה להשוות כאן';
$l['issues_warning'] = 'הקובץ הבא עשוי לדרוש תיקון, אנא בדוק אותו.';
