<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Fri, 01 May 2015 11:49:59 +0000
// --------------------------------------------------------------------------------

$l['plugins'] = 'פלאגינים (הרחבות)';
$l['plugins_desc'] = 'אזור זה מאפשר לך להפעיל, לבטל ולנהל את הפלאגינים שהעלת לפורום שלך בתיקיית <strong>inc/plugins</strong>.
כדי להחביא פלאגין אבל לא לאבד מידע שמור שלו בחר ב"בטל".';
$l['plugin_updates'] = 'עדכוני פלאגינים';
$l['plugin_updates_desc'] = 'אזור זה יאפשר לך לבדוק עדכונים להרחבות שלך.';
$l['browse_plugins'] = 'בדוק פלאגינים';
$l['browse_plugins_desc'] = 'כאן תוכל לעיין בהרחבות המתאימות לסדרת העותק שלך מהאתר הרשמי של MyBB .';
$l['browse_all_plugins'] = 'בדוק את כל הפלאגינים';
$l['plugin'] = 'פלאגין';
$l['active_plugin'] = 'פלאגינים פעילים';
$l['inactive_plugin'] = 'פלאגינים לא פעילים';
$l['your_version'] = 'הגרסא שלך';
$l['latest_version'] = 'הגרסא האחרונה';
$l['download'] = 'הורדה';
$l['deactivate'] = 'בטל';
$l['activate'] = 'הפעל';
$l['install_and_activate'] = 'התקן &amp; הפעל';
$l['uninstall'] = 'הסר';
$l['created_by'] = 'נוצר ע"י';
$l['no_plugins'] = 'אין פלאגינים בפורום שלך עכשיו';
$l['no_active_plugins'] = 'אין פלאגינים פעילים';
$l['no_inactive_plugins'] = 'אין פלאגינים לא פעילים';
$l['plugin_incompatible'] = 'הפלאגין הזה לא תומך בMyBB {1}';
$l['recommended_plugins_for_mybb'] = 'פלאגינים מומלצים ל MyBB {1}';
$l['browse_results_for_mybb'] = 'תוצאות חיפוש עבור MyBB {1}';
$l['search_for_plugins'] = 'חפש פלגינים';
$l['search'] = 'חפש';
$l['error_vcheck_no_supported_plugins'] = 'None of the plugins installed support version checking.';
$l['error_vcheck_communications_problem'] = 'There was a problem communicating with the MyBB modifications version server. Please try again in a few minutes.';
$l['error_vcheck_vulnerable'] = '[Vulnerable plugin]:';
$l['error_vcheck_vulnerable_notes'] = 'This submission has currently been marked as vulnerable by the MyBB Staff. We recommend complete removal of this modification. Please see the notes below: ';
$l['error_no_input'] = 'Error code 1: No input specified.';
$l['error_no_pids'] = 'Error code 2: No plugin ids specified.';
$l['error_communication_problem'] = 'There was a problem communicating with the MyBB modifications server. Please try again in a few minutes.';
$l['error_invalid_plugin'] = 'הפלאגין הנבחר לא קיים.';
$l['error_no_results_found'] = 'No results were found for the specified keywords.';
$l['success_plugins_up_to_date'] = 'ברכות, כל הפלאגינים שלך מעודכנים.';
$l['success_plugin_activated'] = 'הפלאגין הנבחר הופעל בהצלחה';
$l['success_plugin_deactivated'] = 'הפלאגין הנבחר בוטל בהצלחה';
$l['success_plugin_installed'] = 'הפלאגין הנבחר הותקן בהצלחה';
$l['success_plugin_uninstalled'] = 'הפלאגין הנבחר הוסר בהצלחה';
