<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Fri, 01 May 2015 12:36:33 +0000
// --------------------------------------------------------------------------------

$l['security_questions'] = 'שאלות אבטחה';
$l['security_questions_desc'] = 'כאן תוכל ליצור ולנהל שאלות אבטחה שיוצגו באקראי בזמן הרשמה.';
$l['add_new_question'] = 'הוסף שאלה';
$l['add_new_question_desc'] = 'הוסף שאלה ותשובותיה עבור שאלת האבטחה שתופיע בזמן ההרשמה.';
$l['edit_question'] = 'ערוך שאלה';
$l['edit_question_desc'] = 'כאן תוכל לערוך שאלת אבטחה';
$l['options'] = 'אפשרויות';
$l['correct'] = 'נכון';
$l['incorrect'] = 'לא נכון';
$l['disable_question'] = 'בטל שאלה';
$l['enable_question'] = 'הפעל שאלה';
$l['delete_question'] = 'מחק שאלה';
$l['no_security_questions'] = 'אין שאלות אבטחה בפורום שלך כעת.';
$l['question'] = 'שלות';
$l['question_desc'] = 'הכנס את השאלה שברצונך לשאול בעת ההרשמה';
$l['answers'] = 'תשובה/תשובות';
$l['answers_desc'] = 'הכנס את התשובות לשאלה הנ"ל. אנא הכנס כל תשובה בשורה נפרדת.
';
$l['active'] = 'פעיל';
$l['save_question'] = 'שמור שאלה';
$l['error_invalid_question'] = 'You have selected an invalid question.';
$l['error_missing_question'] = 'You did not enter a question for this question';
$l['error_missing_answer'] = 'You did not enter any answers for this question';
$l['success_question_created'] = 'The question has been created successfully.';
$l['success_question_updated'] = 'The question has been updated successfully.';
$l['success_question_disabled'] = 'The question has been disabled successfully.';
$l['success_question_enabled'] = 'The question has been enabled successfully.';
$l['success_question_deleted'] = 'The question has been deleted successfully.';
$l['confirm_question_deletion'] = 'Are you sure you wish to delete this question?';
