<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Fri, 01 May 2015 12:32:01 +0000
// --------------------------------------------------------------------------------

$l['warning_system'] = 'מערכת אזהרות';
$l['warning_types'] = 'סוגי אזהרות';
$l['warning_types_desc'] = 'כאן תוכל לנהל את רשימת סוגי האזהרות שצוות האתר יכולים לתת למשתמש.';
$l['add_warning_type'] = 'הוסף סוג אזהרה חדש';
$l['add_warning_type_desc'] = 'כאן תוכל ליצור סוג אזהרה חדש מוגדרת מראש. סוגי אזהרה ניתנים לבחירה כאשר מזהירים משתמשים ואתה יכוללהגדיר את מס\' הנקודות להוספה עבור סוג זה כמו גם את משך האזהרה.';
$l['edit_warning_type'] = 'ערוך סוג אזהרה';
$l['edit_warning_type_desc'] = 'כאן תוכל לערוך את סוג אזהרה זו. סוגי אזהרה ניתנים לבחירה כאשר מזהירים משתמשים ואתה יכוללהגדיר את מס\' הנקודות להוספה עבור סוג זה כמו גם את משך האזהרה.';
$l['warning_levels'] = 'רמות אזהרה';
$l['warning_levels_desc'] = 'רמות אזהרות מגדירות מה יקרה למשתמש כאשר יגיעו לרמת אזהרה מסויימת (אחוז מתוך כמות מירבית של נק\' אזהרה). תוכל להרחיק משתמשים או להשעות את הרשאותיהם.';
$l['add_warning_level'] = 'הוסף רמת אזהרה חדשה';
$l['add_warning_level_desc'] = 'כאן תוכל ליצור רמת אזהרה חדשה. רמות אזהרה הם פעולות שננקטות נגד משתמשים כאשר מהם מגיעים לאחוז מסויים מתוך רמת האזהרה המרבית.';
$l['edit_warning_level'] = 'ערוך רמת אזהרה';
$l['edit_warning_level_desc'] = 'רמות אזהרה הם פעולות שננקטות נגד משתמשים כאשר מהם מגיעים לאחוז מסויים מתוך רמת האזהרה המרבית.';
$l['percentage'] = 'אחוזים';
$l['action_to_take'] = 'פעולה לנקיטה';
$l['move_banned_group'] = 'העבר לקבוצת מורחקים ({3}) עבור {1} {2}';
$l['move_banned_group_permanent'] = 'העברת לקבוצת מורחקים ({1}) לצמיתות';
$l['suspend_posting'] = 'השעה יכולת פרסום עבור {1} {2}';
$l['suspend_posting_permanent'] = 'השעה יכולות פרסום לנצח';
$l['moderate_new_posts'] = 'פרסומים דורשים אישור עבור {1} {2}';
$l['moderate_new_posts_permanent'] = 'פרסומים יזדקקו לאישור לצמיתות';
$l['no_warning_levels'] = 'אין רמות אזהרה בפורום שלך';
$l['warning_type'] = 'סוג אזהרה';
$l['points'] = 'נקודות';
$l['expires_after'] = 'פג תוקף אחרי ';
$l['no_warning_types'] = 'אין סוגי אזהרות בפורום שלך כעת.';
$l['warning_points_percentage'] = 'אחוז מתוך מקסימום נקודות אזהרה';
$l['warning_points_percentage_desc'] = 'אנא הכנס מספר בין אחד למאה.';
$l['action_to_be_taken'] = 'פעולה לנקיטה';
$l['action_to_be_taken_desc'] = 'Select the action you wish to be taken when users reach the above level.';
$l['ban_user'] = 'הרחק משתמש';
$l['banned_group'] = 'קבוצה מורחקת: ';
$l['ban_length'] = 'משך ההרחקה:';
$l['suspend_posting_privileges'] = 'השעה יכולות פרסום';
$l['suspension_length'] = 'זמן השעיה:';
$l['moderate_posts'] = 'פרסומים דרושים אישור';
$l['moderation_length'] = 'משך זמן:';
$l['save_warning_level'] = 'שמור רמת אזהרה';
$l['title'] = 'כותרת';
$l['points_to_add'] = 'נק\' להוספה';
$l['points_to_add_desc'] = 'The number of points to add to a users warning level.';
$l['warning_expiry'] = 'תפוגה';
$l['warning_expiry_desc'] = 'How long after this warning is given do you want it to expire?';
$l['save_warning_type'] = 'שמור סוג אזהרה';
$l['expiration_hours'] = 'שעות';
$l['expiration_days'] = 'ימים';
$l['expiration_weeks'] = 'שבועות';
$l['expiration_months'] = 'חודשים';
$l['expiration_never'] = 'אף פעם';
$l['expiration_permanent'] = 'לצמיתות';
$l['error_invalid_warning_level'] = 'The specified warning level does not exist.';
$l['error_invalid_warning_percentage'] = 'You did not enter a valid percentage value for this warning level. Your percentage value must be between 1 and 100.';
$l['error_invalid_warning_type'] = 'The specified warning type does not exist.';
$l['error_missing_action_type'] = 'Please select one of the actions to be taken to assign with this new warning level.';
$l['error_missing_type_title'] = 'You did not enter a title for this warning type';
$l['error_missing_type_points'] = 'You did not enter a valid number of points to add when giving warnings of this type. You must enter a number greater than 0 but not greater than {1}';
$l['success_warning_level_created'] = 'The warning level has been created successfully.';
$l['success_warning_level_updated'] = 'The warning level has been updated successfully.';
$l['success_warning_level_deleted'] = 'The selected warning level has been deleted successfully.';
$l['success_warning_type_created'] = 'The warning type has been created successfully.';
$l['success_warning_type_updated'] = 'The warning type has been updated successfully.';
$l['success_warning_type_deleted'] = 'The selected warning type has been deleted successfully.';
$l['confirm_warning_level_deletion'] = 'Are you sure you wish to delete this warning level?';
$l['confirm_warning_type_deletion'] = 'Are you sure you wish to delete this warning type?';
