<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Sun, 26 Apr 2015 11:36:34 +0000
// --------------------------------------------------------------------------------

$l['board_settings'] = 'הגדרות לוח';
$l['change_settings'] = 'שנה הגדרות';
$l['change_settings_desc'] = 'אזור זה מאפשר לך לנהל את כל מגוון ההגדרות הקשורות ללוח שלך. כדי להתחיל, בחר קבוצה מלמטה כדי לערוך את ההגדרות הקשורות אליה.';
$l['add_new_setting'] = 'הוסף הגדרה';
$l['add_new_setting_desc'] = 'האזור הזה יאפשר לך להוסיף הגדרה חדשה ללוח';
$l['modify_existing_settings'] = 'שנה הגדרות קיימות';
$l['modify_existing_settings_desc'] = 'מאפשר לשנות הגדרות קיימות בפורום שלך.';
$l['add_new_setting_group'] = 'הוסף קבוצת הגדרות חדשה';
$l['add_new_setting_group_desc'] = 'מאפשר לך ליצור קבוצת הגדרות כדי להפריד בין קבוצות שונות.
';
$l['edit_setting_group'] = 'ערוך הגדרות קבוצה';
$l['edit_setting_group_desc'] = 'ערוך הגדרות קבוצה קיימת';
$l['title'] = 'כותרת';
$l['description'] = 'תיאור';
$l['group'] = 'קבוצה';
$l['display_order'] = 'סדר הצגה';
$l['name'] = 'מזהה';
$l['name_desc'] = 'תן מזהה ייחודי המשמש להתייחסות להגדרות האלה
';
$l['group_name_desc'] = 'זהו מזהה ייחודי שמשתמשים בו למערכת תרגום';
$l['text'] = 'טקסט';
$l['numeric_text'] = 'טקסט מספרי';
$l['textarea'] = 'אזור טקסט מורחב';
$l['yesno'] = 'בחירת כן/לא';
$l['onoff'] = 'בחירת הפעל/בטל';
$l['select'] = 'בחירה מתוך קופסה (SELECTION BOX)';
$l['radio'] = 'בחירה יחידה מתוך כמה (RADIO)';
$l['checkbox'] = 'Checkboxes (וי בחירה מכמה)';
$l['language_selection_box'] = 'אזור בחירת שפה';
$l['forum_selection_box'] = 'אזור בחירת פורום';
$l['group_selection_box'] = 'אזור בחירת קבוצה';
$l['adminlanguage'] = 'אזור בחירת שפת אדמיניסטרציה';
$l['cpstyle'] = 'אזור בחירת עיצוב פאנל ניהול';
$l['php'] = 'Evaluated PHP';
$l['type'] = 'סוג';
$l['extra'] = 'Extra (נוסף)';
$l['extra_desc'] = 'If this setting is a select, radio or check box enter a key paired (key=Item) list of items to show. Separate items with a new line. If PHP, enter the PHP to be evaluated.';
$l['value'] = 'ערך';
$l['insert_new_setting'] = 'הכנס הגדרות נוספות';
$l['edit_setting'] = 'ערוך הגדרות';
$l['delete_setting'] = 'מחק הגדרות';
$l['setting_configuration'] = 'הגדרות מערכת';
$l['update_setting'] = 'עדכן הגדרות';
$l['save_settings'] = 'שמור הגדרות';
$l['setting_groups'] = 'הגדרות קבוצות';
$l['bbsettings'] = 'הגדרות';
$l['insert_new_setting_group'] = 'הכנס הגדרות קבוצה חדשות';
$l['setting_group_setting'] = 'הגדרות קבוצה/ הגדרות';
$l['order'] = 'סדר';
$l['delete_setting_group'] = 'מחק הגדרות קבוצה';
$l['save_display_orders'] = 'שמור סדר הצגה';
$l['update_setting_group'] = 'עדכן הגדרות קבוצה';
$l['modify_setting'] = 'שנה הגדרות';
$l['search'] = 'חפש';
$l['plugin_settings'] = 'הגדרות פלאגין';
$l['show_all_settings'] = 'הראה כל ההגדרות';
$l['settings_search'] = 'חפש עבור הגדרות';
$l['confirm_setting_group_deletion'] = 'האם אתה בטוח שאתה רוצה למחוק הגדרות קבוצה אלה?';
$l['confirm_setting_deletion'] = 'האם אתה בטוח שאתה רוצה למחוק הגדרות אלה?';
$l['error_missing_title'] = 'לא הכנסת כותרת להגדרה זו';
$l['error_missing_group_title'] = 'לא הכנסת כותרת לקבוצה זו';
$l['error_invalid_gid'] = 'לא בחרת קבוצה להחיל עבורה הגדרות אלו';
$l['error_invalid_gid2'] = 'You have followed a link to an invalid setting group. Please ensure it exists.';
$l['error_missing_name'] = 'You did not enter an identifier for this setting';
$l['error_missing_group_name'] = 'לא הכנסת מזהה עבור הגדרות הקבוצה';
$l['error_invalid_type'] = 'לא בחרת סוג נכון עבור הגדרות אלו';
$l['error_invalid_sid'] = 'ההגדרות הללו לא קיימות';
$l['error_duplicate_name'] = 'The identifier specified has already been used for the "{1}" setting -- it must be unique';
$l['error_duplicate_group_name'] = 'The identifier specified has already been used for the "{1}" setting group -- it must be unique';
$l['error_no_settings_found'] = 'No settings were found for the specified search phrase.';
$l['error_cannot_edit_default'] = 'Default settings and groups may not be edited or removed.';
$l['error_cannot_edit_php'] = 'הגדרות מיוחדות אלו לא ניתנות לעריכה';
$l['error_ajax_search'] = 'הייתה בעיה בחיפוש ההגדרות:';
$l['error_ajax_unknown'] = 'הגדרה בלתי ידועה התרחשה בזמן חיפוש ההגדרות';
$l['error_chmod_settings_file'] = 'The settings file "./inc/settings.php" isn\'t writable. Please CHMOD to 777.<br />For more information on CHMODing, see the <a href="http://docs.mybb.com/HowTo_Chmod.html" target="_blank">MyBB Docs</a>.';
$l['error_hidden_captcha_conflict'] = 'The hidden captcha value cannot be "{1}" as it conflicts with another registration field.';
$l['success_setting_added'] = 'ההגדרות נוצרו בהצלחה';
$l['success_setting_updated'] = 'ההגדרות עודכנו בהצלחה';
$l['success_setting_deleted'] = 'ההגדרות נמחקו בהצלחה';
$l['success_settings_updated'] = 'ההגדרות עודכנו בהצלחה';
$l['success_display_orders_updated'] = 'סדר הצגת ההגדרות עודכן בהצלחה';
$l['success_setting_group_added'] = 'הגדרות הקבוצה נוספו בהצלחה';
$l['success_setting_group_updated'] = 'הגדרות הקבוצה עודכנו בהצלחה';
$l['success_setting_group_deleted'] = 'הגדרות הקבוצה הנבחרות נמחקו בהצלחה';
$l['success_duplicate_settings_deleted'] = 'כל הגדרות הקבוצה הזהות נמחקו בהצלחה';
$l['searching'] = 'מחפש... ';
$l['search_error'] = 'הייתה שגיאה בטעינת התוצאות';
$l['search_done'] = 'סיים!';
