<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Fri, 01 May 2015 12:34:01 +0000
// --------------------------------------------------------------------------------

$l['thread_prefixes'] = 'קידומות אשכולות';
$l['thread_prefixes_desc'] = 'קידומות נושאים מאפשרות לך להגדיר קידומות שמשתמשים יכולים לשייך לאשכולות שלהם.
אשכולות כך יכולות להתמיין בתוך פורום.';
$l['add_new_thread_prefix'] = 'הוסף קידומת אשכול חדשה';
$l['add_new_thread_prefix_desc'] = 'כאן תוכל להוסיף קידומת נושא חדשה ולהגדיר היכן היא זמינה, כמו גם אילו קבוצות משתמשים יכולות להשתמש בה.';
$l['edit_prefix'] = 'ערוך קידומת';
$l['edit_prefix_desc'] = 'Here you can edit a thread prefix and change how it is display, where it is available and which usergroups can use it.';
$l['edit_thread_prefix'] = 'ערוך קידומת אשכול';
$l['delete_thread_prefix'] = 'מחק קידומת אשכול';
$l['prefix_options'] = 'אפשרויות קידומת';
$l['save_thread_prefix'] = 'שמור קידומת אשכול';
$l['prefix'] = 'קידומת';
$l['prefix_desc'] = '(טקסט בלבד) הקידומת שתופיע בתפריט הבחירה בקידומות';
$l['display_style'] = 'סגנון הצגה';
$l['display_style_desc'] = 'This is how the prefix will appear next to thread subjects. You may enter HTML markup here or simply use the same as the plain text version above.';
$l['available_in_forums'] = 'זמין בפורומים';
$l['available_to_groups'] = 'זמין בקבוצות';
$l['no_thread_prefixes'] = 'אין קידומות נושאים בפורום שלך';
$l['confirm_thread_prefix_deletion'] = 'Are you sure you want to delete this thread prefix? Note: You should remember to update any custom moderator tools which use this prefix after deletion.';
$l['success_thread_prefix_created'] = 'קידומת האשכול נוצרה בהצלחה';
$l['success_thread_prefix_updated'] = 'קידומת האשכול עודכנה בהצלחה';
$l['success_thread_prefix_deleted'] = 'The thread prefix has been deleted successfully. Please update any custom moderator tools which use this prefix';
$l['error_missing_prefix'] = 'Please enter the prefix you wish to add.';
$l['error_missing_display_style'] = 'Please enter a display style for this prefix.';
$l['error_no_forums_selected'] = 'Please select the forums in which this prefix will be available.';
$l['error_no_groups_selected'] = 'Please select the groups to which this prefix will be available.';
$l['error_invalid_prefix'] = 'The specified thread prefix does not exist.';
