<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Fri, 01 May 2015 11:55:18 +0000
// --------------------------------------------------------------------------------

$l['attachment_types'] = 'סוגי קבצים מצורפים';
$l['attachment_types_desc'] = 'כאן תוכל ליצור ולנהל סוגי קבצים מצרופים שמגדירים איזה סוגים של קבצים משתמשים יכולים לצרף לפרסומים שלהם.
';
$l['add_new_attachment_type'] = 'הוסף סוג קובץ חדש';
$l['add_attachment_type'] = 'הוסף סוג קובץ';
$l['add_attachment_type_desc'] = 'הוספת סוג קובץ יאפשר למשתמשים להוסיף קבצים מסוג זה בפרסומים שלהם.
יש לך את האפשרות לשלוט בסיומת, סוג הMIME, הגודל המירבי ולהראות סמלון קטן עבור כל סוג קובץ.';
$l['edit_attachment_type'] = 'ערוך סוג קובץ';
$l['edit_attachment_type_desc'] = 'יש לך אפשרות לנהל את הסיומת, סוג הMIME, גודל מירבי ולהראות סוג MIME קטן עבור סוג הקובץ.';
$l['extension'] = 'הרחבה';
$l['maximum_size'] = 'גודל מירבי';
$l['no_attachment_types'] = 'There are no attachment types on your forum at this time.';
$l['name'] = 'שם';
$l['name_desc'] = 'הכנס את שם סוג הקובץ המצורף';
$l['file_extension'] = 'סיומת קובץ';
$l['file_extension_desc'] = 'Enter the file extension you wish to allow uploads for here (Do not include the period before the extension) (Example: txt)';
$l['mime_type'] = 'סוג MIME';
$l['mime_type_desc'] = 'Enter the MIME type sent by the server when downloading files of this type (<a href="http://www.webmaster-toolkit.com/mime-types.shtml">See a list here</a>)';
$l['maximum_file_size'] = 'גודל מקסימלי (KB)';
$l['maximum_file_size_desc'] = 'The maximum file size for uploads of this attachment type in Kilobytes (1 MB = 1024 KB)';
$l['limit_intro'] = 'Please ensure the maximum file size is below the smallest of the following PHP limits:';
$l['limit_post_max_size'] = 'גודל פרסום מירבי: {1}';
$l['limit_upload_max_filesize'] = 'גודל קובץ מועלה מירבי: {1}';
$l['attachment_icon'] = 'סמלון קובץ מצורף';
$l['attachment_icon_desc'] = 'If you wish to show a small attachment icon for attachments of this type then enter the path to it here. {theme} will be replaced by the image directory for the viewers theme allowing you to specify per-theme attachment icons.';
$l['save_attachment_type'] = 'שמור סוג קובץ מצורף';
$l['error_invalid_attachment_type'] = 'You have selected an invalid attachment type.';
$l['error_missing_mime_type'] = 'You did not enter a MIME type for this attachment type';
$l['error_missing_extension'] = 'You did not enter a file extension for this attachment type';
$l['success_attachment_type_created'] = 'The attachment type has been created successfully.';
$l['success_attachment_type_updated'] = 'The attachment type has been updated successfully.';
$l['success_attachment_type_deleted'] = 'The attachment type has been deleted successfully.';
$l['confirm_attachment_type_deletion'] = 'Are you sure you wish to delete this attachment type?';
