<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Fri, 01 May 2015 11:32:09 +0000
// --------------------------------------------------------------------------------

$l['custom_profile_fields'] = 'שדות פרופיל מותאמים אישית';
$l['custom_profile_fields_desc'] = 'כאן תוכל לערוך, למחוק ולנהל את שדות הפרופיל המותאמים אישית.';
$l['add_profile_field'] = 'הוסף שדה פרופיל';
$l['add_new_profile_field'] = 'הוסף שדה פרופיל חדש';
$l['add_new_profile_field_desc'] = 'כאן תוכל להוסיף שדה משתמש מותאם אישית.';
$l['edit_profile_field'] = 'ערוך שדה פרופיל';
$l['edit_profile_field_desc'] = 'כאן תוכל לערוך שדה משתמש מותאם אישית.';
$l['title'] = 'כותרת';
$l['short_description'] = 'תיאור קצר';
$l['maximum_length'] = 'מקסימום אורך';
$l['maximum_length_desc'] = 'This maximum number of characters that can be entered. This only applies to text boxes and text areas.';
$l['field_length'] = 'אורך השדה';
$l['field_length_desc'] = 'This length of the field. This only applies to single and multiple select boxes.';
$l['display_order'] = 'סדר הצגה';
$l['display_order_desc'] = 'This is the order of custom profile fields in relation to other custom profile fields. This number should not be the same as another field.';
$l['text'] = 'תיבת טקסט';
$l['textarea'] = 'תיבת טקסט גדולה';
$l['select'] = 'אזור בחירה';
$l['multiselect'] = 'אזור בחירה (מרובה בחירות)';
$l['radio'] = 'כפתור בחירה (RADIO)';
$l['checkbox'] = 'כפתור בחירה מרובה (CHECKBOX)';
$l['field_type'] = 'סוג שדה';
$l['field_type_desc'] = 'This is the field type that will be shown.';
$l['field_regex'] = 'ביטויים רגולריים';
$l['field_regex_desc'] = 'Enter a regular expression that should be matched from the user input. You must make sure the regular expression is valid and safe—no validation is performed. Empty for anything.<br />
<strong>Example:</strong> ([a-z0-9_\\- ,.+]+)';
$l['selectable_options'] = 'Selectable Options?';
$l['selectable_options_desc'] = 'Please enter each option on a separate line. This only applies to the select boxes, check boxes, and radio buttons types.';
$l['required'] = 'הכרחי?';
$l['required_desc'] = 'Is this field required to be filled in during registration or profile editing? Note that this does not apply if the field is hidden or the field is not editable.';
$l['show_on_registration'] = 'להראות בהרשמה?';
$l['show_on_registration_desc'] = 'Should this field appear on the registration form? Note that this does not apply if the field is not editable. Fields that are required will always appear on registration.';
$l['display_on_profile'] = 'להראות בפרופיל?';
$l['display_on_profile_desc'] = 'Should this field be displayed on the user\'s profile? This doesn\'t apply to administrators/moderators.';
$l['display_on_postbit'] = 'להציג בפוסטים?';
$l['display_on_postbit_desc'] = 'Should this field be displayed on posts of an user?';
$l['viewableby'] = 'ניתן לצפייה על ידי';
$l['viewableby_desc'] = 'Select the allowed groups to view this profile field.';
$l['editableby'] = 'ניתן לעריכה ע"י';
$l['editableby_desc'] = 'בחר קבוצות הרשאיות לשנות שדה פרופיל זה';
$l['min_posts_enabled'] = 'מונה הודעות מינימלי?';
$l['min_posts_enabled_desc'] = 'Should this field only be available to users with a certain post count? If so, set the minimum amount of posts required here.';
$l['parser_options'] = 'אפשרויות מפרש';
$l['parse_allowhtml'] = 'כן, אפשר HTML בשדה פרופיל זה';
$l['parse_allowmycode'] = 'כן, אפשר MyCode בשדה פרופיל זה';
$l['parse_allowsmilies'] = 'כן, אפשר חייכנים בשדה פרופיל זה';
$l['parse_allowimgcode'] = 'כן, אפשר תג [img] בשדה פרופיל זה';
$l['parse_allowvideocode'] = 'כאן, אפשר תג [video] בשדה פרופיל זה';
$l['save_profile_field'] = 'שמור שדה פרופיל';
$l['name'] = 'שם';
$l['registration'] = 'הרשמה?';
$l['editable'] = 'ניתן לעריכה?';
$l['profile'] = 'פרופיל?';
$l['postbit'] = 'מוצג בפוסטים?';
$l['edit_field'] = 'ערוך שדה';
$l['delete_field'] = 'מחק שדה';
$l['no_profile_fields'] = 'There are no custom profile fields on your forum at this time.';
$l['error_missing_name'] = 'You did not enter a title for this custom profile field';
$l['error_missing_description'] = 'You did not enter a description for this custom profile field';
$l['error_invalid_fid'] = 'The selected profile field does not exist.';
$l['success_profile_field_added'] = 'The custom profile field has been created successfully.';
$l['success_profile_field_saved'] = 'The custom profile field has been saved successfully.';
$l['success_profile_field_deleted'] = 'The selected custom profile field has been deleted successfully.';
$l['confirm_profile_field_deletion'] = 'Are you sure you wish to delete this profile field?';
