<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Fri, 01 May 2015 11:42:26 +0000
// --------------------------------------------------------------------------------

$l['custom_mycode'] = 'MyCode מותאם אישית';
$l['mycode'] = 'MyCode';
$l['mycode_desc'] = 'MyCode מותאם אישית מאפשר לך ליצור MyCode נוספים עבור שימוש בהודעות.';
$l['add_new_mycode'] = 'הוסף MyCode חדש';
$l['add_new_mycode_desc'] = 'כאן תוכל להוסיף MyCode מותאם אישית לפורום שלך. אתה יכול להשתמש בארגז החול למטה כדי לבצע בדיקות לפני שמירה.';
$l['edit_mycode_desc'] = 'Here you can edit a custom MyCode. You can use the MyCode Sandbox below the form to test your regular expression and replacement before saving your changes.';
$l['title'] = 'כותרת';
$l['short_description'] = 'תיאור קצר';
$l['regular_expression'] = 'ביטויים רגולריים';
$l['regular_expression_desc'] = 'Enter a regular expression that will search for a specific combination of characters.  You must make sure the regular expression is valid and safe&mdash;no validation is performed.';
$l['replacement'] = 'החלפה';
$l['replacement_desc'] = 'Enter a replacement for the regular expression.';
$l['example'] = 'דוגמה:';
$l['enabled'] = 'מופעל?';
$l['parse_order'] = 'סדר פירוש';
$l['parse_order_desc'] = 'MyCodes will be parsed in ascending order relative to other MyCodes.';
$l['edit_mycode'] = 'ערוך MyCode';
$l['activate_mycode'] = 'הפעל MyCode';
$l['deactivate_mycode'] = 'השבת MyCode';
$l['delete_mycode'] = 'מחק MyCode';
$l['no_mycode'] = 'לא נמצאו MyCode מותאמים אישית';
$l['save_mycode'] = 'שמור MyCode';
$l['add_mycode'] = 'הוסף MyCode';
$l['changes_not_saved'] = 'Your changes have not yet been saved.';
$l['sandbox'] = 'ארגז חול';
$l['sandbox_desc'] = 'You can use this area to test the regular expression and replacement above before saving your changes.';
$l['test_value'] = 'ערך בדיקה (טסט)';
$l['test_value_desc'] = 'הכנס טקסט לבדיקה בתיבה למטה';
$l['result_html'] = 'תוצר HTML';
$l['result_html_desc'] = 'The text area below shows the resulting HTML using the regular expression on the test value.';
$l['result_actual'] = 'תוצר ממשי';
$l['result_actual_desc'] = 'האזור מטה מראה את התוצר בפועל (הסופי)';
$l['test'] = 'בדיקה MyCode';
$l['error_missing_title'] = 'לא הכנסת כותרת';
$l['error_missing_regex'] = 'לא הכנסת ביטוי רגולרי';
$l['error_missing_replacement'] = 'לא הכנסת תחליף';
$l['error_invalid_mycode'] = 'הMyCode המצויין לא קיים';
$l['success_added_mycode'] = 'הMyCode הוסף בהצלחה';
$l['success_deleted_mycode'] = 'הMyCode הנבחר נמחק בהצלחה';
$l['success_updated_mycode'] = 'הMyCode הנבחר עודכן בהצלחה';
$l['success_deactivated_mycode'] = 'הMyCode הנבחר הושבת בהצלחה';
$l['success_activated_mycode'] = 'הMyCode הנבחר הופעל בהצלחה';
$l['confirm_mycode_deletion'] = 'האם אתב בטוח שברצונך למחוק MyCode זה?';
$l['mycode_sandbox_test_error'] = 'התרחשה שגיאה ביצירת תוצר הבדיקה';
