<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Mon, 27 Apr 2015 21:12:53 +0000
// --------------------------------------------------------------------------------

$l['post_icons'] = 'אייקוני פוסטים';
$l['add_post_icon'] = 'הוסף אייקון פוסט';
$l['add_post_icon_desc'] = 'כאן תוכל להוסיף אייקון פוסט חדש';
$l['add_multiple_post_icons'] = 'הוסף מספר אייקוני פוסטים';
$l['add_multiple_post_icons_desc'] = 'כאן תוכל להוסיף מספר אייקוני פוסטים';
$l['edit_post_icon'] = 'ערוך אייקון פוסט';
$l['edit_post_icon_desc'] = 'כאן תוכל לערוך אייקון פוסט';
$l['manage_post_icons'] = 'נהל אייקוני פוסטים';
$l['manage_post_icons_desc'] = 'כאן תוכל לערוך, למחוק ולנהל אייקוני פוסטים.';
$l['name_desc'] = 'זהו השם עבור האייקון שלך';
$l['image_path'] = 'כתובת התמונה';
$l['image_path_desc'] = 'This is the path to the post icon image. If you want to use different post icon images for different themes, please use <strong>{theme}</strong> to represent the image directory of each theme.';
$l['save_post_icon'] = 'שמור אייקון';
$l['reset'] = 'אתחל (RESET)';
$l['path_to_images'] = 'כתובת לתמונות';
$l['path_to_images_desc'] = 'This is the path to the folder that the images are in.';
$l['show_post_icons'] = 'הראה אייקוני פוסטים';
$l['image'] = 'תמונה';
$l['add'] = 'הוסף?';
$l['save_post_icons'] = 'שמור אייקוני פוסטים';
$l['no_post_icons'] = 'There are no post icons on your forum at this time.';
$l['error_missing_name'] = 'לא הכנסת שם לאייקון זה';
$l['error_missing_path'] = 'You did not enter a path to this post icon';
$l['error_missing_path_multiple'] = 'You did not enter a path';
$l['error_invalid_path'] = 'You did not enter a valid path';
$l['error_no_images'] = 'There are no post icons in the specified directory, or all post icons in the directory have already been added.';
$l['error_none_included'] = 'You did not select any post icons to include.';
$l['error_invalid_post_icon'] = 'The specified post icon does not exist.';
$l['success_post_icon_added'] = 'האייקון נוסף בהצלחה';
$l['success_post_icons_added'] = 'האייקונים נוספו בהצלחה';
$l['success_post_icon_updated'] = 'האייקון עודכן בהצלחה';
$l['success_post_icon_deleted'] = 'The selected post icon has been deleted successfully.';
$l['confirm_post_icon_deletion'] = 'Are you sure you wish to delete this post icon?';
