<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Fri, 01 May 2015 11:39:28 +0000
// --------------------------------------------------------------------------------

$l['bad_words'] = 'מסנני מילים';
$l['edit_bad_word'] = 'ערוך מסנן';
$l['edit_bad_word_desc'] = 'Here you can edit the filter and its replacement.';
$l['bad_word_filters'] = 'מסנני מילים';
$l['bad_word_filters_desc'] = 'תכונה זו מאפשרת לך לנהל רשימה של מילים או ביטויים שאוטומטית מוחלפים בפוסטים בפורום שלך. זה שימושי לצנזור של מילים, קללות וכו\'.';
$l['bad_word'] = 'מילה';
$l['bad_word_desc'] = 'הכנס את המילה שאתה רוצה לסנן.
כוכבית "*" תייצג כל אות וספרה אפשרית לפי הביטוי (a-zA-Z0-9)_';
$l['bad_word_max'] = 'ביטוי אסור לא יכול להיות ארוך יותר מ100 תווים';
$l['replacement'] = 'תחליף';
$l['replacement_desc'] = 'Enter the string which will replace the filtered word (If this is blank, asterisks will be shown)';
$l['replacement_word_max'] = 'A replacement word can\'t be longer than 100 characters.';
$l['error_replacement_word_invalid'] = 'A replacement word cannot be equivalent to it\'s word filter.';
$l['save_bad_word'] = 'שמור מסנן';
$l['no_bad_words'] = 'There are no word filters currently set at this time.';
$l['add_bad_word'] = 'הוסף מסנן';
$l['error_missing_bad_word'] = 'לא הכנסת מסנן מילה';
$l['error_invalid_bid'] = 'המסנן שצויין לא קיים';
$l['error_bad_word_filtered'] = 'המסנן שהכנסת קיים כבר';
$l['success_added_bad_word'] = 'המסנן הוסף בהצלחה';
$l['success_deleted_bad_word'] = 'המסנן נמחק בהצלחה';
$l['success_updated_bad_word'] = 'המסנן עודכן בהצלחה';
$l['confirm_bad_word_deletion'] = 'אתה בטוח שברצונך למחוק מסנן זה?';
