<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Fri, 01 May 2015 11:46:01 +0000
// --------------------------------------------------------------------------------

$l['help_documents'] = 'מסמכי עזרה';
$l['add_new_section'] = 'הוסף תחום חדש';
$l['add_new_section_desc'] = 'כאן תוכל להוסיף תחום עזרה חדש';
$l['add_new_document'] = 'הוסף מסמך חדש';
$l['add_new_document_desc'] = 'כאן תוכל להוסיף מסמך חדש';
$l['edit_section'] = 'ערוך תחום';
$l['edit_section_desc'] = 'כאן תוכל לערוך תחום עזרה';
$l['edit_document'] = 'ערוך מסמך';
$l['edit_document_desc'] = 'כאן תוכל לערוך מסמך עזרה';
$l['manage_help_documents'] = 'נהל מסמכי עזרה';
$l['manage_help_documents_desc'] = 'אזור זה מאפשר לך לנהל מסמכי עזרה';
$l['title'] = 'כותרת';
$l['short_description'] = 'תיאור קצר';
$l['display_order'] = 'סדר הצגה';
$l['enabled'] = 'פעיל?';
$l['use_translation'] = 'להשתמש בתרגום?';
$l['add_section'] = 'הוסף תחום';
$l['add_document'] = 'הוסף מסמך';
$l['save_section'] = 'שמור תחום';
$l['save_document'] = 'שמור מסמך';
$l['section'] = 'תחום';
$l['document'] = 'מסמך';
$l['id'] = 'ID';
$l['custom_doc_sec'] = 'מסמך/תחום מותאם אישית';
$l['default_doc_sec'] = 'מסמך/תחום ברירת מחדל';
$l['no_help_documents'] = 'אין מסמכי עזרה בפורום שלך כרגע';
$l['section_document'] = 'תחום / מסמך';
$l['error_section_missing_name'] = 'You must specify a name for the section.';
$l['error_section_missing_description'] = 'You must specify a short description for the section.';
$l['error_section_missing_enabled'] = 'You must specify yes or no for "Enabled?".';
$l['error_section_missing_translation'] = 'You must specify yes or no for "Use Translation?".';
$l['error_missing_sid'] = 'You must specify a section for the document.';
$l['error_document_missing_name'] = 'You must specify a name for the document.';
$l['error_document_missing_description'] = 'You must specify a short description for the document.';
$l['error_document_missing_document'] = 'You must specify the document.';
$l['error_document_missing_enabled'] = 'You must specify yes or no for "Enabled?".';
$l['error_document_missing_translation'] = 'You must specify yes or no for "Use Translation?".';
$l['error_invalid_sid'] = 'Invalid document id specified.';
$l['error_missing_section_id'] = 'The specified section does not exist.';
$l['error_missing_hid'] = 'The specified document does not exist.';
$l['success_help_section_added'] = 'The help section has been added successfully.';
$l['success_help_document_added'] = 'The help document has been added successfully.';
$l['success_help_section_updated'] = 'The help section has been updated successfully.';
$l['success_help_document_updated'] = 'The help document has been updated successfully.';
$l['success_section_deleted'] = 'The selected help section has been deleted successfully.';
$l['success_document_deleted'] = 'The selected help document has been deleted successfully.';
$l['confirm_section_deletion'] = 'Are you sure you wish to delete this section?';
$l['confirm_document_deletion'] = 'Are you sure you wish to delete this document?';
