<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Tue, 28 Apr 2015 15:30:40 +0000
// --------------------------------------------------------------------------------

$l['calendars'] = 'לוחות שנה';
$l['manage_calendars'] = 'נהל לוחות שנה';
$l['manage_calendars_desc'] = 'אזור זה מאפשר לך לנהל את לוחות השנה במערכת. אם תשנה את שדר התצוגה של אחד או יותר לוחות שנה וודא שאתה שולח את בקשת השינוי בתחתית הדף.';
$l['add_calendar'] = 'הוסף לוח שנה חדש';
$l['add_calendar_desc'] = 'צור לוח שנה חדש';
$l['edit_calendar'] = 'ערוך לוח שנה';
$l['edit_calendar_desc'] = 'כאן תוכל לערוך את הגדרות לוח שנה';
$l['calendar'] = 'לוח שנה';
$l['order'] = 'סדר';
$l['no_calendars'] = 'אין לוחות שנה בפורום שלך כעת.';
$l['save_calendar_orders'] = 'שמור סדר תצוגת לוח שנה';
$l['name'] = 'שם';
$l['display_order'] = 'סדר תצוגה';
$l['week_start'] = 'תחילת שבוע';
$l['week_start_desc'] = 'Here you can set the day weeks should start on for this calendar.';
$l['sunday'] = 'ראשון';
$l['monday'] = 'שני';
$l['tuesday'] = 'שלישי';
$l['wednesday'] = 'רביעי';
$l['thursday'] = 'חמישי';
$l['friday'] = 'שישי';
$l['saturday'] = 'שבת';
$l['event_limit'] = 'גבול אירוע';
$l['event_limit_desc'] = 'The number of events to be shown before a single link to all events on the particular day is shown instead.';
$l['show_birthdays'] = 'הצג ימי הולדת?';
$l['show_birthdays_desc'] = 'Do you wish to show birthdays of registered users in this calendar?';
$l['moderate_events'] = 'נהל אירועים חדשים?';
$l['moderate_events_desc'] = 'If this option is set to \'Yes,\' all events will be moderated apart from those created by members with \'Bypass moderation queue\' set for their calendar permissions.';
$l['allow_html'] = 'אפשר HTML באירועים?';
$l['allow_mycode'] = 'אפשר MyCode באירועים?';
$l['allow_img'] = 'אפשר [IMG] באירועים?';
$l['allow_video'] = 'אפשר [VIDEO] באירועים?';
$l['allow_smilies'] = 'אפשר סמיילים אירועים?';
$l['save_calendar'] = 'שמור לוח שנה';
$l['permissions'] = 'הרשאות';
$l['edit_permissions'] = 'ערוך הרשאות לוח שנה';
$l['calendar_permissions_for'] = 'הרשאות לוח שנה עבור';
$l['permissions_group'] = 'קבוצה';
$l['permissions_view'] = 'תצוגה';
$l['permissions_post_events'] = 'אירועי פוסטים';
$l['permissions_bypass_moderation'] = 'Bypass Moderation';
$l['permissions_moderator'] = 'ערוך גישות';
$l['permissions_all'] = 'הכל?';
$l['permissions_use_group_default'] = 'השתמש בקבוצת ברירת מחדל';
$l['save_permissions'] = 'שמור הרשאות';
$l['error_invalid_calendar'] = 'The specified calendar does not exist.';
$l['error_missing_name'] = 'You did not enter a name for this calendar';
$l['error_missing_order'] = 'You did not enter a display order for this calendar';
$l['success_calendar_created'] = 'The calendar has been created successfully.';
$l['success_calendar_updated'] = 'The calendar has been updated successfully.';
$l['success_calendar_permissions_updated'] = 'The calendar permissions have been updated successfully.';
$l['success_calendar_deleted'] = 'The selected calendar has been deleted successfully.';
$l['success_calendar_orders_updated'] = 'The calendar display orders have been updated successfully.';
$l['confirm_calendar_deletion'] = 'אתה בטוח שברצונך למחוק לוח שנה זה?';
