<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Sun, 26 Apr 2015 09:41:00 +0000
// --------------------------------------------------------------------------------

$l['announcement'] = 'הכרזות';
$l['order'] = 'סדר';
$l['announcement_simple'] = 'הכרזות';
$l['announcement_error'] = 'שגיאה בלתי ידועה, אנא נסה בזמן אחר';
$l['announcement_permission'] = 'יכול לנהל הכרזות?';
$l['announcement_no'] = 'אין הכרזות';
$l['left'] = 'שמאל';
$l['right'] = 'ימין';
$l['top'] = 'למעלה';
$l['bottom'] = 'למטה';
$l['scroll_none'] = 'אין גלילה';
$l['scroll_right'] = 'שמאל לימין';
$l['scroll_left'] = 'ימין לשמאל';
$l['scroll_both'] = 'הלוך וחזור';
$l['announcement_list'] = 'הכרזות';
$l['announcement_list_desc'] = 'כאן תוכל לנהל הכרזות';
$l['announcement_add'] = 'הוסף הכרזה';
$l['announcement_add_desc'] = 'כן תוכל להוסיף הכרזה';
$l['announcement_add_success'] = 'הכרזה הוספה בהצלחה';
$l['announcement_enable_success'] = 'הוכרז בהצלחה {1}';
$l['announcement_delete_success'] = 'הכרזה נמחקה בהצלחה';
$l['announcement_edit_success'] = 'הכרזה נערכה בהצלחה';
$l['announcement_order_success'] = 'שנה סדר';
$l['announcement_deactivate'] = 'בטל';
$l['announcement_activate'] = 'הפעל';
$l['announcement_location'] = 'גלובלי?';
$l['announcement_submit'] = 'שמור';
$l['announcement_desc'] = 'ההודעה שתיראה';
$l['announcement_not'] = 'אנא רשום הודעה';
$l['announcement_global'] = 'להראות את ההכרזה גלובלית';
$l['announcement_global_not'] = 'שגיאה פנימית [1]';
$l['announcement_forum'] = 'In which forum should the Announcement be shown?';
$l['announcement_forum_desc'] = 'If you choose nothing and set no thread the Announcement will be shown on the index';
$l['announcement_thread'] = 'In which threads should the Announcement be shown?';
$l['announcement_thread_desc'] = 'Seperate different threads with ","<br />If you choose nothing and set no forum the Announcement will be shown on the index';
$l['announcement_group'] = 'To which usergroups should the Announcement be shown?';
$l['announcement_group_desc'] = 'If you choose nothing the Announcement will be shown to everyone';
$l['announcement_languages'] = 'In which language(s) is the Announcement written?';
$l['announcement_languages_desc'] = 'Users with an other language can\'t see the Announcement.<br />If you choose nothing the Announcement will be shown to everyone';
$l['announcement_color'] = 'צבע הטקסט';
$l['announcement_color_desc'] = 'The Color the Announcement will be shown in';
$l['announcement_color_not'] = 'אנא הכנס צבע טקסט';
$l['announcement_back_color'] = 'צבע רקע';
$l['announcement_back_color_desc'] = 'The Background Color of the Announcement';
$l['announcement_back_color_not'] = 'Please enter a Background Color';
$l['announcement_border_select'] = 'גבול';
$l['announcement_border_select_desc'] = 'היכן להראות גבול?';
$l['announcement_border_select_not'] = 'Internal Error [2]';
$l['announcement_border_color'] = 'צבע גבול';
$l['announcement_border_color_desc'] = 'The Border Color of the Announcement';
$l['announcement_border_color_not'] = 'Please enter a Border Color';
$l['announcement_scroll'] = 'טקסט נגלל';
$l['announcement_scroll_desc'] = '';
$l['announcement_scroll_not'] = 'Internal Error [3]';
$l['announcement_slow_down'] = 'האט גלילה למטה';
$l['announcement_slow_down_desc'] = 'Slow down the scrolling when the user moves his mouse over it?';
$l['announcement_slow_down_not'] = 'Interal Error [4]';
$l['announcement_css'] = 'עוד ארגומנטים של CSS';
$l['announcement_css_desc'] = 'Here you can add more CSS Arguments';
$l['announcement_removable'] = 'לאפשר להחביא?';
$l['announcement_removable_desc'] = 'Can the user hide this announcement (like PM Notices)?';
$l['announcement_removable_not'] = 'Internal Error [5]';
$l['announcement_enable'] = 'להפעיל הכרזה?';
$l['announcement_enable_not'] = 'Internal Error [6]';
