<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Fri, 01 May 2015 11:36:31 +0000
// --------------------------------------------------------------------------------

$l['smilies'] = 'חייכנים';
$l['manage_smilies'] = 'נהל חייכנים';
$l['manage_smilies_desc'] = 'אזור זה מאפשר לערוך או למחוק חייכנים';
$l['add_smilie'] = 'הוסף חייכן חדש';
$l['add_smilie_desc'] = 'כאן תוכל להוסיף חייכן יחיד חדש
';
$l['add_multiple_smilies'] = 'הוסף מספר חייכנים';
$l['add_multiple_smilies_desc'] = 'כאן תוכל להוסיף מס\' חייכנים בבת אחת';
$l['edit_smilie'] = 'ערוך חייכן';
$l['edit_smilie_desc'] = 'כאן תוכל לערוך חייכן יחיד';
$l['mass_edit'] = 'עריכה המונית';
$l['mass_edit_desc'] = 'כאן תוכל לערוך בקלות את כל החייכנים בבת אחת';
$l['no_smilies'] = 'אין חייכנים בפורום שלך נכון לעכשיו';
$l['image'] = 'תמונה';
$l['name'] = 'שם';
$l['text_replace'] = 'טקסט חלופי';
$l['text_replace_desc'] = 'This is the text to replace with the smilie (enter one per line).';
$l['image_path'] = 'כתובת תמונה';
$l['image_path_desc'] = 'This is the path to the smilie image. If you want to use different smilie images for different themes, please use <strong>{theme}</strong> to represent the image directory of each theme.';
$l['order'] = 'סדר';
$l['display_order'] = 'סדר הצגה';
$l['display_order_desc'] = 'The order on the smilies list that this will appear. This number should not be the same as another smilie\'s.';
$l['mass_edit_show_clickable'] = 'Show on Clickable?';
$l['show_clickable'] = 'Show on clickable list?';
$l['show_clickable_desc'] = 'Do you want this smilie to show on the clickable smilie list on the post editor?';
$l['include'] = 'להוסיף?';
$l['path_to_images'] = 'כתובת לתמונות';
$l['path_to_images_desc'] = 'This is the path to the folder that the images are in.';
$l['smilie_delete'] = 'למחוק?';
$l['save_smilie'] = 'שמור חייכן';
$l['save_smilies'] = 'שמור חייכנים';
$l['show_smilies'] = 'הראה חייכנים';
$l['reset'] = 'אתחל (RESET)';
$l['error_missing_name'] = 'You did not enter a name for this smilie.';
$l['error_missing_text_replacement'] = 'You did not enter a text replacement for this smilie.';
$l['error_missing_path'] = 'You did not enter a path for this smilie.';
$l['error_missing_path_multiple'] = 'You did not enter a path.';
$l['error_missing_order'] = 'You did not enter a display order for this smilie.';
$l['error_duplicate_order'] = 'You did not enter a valid display order for this smilie.';
$l['error_missing_clickable'] = 'You did not specify yes or no for the "Show Clickable" option.';
$l['error_no_smilies'] = 'There are no smilies in the specified directory, or all smilies in the directory have already been added.';
$l['error_no_images'] = 'There are no images in the specified directory.';
$l['error_none_included'] = 'You did not select any smilies to include.';
$l['error_invalid_path'] = 'You did not enter a valid path.';
$l['error_invalid_smilie'] = 'The specified smilie does not exist.';
$l['success_smilie_added'] = 'The smilie has been added successfully.';
$l['success_multiple_smilies_added'] = 'The selected smilies have been added successfully.';
$l['success_smilie_updated'] = 'The smilie has been updated successfully.';
$l['success_multiple_smilies_updated'] = 'The smilies have been updated successfully.';
$l['success_smilie_deleted'] = 'The selected smilie has been deleted successfully.';
$l['success_mass_edit_updated'] = 'The smilies have been updated successfully.';
$l['confirm_smilie_deletion'] = 'Are you sure you wish to delete this smilie?';
