<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Sun, 26 Apr 2015 09:57:27 +0000
// --------------------------------------------------------------------------------

$l['configuration'] = 'תצורה';
$l['bbsettings'] = 'הגדרות';
$l['banning'] = 'השעיות';
$l['custom_profile_fields'] = 'שדות מותאמים אישית בפרופיל';
$l['smilies'] = 'סמיילים';
$l['word_filters'] = 'סנן מילים';
$l['mycode'] = 'MyCode';
$l['languages'] = 'שפות';
$l['post_icons'] = 'סמלוני הודעות';
$l['help_documents'] = 'מסמכי עזרה';
$l['plugins'] = 'תוספים';
$l['attachment_types'] = 'קבצים מצורפים';
$l['moderator_tools'] = 'אפשרויות מנהל';
$l['spiders_bots'] = 'עכבישים / רובוטים';
$l['calendars'] = 'לוחות שנה';
$l['warning_system'] = 'מערכת אזהרות';
$l['thread_prefixes'] = 'תיוגי אשכול';
$l['security_questions'] = 'שאלות אבטחה';
$l['can_manage_settings'] = 'יכול לנהל הגדרות?';
$l['can_manage_banned_accounts'] = 'יכול לנהל משתמשים מורחקים?';
$l['can_manage_custom_profile_fields'] = 'Can manage custom profile fields?';
$l['can_manage_smilies'] = 'יכול לנהל סמיילים?';
$l['can_manage_bad_words'] = 'יכול לנהל סינון מילים אסורות?';
$l['can_manage_custom_mycode'] = 'Can manage custom MyCode?';
$l['can_manage_language_packs'] = 'יכול לנהל ערכות שפה?';
$l['can_manage_post_icons'] = 'יכול לנהל אייקוני פוסטים?';
$l['can_manage_help_documents'] = 'Can manage help documents?';
$l['can_manage_plugins'] = 'יכול לנהל פלאגינים?';
$l['can_manage_attachment_types'] = 'יכול לנהל סוגי קבצים מצורפים?';
$l['can_manage_spiders_bots'] = 'יכול לנהל ספיידרס/בוטים?';
$l['can_manage_calendars'] = 'Can manage calendars?';
$l['can_manage_warning_system'] = 'Can manage warning system?';
$l['can_manage_mod_tools'] = 'יכול לנהל כלי משגיחים?';
$l['can_manage_thread_prefixes'] = 'יכול לנהל קידומות נושאים?';
$l['can_manage_security_questions'] = 'יכול לנהל שאלות אבטחה?';
