<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Fri, 01 May 2015 13:47:26 +0000
// --------------------------------------------------------------------------------

$l['forums_and_posts'] = 'פורומים והודעות';
$l['forum_management'] = 'ניהול פורומים';
$l['forum_announcements'] = 'הכרזות פורומים';
$l['moderation_queue'] = 'ממתינים לאישור מנהל';
$l['attachments'] = 'קבצים מצורפים';
$l['can_manage_forums'] = 'יכול לנהל פורומים?';
$l['can_manage_forum_announcements'] = 'יכול לנהל פורום מהכרזות?';
$l['can_moderate'] = 'יכול לנהל פוסטים, נושאים וקבצים מצורפים?';
$l['can_manage_attachments'] = 'יכול לנהל קבצים מצורפים?';
