<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Tue, 28 Apr 2015 16:35:28 +0000
// --------------------------------------------------------------------------------

$l['forum_announcements'] = 'הכרזות פורום';
$l['forum_announcements_desc'] = 'כאן תוכל לנהל את ההכרזות בפורום שלך. הכרזות גלובליות מופיעות בכל הפורומים, בעוד שאלה שמוגדרים לפורומים ספציפיים מוצגים בפורום הזה ובכל תתי הפורום שלו.';
$l['add_announcement'] = 'הוסף הכרזה';
$l['add_announcement_desc'] = 'כאן תוכל להוסיף הכרזה לפורום יחיד או לכל הפורומים.';
$l['update_announcement'] = 'שמור הכרזה';
$l['preview_announcement'] = 'תצוגה מקדימה של הכרזה';
$l['update_announcement_desc'] = 'כאן תוכל לעדכן פרטי הכרזה.';
$l['start_date_desc'] = 'On this date and time (in GMT), the announcement will appear in the selected forum(s).';
$l['end_date_desc'] = 'On this date and time (in GMT), the announcement will be hidden from view on your forum. You may select never end this announcement until you delete it or edit its end date.';
$l['forums_to_appear_in_desc'] = 'The announcement will appear in the forums selected below. The announcement will appear in the selected forum and all child forums of the selected forum.';
$l['announcement'] = 'הכרזה';
$l['global_announcements'] = 'הכרזה גלובלית (כללית)';
$l['no_global_announcements'] = 'אין כרגע הכרזות פורום גלובליות';
$l['no_forums'] = 'There are currently no forums setup to show forum announcements.';
$l['confirm_announcement_deletion'] = 'Are you sure you wish to delete this announcement?';
$l['success_announcement_deleted'] = 'The selected announcement has been deleted successfully.';
$l['success_added_announcement'] = 'The selected announcement has been created successfully.';
$l['success_updated_announcement'] = 'The selected announcement has been updated successfully.';
$l['error_invalid_announcement'] = 'Please input a valid announcement.';
$l['error_missing_title'] = 'לא הכנסת כותרת';
$l['error_missing_message'] = 'You did not enter a message.';
$l['error_missing_forum'] = 'You did not select a forum.';
$l['error_invalid_start_date'] = 'The starting date for the announcement is invalid.';
$l['error_invalid_end_date'] = 'The ending date for the announcement is invalid.';
$l['error_end_before_start'] = 'The ending date must be after the start date.';
$l['add_an_announcement'] = 'הוסף הכרזה';
$l['update_an_announcement'] = 'עדכן הכרזה';
$l['save_announcement'] = 'שמור הכרזה';
$l['title'] = 'כותרת';
$l['start_date'] = 'תאריך התחלה';
$l['end_date'] = 'תאריך סיום';
$l['message'] = 'הודעה';
$l['forums_to_appear_in'] = 'פורומים בהם יופיע';
$l['allow_html'] = 'לאפשר HTML?';
$l['allow_mycode'] = 'לאפשר MyCode?';
$l['allow_smilies'] = 'לאפשר חייכנים? (סמיילים)';
$l['time'] = 'זמן:';
$l['set_time'] = 'הגדר זמן';
$l['announcement_preview'] = 'תצוגה מקדימה של הכרזה';
