<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Tue, 28 Apr 2015 16:39:59 +0000
// --------------------------------------------------------------------------------

$l['attachments'] = 'קבצים מצורפים';
$l['stats'] = 'סטטיסטיקה';
$l['find_attachments'] = 'מצא קבצים מצורפים';
$l['find_attachments_desc'] = 'השתמש במערכת חיפוש הקבצים המצורפים כדי לחפש קבצים ספציפיים שמשתמשים צירפו לפורומים שלך.
התחל ע"י הזנת ביטויי חיפוש למטה. כל השדות הם אופציונליים ולא יוכללו בחיפוש אלא אם הזנת אותם.';
$l['find_orphans'] = 'מצא קבצים מצורפים יתומים';
$l['find_orphans_desc'] = 'קבצים יתומים מצורפים הם קבצים אשר מסיבה כלשהי חסרים במסד הנתונים או מערכת הקבצים.
כלי זה יאפשר לך לאתר אותם ולמחוק אותם.';
$l['attachment_stats'] = 'סטטיסטיקת קבצים מצורפים';
$l['attachment_stats_desc'] = 'למטה ישנם סטטיסטיקות כלליות עבור הקבצים המצורפים כעת בפורום שלך.';
$l['error_nothing_selected'] = 'בחר קובץ מצורף אחד או יותר למחיקה';
$l['error_no_attachments'] = 'לא קיימים קבצים מצורפים בפורום שלך עדיין. ברגע שקובץ מצורף יפורסם תוכל לגשת לאזור זה.';
$l['error_not_all_removed'] = 'Only some orphaned attachments were successfully deleted, others could not be removed from the uploads directory.';
$l['error_invalid_username'] = 'שם המשתמש שהקלדת אינו תקין';
$l['error_invalid_forums'] = 'פורום אחד או יותר שהזנת אינו תקין';
$l['error_no_results'] = 'לא נמצאו קבצים מצורפים עבור חיפוש זה';
$l['error_not_found'] = 'Attachment file could not be found in the uploads directory.';
$l['error_not_attached'] = 'Attachment was uploaded over 24 hours ago but not attached to a post.';
$l['error_does_not_exist'] = 'הנושא/פוסט עבור קובץ זה אינו קיים עוד';
$l['success_deleted'] = 'הקובץ המצורף הנבחר נמחק בהצלחה';
$l['success_orphan_deleted'] = 'The selected orphaned attachments have been deleted successfully.';
$l['success_no_orphans'] = 'אין קבצים מצורפים יתומים בפורום שלך';
$l['confirm_delete'] = 'אתה בטוח שברצונך למחוק את הקבצים המצורפים שנבחרו?';
$l['general_stats'] = 'סטטיסטיקות כלליות';
$l['stats_attachment_stats'] = 'קבצים מצורפים - סטטיסטיקות קבצים מצורפים';
$l['num_uploaded'] = '<strong>מס\' הקבצים שהועלו</strong>';
$l['space_used'] = '<strong>שימוש מוערך בנפח אחסון</strong>';
$l['bandwidth_used'] = '<strong>שימוש תעבורה מוערך</strong>';
$l['average_size'] = '<strong>גודל קובץ ממוצע</strong>';
$l['size'] = 'קובץ';
$l['posted_by'] = 'פורסם ע"י';
$l['thread'] = 'נושא';
$l['downloads'] = 'הורדות';
$l['date_uploaded'] = 'זמן העלאה';
$l['popular_attachments'] = '5 הפופולריים ביותר';
$l['largest_attachments'] = '5 הגדולים ביותר';
$l['users_diskspace'] = 'Top 5 Users Using the Most Disk Space';
$l['username'] = 'שם משתמש';
$l['total_size'] = 'גודל כולל';
$l['orphan_results'] = 'תוצאות חיפוש קבצים מצורפים יתומים';
$l['orphan_attachments_search'] = 'חיפוש קבצים מצורפים יתומים';
$l['reason_orphaned'] = 'סיבת יתמות';
$l['reason_not_in_table'] = 'Not in attachments table';
$l['reason_file_missing'] = 'קובץ מצורף חסר';
$l['reason_thread_deleted'] = 'נושא נמחק';
$l['reason_post_never_made'] = 'פוסט מעולם לא פורסם';
$l['unknown'] = 'לא ידוע';
$l['results'] = 'תוצאות';
$l['step1'] = 'שלב 1';
$l['step2'] = 'שלב 2';
$l['step1of2'] = 'שלב 1 מתוך 2 - סריקת קבצי מערכת';
$l['step2of2'] = 'שלב 2 מתוך 2 - סריקת מסד נתונים';
$l['step1of2_line1'] = 'אנא המתן, המערכת כרגע סורקת אחר קבצים מצורפים יתומים.';
$l['step2of2_line1'] = 'אנא המתן, המסד כרגע סורק אחר קבצים מצורפים יתומים.';
$l['step_line2'] = 'אתה תועבר לשלב הבא אוטומטית ברגע שהתהליך יושלם.';
$l['scanning'] = 'סורק...';
$l['index_find_attachments'] = 'קבצים מצורפים - מצא קבצים';
$l['find_where'] = 'מצא קבצים בהם...';
$l['name_contains'] = 'שם שכולל';
$l['name_contains_desc'] = 'כדי לחפש ע"פ סיומת השתמש בכוכבית.
דוגמה: *.zip
';
$l['type_contains'] = 'סוג קובץ שמכיל';
$l['forum_is'] = 'פורום הוא';
$l['username_is'] = 'שם משתמש המפרסם הינו';
$l['more_than'] = 'יותר מ';
$l['greater_than'] = 'גדול מ';
$l['is_exactly'] = 'בדיוק';
$l['less_than'] = 'פחות מ';
$l['date_posted_is'] = 'זמן הפרסום הוא';
$l['days_ago'] = 'לפני מס\' ימים';
$l['file_size_is'] = 'גודל הקובץ הוא';
$l['kb'] = 'KB';
$l['download_count_is'] = 'מונה ההורדות הינו';
$l['display_options'] = 'אפשרויות תצוגה';
$l['filename'] = 'שם הקובץ';
$l['filesize'] = 'גודל הקובץ';
$l['download_count'] = 'מונה הורדות';
$l['post_username'] = 'שם משתמש המפרסם';
$l['asc'] = 'יורד';
$l['desc'] = 'עולה';
$l['sort_results_by'] = 'סדר תוצאות ע"פ';
$l['results_per_page'] = 'תוצאות לעמוד';
$l['in'] = 'ב';
$l['button_delete_orphans'] = 'מחק יתומים שנבחרו';
$l['button_delete_attachments'] = 'מחק קבצים שנבחרו';
$l['button_find_attachments'] = 'מצא קבצים מצורפים';
