<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Sat, 25 Apr 2015 13:43:29 +0000
// --------------------------------------------------------------------------------

$l['akismet'] = 'Akismet';
$l['akismet_desc'] = 'Akismet היא תוכנה המונעת ספאם בפורום שלך.';
$l['can_manage_akismet'] = 'Can Manage Akismet?';
$l['title'] = 'כותרת';
$l['detected_spam_messages'] = 'זהה הודעות ספאם';
$l['unmark_selected'] = 'Unmark Selected';
$l['deleted_selected'] = 'מחק בחירה';
$l['delete_all'] = 'מחק הכל';
$l['success_deleted_spam'] = 'כל הודעות הספאם שזוהו נמחקו בהצלחה';
$l['success_unmarked'] = 'ההודעות שסומנו אינן מזוהות כספאם עוד';
$l['success_spam_deleted'] = 'הודעות הספאם שנבחרו נמחקו בהצלחה';
$l['confirm_spam_deletion'] = 'האם אתה בטוח שברצונך למחוק את כל הודעות הספאם שזוהו?';
$l['error_deletepost'] = 'אתה חייב לבחור לפחות פוסט אחד למחיקה';
$l['error_unmark'] = 'You must select at least one post to unmark.';
$l['no_spam_found'] = ' Akismet לא זיהה הודעות ספאם נכון לעכשיו.';
