<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Tue, 28 Apr 2015 16:36:28 +0000
// --------------------------------------------------------------------------------

$l['moderation_queue'] = 'רשימת ניהול';
$l['threads'] = 'נושאים';
$l['threads_desc'] = 'כאן תוכל לאשר נושאים שברשימת הניהול';
$l['posts'] = 'פוסטים';
$l['posts_desc'] = 'Here you can view and approve posts in the moderation queue.';
$l['attachments'] = 'קבצים מצורפים';
$l['attachments_desc'] = 'Here you can view and approve attachments in the moderation queue.
';
$l['threads_awaiting_moderation'] = 'נושאים המחכים לניהול';
$l['posts_awaiting_moderation'] = 'פוסטים המחכים לניהול';
$l['attachments_awaiting_moderation'] = 'קבצים מצורפים הממתינים לניהול';
$l['error_no_posts'] = 'אין פוסטים קיימים הממתינים לניהול';
$l['error_no_attachments'] = 'אין קבצים מצורפים הממתינים לניהול';
$l['error_no_threads'] = 'אין פוסטים, נושאים או קבצים מצורפים הממתינים כעת לניהול.';
$l['success_threads'] = 'הנושאים הנבחרים נוהלו בהצלחה';
$l['success_posts'] = 'הפוסטים הנבחרים נוהלו בהצלחה';
$l['success_attachments'] = 'הקבצים המצורפים הנבחרים נוהלו בהצלחה.';
$l['subject'] = 'נושא';
$l['author'] = 'ע"י';
$l['posted'] = 'פורסם';
$l['ignore'] = 'התעלם';
$l['approve'] = 'אשר';
$l['forum'] = 'פורום:';
$l['thread'] = 'נושא:';
$l['post'] = 'פוסט:';
$l['re'] = 'RE:';
$l['filename'] = 'שם קובץ';
$l['uploadedby'] = 'הועלה ע"י';
$l['controls'] = 'Controls';
$l['mark_as_ignored'] = 'סמן כולם להתעלמות';
$l['mark_as_deleted'] = 'סמן כולם למחיקה';
$l['mark_as_approved'] = 'סמן כולם לאישור';
$l['perform_action'] = 'אשר פעולות';
