<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Sun, 26 Apr 2015 10:09:35 +0000
// --------------------------------------------------------------------------------

$l['today'] = 'היום';
$l['yesterday'] = 'אתמול';
$l['size_yb'] = 'YB';
$l['size_zb'] = 'ZB';
$l['size_eb'] = 'EB';
$l['size_pb'] = 'PB';
$l['size_tb'] = 'TB';
$l['size_gb'] = 'GB';
$l['size_mb'] = 'MB';
$l['size_kb'] = 'KB';
$l['size_bytes'] = 'בייטים';
$l['na'] = 'לא זמין';
$l['mybb_admin_panel'] = 'לוח הבקרה של MyBB';
$l['mybb_admin_cp'] = 'לוח בקרת אדמין';
$l['logged_in_as'] = 'מחובר כ- ';
$l['view_board'] = 'צפה בפורום';
$l['logout'] = 'התנתק';
$l['generated_in'] = 'נטען ב {1} עם <a href="{2}" target="_blank">{3} שאילתות</a>. זיכרון בשימוש: {4}';
$l['enter_username_and_password'] = 'אנא הזן את {1} והסיסמה שלך בכדי להמשיך.';
$l['login_username'] = 'שם המשתמש';
$l['login_email'] = 'האימייל';
$l['login_username_and_password'] = 'שם המשתמש / האימייל';
$l['mybb_admin_login'] = 'לוח הבקרה של MyBB - התחברות';
$l['return_to_forum'] = 'חזור לפורום';
$l['please_login'] = 'אנא התחבר';
$l['username'] = 'שם משתמש:';
$l['username1'] = 'אימייל:';
$l['username2'] = 'שם משתמש / אימייל:';
$l['password'] = 'סיסמה:';
$l['secret_pin'] = 'קוד סודי:';
$l['login'] = 'התחבר';
$l['lost_password'] = 'שכחת את הסיסמה?';
$l['error_invalid_admin_session'] = 'סייישן מנהל לא חוקי.';
$l['error_admin_session_expired'] = 'סיישן המנהל שלך פג תוקף.';
$l['error_invalid_ip'] = 'כתובת ה IP שלך אינה מתאימה לסיישן המנהל שלך.';
$l['error_mybb_admin_lockedout'] = 'הגישה לפאנל הניהול שלך נחסמה.';
$l['error_mybb_admin_lockedout_message'] = 'Your account is currently locked out after failing to login {1} times. You have been sent an email with instructions on how to unlock your account.';
$l['error_invalid_secret_pin'] = 'הקוד האישי שהזנת שגוי.';
$l['error_invalid_username'] = 'שם המשתמש שהזנת שגוי.';
$l['error_invalid_uid'] = 'זיהוי המשתמש שהזנת אינו חוקי.';
$l['error_invalid_token'] = 'קוד ההפעלה שהזנת אינו חוקי.';
$l['success_logged_out'] = 'התנתקת מהמערכת בהצלחה.';
$l['error_invalid_username_password'] = 'The {1} and password combination you entered is invalid.';
$l['confirm_action'] = 'האם אתה בטוח שברצונך לבצע פעולה זו?';
$l['home'] = 'דף הבית';
$l['name'] = 'שם';
$l['size'] = 'גודל';
$l['controls'] = 'אפשרויות';
$l['view'] = 'צפייה';
$l['yes'] = 'כן';
$l['no'] = 'לא';
$l['cancel'] = 'ביטול';
$l['options'] = 'אפשרויות';
$l['proceed'] = 'המשך';
$l['ok'] = 'אוקיי';
$l['error'] = 'שגיאה';
$l['edit'] = 'ערוך';
$l['never'] = 'אף פעם';
$l['legend'] = 'אורך';
$l['version'] = 'גירסא';
$l['languagevar'] = 'שפה';
$l['use_default'] = 'השתמש בברירת מחדל';
$l['file'] = 'קובץ';
$l['go'] = 'עבור';
$l['clear'] = 'נקה';
$l['unknown'] = 'לא ידוע';
$l['year'] = 'שנה';
$l['year_short'] = 'שנה';
$l['years'] = 'שנים';
$l['years_short'] = 'שנים';
$l['month'] = 'חודש';
$l['month_short'] = 'חודש';
$l['months'] = 'חודשים';
$l['months_short'] = 'חודשים';
$l['week'] = 'שבוע';
$l['week_short'] = 'שבוע';
$l['weeks'] = 'שבועות';
$l['weeks_short'] = 'שבועות';
$l['day'] = 'יום';
$l['day_short'] = 'יום';
$l['days'] = 'ימים';
$l['days_short'] = 'ימים';
$l['hour'] = 'שעה';
$l['hour_short'] = 'שעה';
$l['hours'] = 'שעות';
$l['hours_short'] = 'שעות';
$l['minute'] = 'דקה';
$l['minute_short'] = 'דקה';
$l['minutes'] = 'דקות';
$l['minutes_short'] = 'דקות';
$l['second'] = 'שניה';
$l['second_short'] = 'שניה';
$l['seconds'] = 'שניות';
$l['seconds_short'] = 'שניות';
$l['permanent'] = 'לנצח';
$l['all_forums'] = 'כל הפורומים';
$l['all_groups'] = 'כל הקבוצות';
$l['select_forums'] = 'בחר פורומים';
$l['select_groups'] = 'בחר קבוצות';
$l['forums_colon'] = 'פורומים:';
$l['groups_colon'] = 'קבוצות:';
$l['none'] = 'אף אחד';
$l['mybb_acp'] = 'לוח הבקרה של MyBB';
$l['pages'] = 'עמודים';
$l['previous'] = 'קודם';
$l['page'] = 'עמוד';
$l['next'] = 'הבא';
$l['delete'] = 'מחק';
$l['reset'] = 'אפס';
$l['and'] = 'ו';
$l['on'] = 'דלוק';
$l['off'] = 'כבוי';
$l['alt_enabled'] = 'מופעל';
$l['alt_disabled'] = 'מבוטל';
$l['saved'] = 'שמור';
$l['rel_in'] = 'ב ';
$l['rel_ago'] = 'לפני';
$l['rel_less_than'] = 'לפני פחות מ';
$l['rel_time'] = '{4} {1}{2} {3}';
$l['rel_minutes_single'] = 'דקה';
$l['rel_minutes_plural'] = 'דקות';
$l['rel_hours_single'] = 'שעה';
$l['rel_hours_plural'] = 'שעות';
$l['quote'] = 'ציטוט:';
$l['wrote'] = 'כתב:';
$l['code'] = 'קוד:';
$l['php_code'] = 'קוד PHP:';
$l['linkback'] = 'ההודעה המקורית';
$l['january'] = 'ינואר';
$l['february'] = 'פברואר';
$l['march'] = 'מרץ';
$l['april'] = 'אפריל';
$l['may'] = 'מאי';
$l['june'] = 'יוני';
$l['july'] = 'יולי';
$l['august'] = 'אוגוסט';
$l['september'] = 'ספטמבר';
$l['october'] = 'אוקטובר';
$l['november'] = 'נובמבר';
$l['december'] = 'דצמבר';
$l['access_denied'] = 'גישה נדחתה';
$l['access_denied_desc'] = 'אין לך גישה לחלק הזה של לוח הבקרה';
$l['cannot_perform_action_super_admin_general'] = 'Sorry, but you cannot perform this action because you are not a super administrator.<br /><br />To be able to perform this action, you need to add your user ID to the list of super administrators in inc/config.php.';
$l['loading_text'] = 'טוען<br />אנא המתן...';
$l['timezone_gmt_minus_1200'] = '(GMT -12:00) Marshall Islands';
$l['timezone_gmt_minus_1100'] = '(GMT -11:00) Nome, Midway Island';
$l['timezone_gmt_minus_1000'] = '(GMT -10:00) Hawaii, Papeete';
$l['timezone_gmt_minus_950'] = '(GMT -9:30) Marquesas Islands';
$l['timezone_gmt_minus_900'] = '(GMT -9:00) Alaska';
$l['timezone_gmt_minus_800'] = '(GMT -8:00) Pacific Time';
$l['timezone_gmt_minus_700'] = '(GMT -7:00) Mountain Time';
$l['timezone_gmt_minus_600'] = '(GMT -6:00) Central Time, Mexico City';
$l['timezone_gmt_minus_500'] = '(GMT -5:00) Eastern Time, Bogota, Lima, Quito';
$l['timezone_gmt_minus_450'] = '(GMT -4:30) Caracas';
$l['timezone_gmt_minus_400'] = '(GMT -4:00) Atlantic Time, La Paz, Halifax';
$l['timezone_gmt_minus_350'] = '(GMT -3:30) Newfoundland';
$l['timezone_gmt_minus_300'] = '(GMT -3:00) Brazil, Buenos Aires, Georgetown, Falkland Is.';
$l['timezone_gmt_minus_200'] = '(GMT -2:00) Mid-Atlantic, South Georgia and the South Sandwich Islands';
$l['timezone_gmt_minus_100'] = '(GMT -1:00) Azores, Cape Verde Islands';
$l['timezone_gmt'] = '(GMT) Casablanca, Dublin, Edinburgh, London, Lisbon, Monrovia';
$l['timezone_gmt_100'] = '(GMT +1:00) Berlin, Brussels, Copenhagen, Madrid, Paris, Rome, Warsaw';
$l['timezone_gmt_200'] = '(GMT +2:00) Athens, Istanbul, Cairo, Jerusalem, South Africa';
$l['timezone_gmt_300'] = '(GMT +3:00) Kaliningrad, Minsk, Baghdad, Riyadh, Nairobi';
$l['timezone_gmt_350'] = '(GMT +3:30) Tehran';
$l['timezone_gmt_400'] = '(GMT +4:00) Moscow, Abu Dhabi, Baku, Muscat, Tbilisi';
$l['timezone_gmt_450'] = '(GMT +4:30) Kabul';
$l['timezone_gmt_500'] = '(GMT +5:00) Islamabad, Karachi, Tashkent';
$l['timezone_gmt_550'] = '(GMT +5:30) Mumbai, Calcutta, Madras, New Delhi';
$l['timezone_gmt_575'] = '(GMT +5:45) Kathmandu';
$l['timezone_gmt_600'] = '(GMT +6:00) Almaty, Dhakra, Yekaterinburg';
$l['timezone_gmt_650'] = '(GMT +6:30) Yangon';
$l['timezone_gmt_700'] = '(GMT +7:00) Bangkok, Hanoi, Jakarta';
$l['timezone_gmt_800'] = '(GMT +8:00) Beijing, Hong Kong, Perth, Singapore, Taipei, Manila';
$l['timezone_gmt_900'] = '(GMT +9:00) Osaka, Sapporo, Seoul, Tokyo, Irkutsk';
$l['timezone_gmt_950'] = '(GMT +9:30) Adelaide, Darwin';
$l['timezone_gmt_1000'] = '(GMT +10:00) Melbourne, Papua New Guinea, Sydney, Yakutsk';
$l['timezone_gmt_1050'] = '(GMT +10:30) Lord Howe Island';
$l['timezone_gmt_1100'] = '(GMT +11:00) Magadan, New Caledonia, Solomon Islands, Vladivostok';
$l['timezone_gmt_1150'] = '(GMT +11:30) Norfolk Island';
$l['timezone_gmt_1200'] = '(GMT +12:00) Auckland, Wellington, Fiji, Marshall Island';
$l['timezone_gmt_1275'] = '(GMT +12:45) Chatham Islands';
$l['timezone_gmt_1300'] = '(GMT +13:00) Samoa, Tonga, Tokelau';
$l['timezone_gmt_1400'] = '(GMT +14:00) Line Islands';
$l['timezone_gmt_short'] = 'GMT {1}({2})';
$l['confirm_delete_logs'] = 'Prune the selected log entries?';
$l['confirm_delete_all_logs'] = 'Prune all log entries?';
$l['selected_logs_deleted'] = 'The selected log entries have been deleted.';
$l['all_logs_deleted'] = 'All log entries have been deleted.';
$l['delete_selected'] = 'מחק מסומנים';
$l['delete_all'] = 'מחק את כל המסוננים.';
$l['encountered_errors'] = 'השגיאות הבאות אירעו:';
$l['invalid_post_verify_key'] = 'An authorization code mismatch occurred. Please confirm that you wish to perform the action below.';
$l['invalid_post_verify_key2'] = 'An authorization code mismatch occurred. Please double check that you are accessing this page correctly.';
$l['unknown_error'] = 'שגיאה לא ידועה אירעה.';
$l['editor_bold'] = 'מודגש';
$l['editor_italic'] = 'נטוי';
$l['editor_underline'] = 'קו תחתון';
$l['editor_strikethrough'] = 'מחוק';
$l['editor_subscript'] = 'Subscript';
$l['editor_superscript'] = 'Superscript';
$l['editor_alignleft'] = 'הצמד לשמאל';
$l['editor_center'] = 'מרכז';
$l['editor_alignright'] = 'הצמד לימין';
$l['editor_justify'] = 'הצדק';
$l['editor_fontname'] = 'שם פונט';
$l['editor_fontsize'] = 'גודל פונט';
$l['editor_fontcolor'] = 'צבע פונט';
$l['editor_removeformatting'] = 'Remove Formatting';
$l['editor_cut'] = 'גזור';
$l['editor_copy'] = 'העתק';
$l['editor_paste'] = 'הדבק';
$l['editor_cutnosupport'] = 'Your browser does not allow the cut command. Please use the keyboard shortcut Ctrl/Cmd-X';
$l['editor_copynosupport'] = 'Your browser does not allow the copy command. Please use the keyboard shortcut Ctrl/Cmd-C';
$l['editor_pastenosupport'] = 'Your browser does not allow the paste command. Please use the keyboard shortcut Ctrl/Cmd-V';
$l['editor_pasteentertext'] = 'Paste your text inside the following box:';
$l['editor_pastetext'] = 'הדבק טקסט';
$l['editor_numlist'] = 'רשימה ממוספרת';
$l['editor_bullist'] = 'Bullet list';
$l['editor_undo'] = 'בטל';
$l['editor_redo'] = 'עשה שוב';
$l['editor_rows'] = 'שורות:';
$l['editor_cols'] = 'עמודות:';
$l['editor_inserttable'] = 'הכנס טבלה';
$l['editor_inserthr'] = 'Insert a horizontal rule';
$l['editor_code'] = 'קוד';
$l['editor_php'] = 'PHP';
$l['editor_width'] = 'אורך (אופציונאלי):';
$l['editor_height'] = 'גובה (אופציונאלי):';
$l['editor_insertimg'] = 'הכנס תמונה';
$l['editor_email'] = 'E-mail:';
$l['editor_insertemail'] = 'הכנס אימייל';
$l['editor_url'] = 'URL:';
$l['editor_insertlink'] = 'הכנס לינק';
$l['editor_unlink'] = 'הסר לינק';
$l['editor_more'] = 'עוד';
$l['editor_insertemoticon'] = 'Insert an emoticon';
$l['editor_videourl'] = 'כתובת וידאו:';
$l['editor_videotype'] = 'סוג וידאו:';
$l['editor_insert'] = 'הכנס';
$l['editor_insertyoutubevideo'] = 'Insert a YouTube video';
$l['editor_currentdate'] = 'הכנס תאריך נוכחי:';
$l['editor_currenttime'] = 'הכנס זמן נוכחי:';
$l['editor_print'] = 'הדפס';
$l['editor_viewsource'] = 'View source';
$l['editor_description'] = 'Description (optional):';
$l['editor_enterimgurl'] = 'הכנס כתובת תמונה:';
$l['editor_enteremail'] = 'Enter the e-mail address:';
$l['editor_enterdisplayedtext'] = 'Enter the displayed text:';
$l['editor_enterurl'] = 'הכנס כתובת:';
$l['editor_enteryoutubeurl'] = 'Enter the YouTube video URL or ID:';
$l['editor_insertquote'] = 'הכנס ציטוט:';
$l['editor_invalidyoutube'] = 'Invalid YouTube video';
$l['editor_dailymotion'] = 'Dailymotion';
$l['editor_metacafe'] = 'MetaCafe';
$l['editor_veoh'] = 'Veoh';
$l['editor_vimeo'] = 'Vimeo';
$l['editor_youtube'] = 'Youtube';
$l['editor_facebook'] = 'Facebook';
$l['editor_liveleak'] = 'LiveLeak';
$l['editor_insertvideo'] = 'הכנס סרטון';
$l['editor_maximize'] = 'Maximize';
$l['missing_task'] = 'שגיאה: המשימה לא נמצאה';
$l['task_backup_cannot_write_backup'] = 'Error: The database backup task cannot write to backups directory.';
$l['task_backup_ran'] = 'משימת גיבוי המסד הורצה בהצלחה.';
$l['task_checktables_ran'] = 'The check tables task successfully ran with no corrupted tables found.';
$l['task_checktables_ran_found'] = 'Notice: The check tables task successfully ran and repaired the {1} table(s).';
$l['task_dailycleanup_ran'] = 'משימת הנקיון היומי רצה בהצלחה';
$l['task_hourlycleanup_ran'] = 'משימת "נקיון כל שעה" בוצעה';
$l['task_logcleanup_ran'] = 'The log cleanup task successfully ran and pruned any old logs.';
$l['task_promotions_ran'] = 'The promotions task successfully ran.';
$l['task_threadviews_ran'] = 'The thread views task successfully ran.';
$l['task_usercleanup_ran'] = 'The user cleanup task successfully ran.';
$l['task_massmail_ran'] = 'The mass mail task successfully ran.';
$l['task_userpruning_ran'] = 'The user pruning task successfully ran.';
$l['task_delayedmoderation_ran'] = 'The delayed moderation task successfully ran.';
$l['task_massmail_ran_errors'] = 'One or more problems occurred sending to "{1}":

{2}';
$l['task_versioncheck_ran'] = 'The version check task successfully ran.';
$l['task_versioncheck_ran_errors'] = 'Could not connect to MyBB for a version check.';
$l['task_recachestylesheets_ran'] = 'Re-cached {1} stylesheets.';
$l['massmail_username'] = 'שם משתמש';
$l['email_addr'] = 'כתובת אימייל';
$l['board_name'] = 'שם הפורום';
$l['board_url'] = 'כתובת הפורום';
$l['lockout_unlock'] = 'בטל נעילת לוח הבקרה';
$l['enter_username_and_token'] = 'אנא הזן את שם המשתמש שלך ואת קוד ההפעלה.';
$l['unlock_token'] = 'קוד הפעלה:';
$l['unlock_account'] = 'בטל נעילת משתמש';
$l['locked_out_subject'] = 'משתמש המנהל ננעל ב-{1}';
$l['locked_out_message'] = '{1},



Your administrator account at {2} has been locked after {3} failed login attempts.



To unlock your account, please go to the URL below in your web browser.



{4}/{5}/index.php?action=unlock&uid={7}&token={6}



If the above link does not work correctly, go to



{4}/{5}/index.php?action=unlock



You will need to enter the following:

Username: {1}

Activation Code: {6}



Thank you,

{2} Staff';
$l['comma'] = ', ';
