<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Sun, 26 Apr 2015 11:28:02 +0000
// --------------------------------------------------------------------------------

$l['preferences_and_personal_notes'] = 'העדפות והערות אישיות';
$l['prefs_and_personal_notes_description'] = 'כאן תוכל לנהל את העדפות פאנל הניהול למנהל המערכת ולהשאיר הערות אישיות לעצמך.';
$l['preferences'] = 'העדפות';
$l['global_preferences'] = 'העדפות גלובאליות';
$l['acp_theme'] = 'עיצוב לוח הבקרה';
$l['select_acp_theme'] = 'אנא בחר את העיצוב עליו יופעל לוח הבקרה';
$l['acp_language'] = 'שפת לוח הבקרה';
$l['select_acp_language'] = 'אנא בחר את השפה עליה יופעל לוח הבקרה';
$l['notes_not_shared'] = 'הערות אלו אינן מוצגות למנהלים אחרים';
$l['save_notes_and_prefs'] = 'שמור הערות אישיות והעדפות';
$l['personal_notes'] = 'הערות אישיות';
$l['codemirror'] = 'הפעל / כבר עורך קוד';
$l['use_codemirror_desc'] = 'העדפה זו מאפשרת לך לכבות את עורך קוד (משומש לעריכת תבנית ועריכת גליונות CSS עבור הדגשת התחביר) אם אתה נתקלת בבעיות / איטית.';
$l['success_preferences_updated'] = 'ההעדפות נשמרו בהצלחה.';
