<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Sun, 26 Apr 2015 11:23:49 +0000
// --------------------------------------------------------------------------------

$l['mybb_credits'] = 'קרדיטים ל MyBB.';
$l['mybb_credits_description'] = 'האנשים הללו השקיעו מזמנם החופשי בכדי ליצור את MyBB.';
$l['about_the_team'] = 'אודות הצוות';
$l['check_for_updates'] = 'בדוק עדכוני צוות';
$l['error_communication'] = 'ארעה שגיאה בהורדת קובץ הקרדיטים. אנא נסה בעוד מספר דקות.';
$l['no_credits'] = 'לא נמצאו קרדיטים ל-MyBB. <a href="index.php?module=home-credits&amp;fetch_new=1">חפש עדכונים</a>.';
