<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Mon, 27 Apr 2015 19:32:21 +0000
// --------------------------------------------------------------------------------

$l['version_check'] = 'בדיקת גרסה';
$l['version_check_description'] = 'כאן אתה יכול לבדוק שאתה מפעיל כרגע את העותק האחרון של MyBB ותראה את ההכרזות האחרונות ישירות מMyBB.';
$l['latest_mybb_announcements'] = 'הכרזות אחרונות מ MyBB';
$l['dl_the_latest_mybb'] = 'הורד את הגרסה האחרונה של MyBB';
$l['check_plugin_versions'] = 'בדוק גרסאות תוספים';
$l['your_version'] = 'הגרסה שלך';
$l['latest_version'] = 'הגרסה האחרונה';
$l['update_forum'] = 'Please upgrade to the latest version of MyBB by visiting the <a href="http://mybb.com" target="_blank">MyBB Website</a>.
אנא שדרג לגרסא האחרונה של MyBB דרך  <a href="http://mybb.com" target="_blank">האתר הרשמי</a.';
$l['read_more'] = 'קרא עוד';
$l['success_up_to_date'] = 'ברכות, אתה מפעיל את הגרסה האחרונה של MyBB.';
$l['error_out_of_date'] = 'העותק של MyBB שלך אינו מעודכן.';
$l['error_communication'] = 'הייתה בעיה בחיבור עם השרת. אנא נסה בעוד מספר דקות.';
$l['error_fetch_news'] = 'MyBB לא הצליח להשיג את ההכרזות האחרונות מהאתר הרשמי.';
