<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Mon, 27 Apr 2015 20:33:37 +0000
// --------------------------------------------------------------------------------

$l['dashboard'] = 'לוח הבקרה';
$l['dashboard_description'] = 'סעיף זה מאפשר לך לראות חלק מהסטטיסטיקות השונות הנוגעות לפורום שלך.. אתה יכול גם להוסיף הערות אחרות עבור המנהלים האחרים כדי שיראו.';
$l['mybb_server_stats'] = 'סטטיסטיקות MyBB והשרת';
$l['forum_stats'] = 'סטטיסטיקות הפורום';
$l['mybb_version'] = 'גרסאת MyBB';
$l['threads'] = 'נושאים';
$l['new_today'] = 'חדשים היום';
$l['unapproved'] = 'לא מאושרים';
$l['php_version'] = 'גרסאת PHP';
$l['posts'] = 'הודעות';
$l['sql_engine'] = 'מנוע SQL';
$l['users'] = 'משתמשים';
$l['registered_users'] = 'משתמשים רשומים';
$l['active_users'] = 'משתמשים פעילים';
$l['registrations_today'] = 'הרשמות היום';
$l['awaiting_activation'] = 'ממתינים לאישור';
$l['server_load'] = 'טעינת השרת';
$l['attachments'] = 'קבצים מצורפים';
$l['used'] = 'משומש';
$l['reported_posts'] = 'הודעות מדווחות';
$l['unread_reports'] = 'דיווחים שלא נקראו';
$l['version_check'] = 'בדוק עדכוני מערכת';
$l['last_update_check_two_weeks'] = 'בדיקת <a href="{1}">גרסאת ה-MyBB </a> הייתה לפני יותר משבועיים.';
$l['new_version_available'] = 'אתה מריץ כעת {1} בעוד שהגרסא האחרונה הזמינה באופן כללי היא {2}.';
$l['version_check_description'] = 'כאן אתה יכול לבדוק את הגרסא הנוכחית של עותק הMyBB ולראות הכרזות ישירות מMyBB.';
$l['latest_mybb_announcements'] = 'הכרזות MyBB אחרונות';
$l['no_announcements'] = 'אין הכרזות שמורות. <a href="index.php?module=home&amp;action=version_check">בדוק עדכונים</a>.';
$l['your_version'] = 'הגרסה שלך';
$l['latest_version'] = 'הגרסה האחרונה';
$l['update_forum'] = 'אנא שדרג לגרסא האחרונה של MyBB <a href="http://www.mybb.com" target="_blank">באתר הרשמי</a> ';
$l['read_more'] = 'קרא עוד';
$l['success_up_to_date'] = 'ברכות, אתה מפעיל את הגרסה האחרונה של MyBB.';
$l['error_out_of_date'] = 'עותק ה MyBB שלך אינו מעודכן.';
$l['error_communication'] = 'הייתה בעיה בתקשורת עם השרת. אנא נסה שוב בעוד כמה דקות.';
$l['error_fetch_news'] = 'MyBB נכשל להשיג את הההכרזות האחרונות מהאתר הרשמי.';
$l['news_description'] = 'החדשות האחרונות מה<a href="http://blog.mybb.com/" target="_blank">בלוג של MyBB</a>.';
$l['admin_notes_public'] = 'הערות אלו מוצגות לכל המנהלים';
$l['admin_notes'] = 'הערות מנהל';
$l['save_notes'] = 'שמור הערות';
$l['success_notes_updated'] = 'הערות המנהל נשמרו בהצלחה';
