<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Sat, 25 Apr 2015 14:13:01 +0000
// --------------------------------------------------------------------------------

$l['plugname'] = '"פוסטים אחרונים" בתפריט הצד';
$l['plugdesc'] = 'מראה את הפוסטים האחרונים בפורום שלך';
$l['settings_name'] = 'הגדרות ה"פוסטים האחרונים"';
$l['num_posts_to_show'] = 'כמה פוסטים להראות?';
$l['forums_to_skip'] = 'על איזה פורומים לדלג?';
$l['latestposts_showtime'] = 'להראות את זמן הפוסט האחרון?';
$l['forums_to_skip_desc'] = 'The ID of the forums that you dont want to show posts from them. Separated by commas.';
$l['rightorleft'] = 'להראות בצד ימין או שמאל?';
$l['latestposts_right'] = 'צד ימין';
$l['latestposts_left'] = 'צד שמאל';
