<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Fri, 01 May 2015 13:46:43 +0000
// --------------------------------------------------------------------------------

$l['templates_and_style'] = 'תבניות ועיצובים';
$l['themes'] = 'עיצובים';
$l['templates'] = 'תבניות';
$l['can_manage_themes'] = 'יכול לנהל ערכות נושא?';
$l['can_manage_templates'] = 'יכול לנהל תבניות?';
