<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Fri, 01 May 2015 13:08:10 +0000
// --------------------------------------------------------------------------------

$l['template_sets'] = 'ערכות תבניות';
$l['template_set'] = 'ערכת תבנית';
$l['templates'] = 'תבניות {1}';
$l['manage_template_sets'] = 'נהל ערכות תבניות';
$l['manage_template_sets_desc'] = 'כאן תוכל לנהל ערכת תבניות, לצפות בתבניות שמשתמשות בהגדרות אלה ולהתחיל להתאים אישית את מבנה התצוגה החיצונית של הלוח שלך.';
$l['add_set'] = 'הוסף ערכה';
$l['add_set_desc'] = 'כאן תוכל ליצור תבנית חדשה. תבנית חדשה יוצרת עותק של תבנית MyBB הראשית ותאפשר לך לערוך אותם מבלי להפריע לשינויים של התבניות האחרות.';
$l['add_template'] = 'הוסף תבנית';
$l['add_template_desc'] = 'כאן אתה יכול להוסיף תבנית חדשה';
$l['add_template_group'] = 'הוסף קבוצת תבניות';
$l['add_template_group_desc'] = 'הוסף קבוצת תבנית כדי לאסוף תבניות יחד.';
$l['search_replace'] = 'חפש/החלף';
$l['search_replace_desc'] = 'כלי זה מאפשר לך לחפש כותרות תבניות, או תבניות שמכילות טקסט מסויים או כאפשרות להחליף אותו בטקסט אחר אוטומטית.';
$l['find_updated'] = 'חפש תבניות שעודכנו';
$l['find_updated_desc'] = 'מאפשר לך למצוא תבניות ששונו בגרסא החדשה של MyBB כך שתוכל להפעיל את השינויים כמו שצריך.';
$l['edit_template'] = 'ערוך תבנית';
$l['editing_template'] = 'עריכת תבנית: {1}';
$l['edit_template_desc'] = 'כאן תוכל לערוך את קוד התבנית, כותרתה או ערכתה.';
$l['edit_set'] = 'הוסף ערכה';
$l['edit_set_desc'] = 'כאן תוכל לערוך את מאפייני ערכת התבנית';
$l['manage_templates'] = 'נהל תבניות';
$l['manage_templates_desc'] = 'Here you can manage the templates for this template set. To edit a template click on it\'s link or select "Full Edit" to edit all properties on a separate page.';
$l['diff_report'] = 'דיווח הבדלים';
$l['diff_report_desc'] = 'Performs a difference analysis between the templates and shows you exactly what changes have been made between your customized copy and the latest master copy.';
$l['title'] = 'כותרת';
$l['save'] = 'שמור';
$l['search_for'] = 'חפש עבור';
$l['replace_with'] = 'החלף ב (לא חובה)';
$l['reset'] = 'אתחל (RESET)';
$l['find_templates'] = 'מצא תבניות';
$l['find_and_replace'] = 'מצא והחלף';
$l['search_template_names'] = 'חפש שמות תבניות';
$l['ungrouped_templates'] = 'תבניות חסרות קבוצה';
$l['search_noneset'] = 'לא הכנסת טקסט לחיפוש';
$l['search_results'] = 'תוצאות חיפוש התבנית';
$l['search_header'] = 'מחפש עבור "{1}" ב{2}';
$l['search_updated'] = 'עודכן{1}';
$l['search_found'] = 'נמצא ב {1}';
$l['search_created_custom'] = 'צור תבנית מותאמת אישית עבור {1}';
$l['search_edit'] = 'ערוך';
$l['search_change_original'] = 'שנה מקורי';
$l['search_noresults'] = 'לא נמצאו תבניות המכילות  \'<strong>{1}</strong>\'';
$l['search_noresults_title'] = 'לא נמצאו תבניות עם הכותרת \'<strong>{1}</strong>\'';
$l['default_templates'] = 'תבניות ברירת מחדל';
$l['edit_template_breadcrumb'] = 'ערוך תבנית:';
$l['global_templates'] = 'תבניות גלובאליות';
$l['master_templates'] = 'תבניות ראשיות';
$l['not_used_by_any_themes'] = 'לא משומש ע"י שום עיצוב';
$l['used_by'] = 'משומש ע"י:';
$l['used_by_all_themes'] = 'משומש ע"י כל העיצובים';
$l['expand_templates'] = 'הרחב את התבניות';
$l['edit_template_set'] = 'ערוך קבוצת תבניות';
$l['delete_template_set'] = 'מחק קבוצת תבניות';
$l['empty_template_set'] = '<em>אין תבניות בערכה זו</em>';
$l['inline_edit'] = 'עריכה מהירה';
$l['full_edit'] = 'עריכה מלאה';
$l['revert_to_orig'] = 'החזר למקורי';
$l['delete_template'] = 'מחק תבנית';
$l['edit_in'] = 'ערוך ב';
$l['group_calendar'] = 'לוח שנה';
$l['group_forumdisplay'] = 'הצגת פורום';
$l['group_index'] = 'דף הבית';
$l['group_error'] = 'הודעת שגיאה';
$l['group_memberlist'] = 'רשימת משתמשים';
$l['group_multipage'] = 'עימוד מרובה';
$l['group_private'] = 'הודעות פרטיות';
$l['group_portal'] = 'פורטל';
$l['group_postbit'] = 'איזור ההודעות';
$l['group_posticons'] = 'סמלי הודעה';
$l['group_showthread'] = 'הצגת נושא';
$l['group_usercp'] = 'לוח בקרה אישי';
$l['group_online'] = 'מי מחובר';
$l['group_forumbit'] = 'איזור הפורום';
$l['group_editpost'] = 'עריכת הודעה';
$l['group_forumjump'] = 'קפיצה לפורום';
$l['group_moderation'] = 'ניהול';
$l['group_nav'] = 'ניווט';
$l['group_search'] = 'חיפוש';
$l['group_showteam'] = 'הצגת חברי הנהלה';
$l['group_reputation'] = 'מוניטין';
$l['group_newthread'] = 'אשכול חדש';
$l['group_newreply'] = 'תגובה חדשה';
$l['group_member'] = 'משתמש';
$l['group_warning'] = 'מערכת אזהרות';
$l['group_global'] = 'גלובאלי';
$l['group_header'] = 'חלק עליון';
$l['group_managegroup'] = 'ניהול קבוצות';
$l['group_misc'] = 'שונים';
$l['group_modcp'] = 'לוח בקרה למנהל';
$l['group_announcement'] = 'הכרזות';
$l['group_polls'] = 'סקר';
$l['group_post'] = 'הודעה';
$l['group_printthread'] = 'הדפסת אשכול';
$l['group_report'] = 'דיווח';
$l['group_smilieinsert'] = 'תיבת סמיילים';
$l['group_stats'] = 'סטטיסיקה';
$l['group_xmlhttp'] = 'XMLHTTP';
$l['group_footer'] = 'חלק תחתון';
$l['group_video'] = 'MyCode וידאו';
$l['group_sendthread'] = 'שליחת אשכול';
$l['expand'] = 'הרחב';
$l['collapse'] = 'צמצם';
$l['save_continue'] = 'שמור והמשך לערוך';
$l['save_close'] = 'שמור וחזור לרשימה';
$l['template_name'] = 'שם התבנית';
$l['template_name_desc'] = 'Name of the template. If you change this on the default template, it will save the template as a custom template under the new name.';
$l['template_set_desc'] = 'Which template set should this template be in?';
$l['template_group_prefix'] = 'קידומת קבוצת תבנית';
$l['template_group_prefix_desc'] = 'The prefix name to group templates. This must not already exist. For example, to group templates <em>hello_world</em>, <em>hello_foobar</em> and <em>hello_foo</em>, enter <strong>hello</strong> here.';
$l['template_group_title'] = 'כותרת קבוצת תבנית';
$l['template_group_title_desc'] = 'The title of the prefix group. This will be shown in the templates list. For example, for our <em>hello</em> templates, enter <strong>Hello</strong> here.';
$l['edit_template_group'] = 'ערוך קבוצת תבנית';
$l['editing_template_group'] = 'ערוך קבוצת תבנית {1}';
$l['delete_template_group'] = 'מחק קבוצת תבנית';
$l['save_template_group'] = 'שמור קבוצת תבנית';
$l['templates_the_same'] = 'לא ניתן להשוות בין התבניות שבחרת מכיוון שהן זהות';
$l['master_updated_ins'] = 'Changes that have been made between your previous version and this one are highlighted like this.';
$l['master_updated_del'] = 'Any customizations you\'ve made to your templates (the old ones) are highlighted like this.';
$l['template_diff_analysis'] = 'תחקור הבדל התבניות';
$l['search_names_header'] = 'Searching template names containing "{1}"';
$l['updated_template_welcome1'] = 'ערוך - מאפשר לך לערוך את התבנית הנוכחית כדי שערכה זו תעודכן בין הגרסאות.';
$l['updated_template_welcome2'] = 'שחזר - מאפשר לשחזר את התבנית המותאמת אישית חזרה לראשית, אומנם אתה תאבד כל שינוי מותאם אישית שעשית.';
$l['updated_template_welcome3'] = 'מצא הבדל - מבצע תחקור בין התבנית שאתה עשית לבין העותק האחרון.';
$l['no_global_templates'] = 'אין כרגע תבניות גלובליות';
$l['no_updated_templates'] = 'There are currently no templates which have been updated since you last upgraded.';
$l['confirm_template_set_deletion'] = 'אתה בטוח שאתה רוצה למחוק ערכת תבנית זו?';
$l['confirm_template_group_delete'] = 'Are you sure you want to delete this template group? This action does not remove the templates in the group.';
$l['confirm_template_deletion'] = 'Are you sure you want to delete this template?';
$l['confirm_template_revertion'] = 'Are you sure you want to revert this template?';
$l['error_security_problem'] = 'A potential security issue was found in the template. Please review your changes or contact the MyBB Group for support.';
$l['error_missing_input'] = 'Please make sure you have all the input required to edit this template (tid and sid)';
$l['error_already_exists'] = 'The template title is already in use. Please use a different title.';
$l['error_invalid_template'] = 'Please select a valid template.';
$l['error_missing_set_title'] = 'Please select a template set title.';
$l['error_invalid_input'] = 'Please make sure you have the correct template set ID.';
$l['error_invalid_set'] = 'Please select a valid template set.';
$l['error_invalid_template_set'] = 'Invalid template set selected.';
$l['error_themes_attached_template_set'] = 'This template set cannot be deleted as there are themes attached to this template set.';
$l['error_missing_group_prefix'] = 'Please enter a prefix for the template group.';
$l['error_missing_group_title'] = 'Please enter a title for the template group.';
$l['error_duplicate_group_prefix'] = 'A template group already exists with this prefix. Please enter another prefix.';
$l['error_missing_template_group'] = 'The template group could not be found.';
$l['error_default_template_group'] = 'You cannot edit or remove a default template group.';
$l['success_template_saved'] = 'The selected template has successfully been saved.';
$l['success_template_deleted'] = 'The selected template has successfully been deleted.';
$l['success_template_reverted'] = 'The selected template has successfully been reverted.';
$l['success_template_set_saved'] = 'The selected template set has successfully been saved.';
$l['success_template_set_deleted'] = 'The selected template set has successfully been deleted.';
$l['success_template_group_saved'] = 'The selected template group has successfully been saved.';
$l['success_template_group_deleted'] = 'The selected template group has successfully been deleted.';
