<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Tue, 28 Apr 2015 15:55:23 +0000
// --------------------------------------------------------------------------------

$l['php_info'] = 'מידע PHP';
$l['browser_no_iframe_support'] = 'הדפדפן שלך אינו תומך בiFrames.';
