<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Fri, 01 May 2015 13:40:54 +0000
// --------------------------------------------------------------------------------

$l['user_email_log'] = 'רישומי EMAIL משתמש';
$l['user_email_log_desc'] = 'כל המיילים שנשלחים ממשתמש אחד לאחר כמו גם המיילים שנשלחים דרך "שלח נושא לחבר" נרשמים למטה. אתה יכול לזהות משתמשים שפונטנציאלית מנצלים לרעה תכונה זו.';
$l['prune_user_email_log'] = 'השמט רישומי אימייל משתמש';
$l['close_window'] = 'סגור חלון';
$l['user_email_log_viewer'] = 'תצפית רישומי מייל המשתמש';
$l['to'] = 'עד';
$l['from'] = 'מ';
$l['ip_address'] = 'כתובות IP';
$l['subject'] = 'נושא';
$l['date'] = 'תאריך';
$l['email'] = 'אימייל';
$l['date_sent'] = 'תאריך שליחה';
$l['deleted'] = 'נמחק';
$l['sent_using_send_thread_feature'] = 'נשלח דרך "שלח נושא לחבר"';
$l['thread'] = 'נושא:';
$l['find_emails_by_user'] = 'מצא את כל המיילים שנשלחו ע"י המשתמש הזה';
$l['find'] = 'מצא';
$l['deleted_user'] = 'משתמש מחוק';
$l['email_sent_to_user'] = 'אימייל נשלח למשתמש';
$l['email_sent_using_contact_form'] = 'אימייל נשלח דרך טופס "צור קשר"';
$l['no_logs'] = 'אין רישומים עבור הקריטריונים שהוזנו';
$l['filter_user_email_log'] = 'סנן רישומי מייל משתמש';
$l['username_is'] = 'שם המשתמש הינו';
$l['email_contains'] = 'כתובת אימייל מכילה';
$l['subject_contains'] = 'נושא מכיל';
$l['find_emails_to_user'] = 'מצא את כל האימיילים שנשלחו למשתמש';
$l['error_invalid_user'] = 'שם המשתמש שהזנת אינו קיים במערכת';
