<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Tue, 28 Apr 2015 16:37:25 +0000
// --------------------------------------------------------------------------------

$l['statistics'] = 'סטטיסטיקות';
$l['overall_statistics'] = 'סטטיסטיקות כוללות';
$l['overall_statistics_desc'] = 'כאן תוכל לצפות בסטטיסטיקות כלליות בפורום שלך. כל הזמנים הם בUTC.';
$l['date_range'] = 'טווח תאריך';
$l['date'] = 'תאריך';
$l['users'] = 'משתמשים';
$l['threads'] = 'נושאים';
$l['posts'] = 'פוסטים';
$l['from'] = 'מ';
$l['to'] = 'עד';
$l['increase'] = 'הגדל';
$l['no_change'] = 'ללא שינוי';
$l['decrease'] = 'הקטן';
$l['error_no_results_found_for_criteria'] = 'We could not find any results for the date range you provided. Please try a different date range.';
$l['error_no_statistics_available_yet'] = 'We\'re sorry, there are currently no statistics data available for your forum yet.';
