<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Wed, 29 Apr 2015 11:08:03 +0000
// --------------------------------------------------------------------------------

$l['cache'] = 'מטמון:';
$l['cache_manager'] = 'מנהל מטמון';
$l['cache_manager_description'] = 'כאן תוכל לנהל מטמונים , שהם משמשים כשיטה לייעול MyBB. בנייה מחודשת של מטמון תיקח את כל המידע ההכרחי כדי ליצור את המטמון ולסנכרן אותו מחדש.
טעינה מחודשת של המטמון תטען אותו אל מנהל המטמון הנבחר (אחסון, eAccelerator, memcache, וכו\'). טעינה מחודשת היא שימושית כשמחליפים ממסד אחד או מערכת קבצים לxcache ,  eaccelerator או מנהל מטמון אחר.';
$l['rebuild_cache'] = 'בנה מחדש מטמון';
$l['reload_cache'] = 'טען מחדש מטמון';
$l['rebuild_reload_all'] = '(בנה מחדש טען מחדש הכל)';
$l['error_cannot_rebuild'] = 'מטמון זה לא יכול להיבנות מחדש';
$l['error_empty_cache'] = 'המטמון ריק';
$l['error_incorrect_cache'] = 'מטמון בלתי תקין נבחר';
$l['error_no_cache_specified'] = 'לא ציינת מטמון לתצוגה';
$l['success_cache_rebuilt'] = 'המטמון נבנה מחדש בהצלחה';
$l['success_cache_reloaded'] = 'המטמון נטען מחדש בהצלחה';
