<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Tue, 28 Apr 2015 15:54:57 +0000
// --------------------------------------------------------------------------------

$l['optimize_database'] = 'אופטימיזציית מסד נתונים';
$l['table_selection'] = 'בחירת טבלה';
$l['tables_select_desc'] = 'אתה רשאי לבחור את טבלאות מסד הנתונים שאתה מבקש לבצע עליהם את הפעולה.
החזק את מקש הCTRL כדי לבחור מספר טבלאות.';
$l['select_all'] = 'בחר הכל';
$l['deselect_all'] = 'הסר בחירה מכולם';
$l['select_forum_tables'] = 'בחר טבלאות פורום';
$l['optimize_selected_tables'] = 'אופטימיזציית טבלאות בחורות';
$l['error_no_tables_selected'] = 'You did not select any database tables to optimize.';
$l['success_tables_optimized'] = 'The selected tables have been optimized and analyzed successfully.';
