<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Fri, 01 May 2015 13:45:08 +0000
// --------------------------------------------------------------------------------

$l['warning_logs'] = 'רישומי אזהרות';
$l['warning_logs_desc'] = 'אזור זה מאפשר לך לצפות בהיסטוריית האזהרות שניתנו למשתמשים.';
$l['warned_user'] = 'משתמש מוזהר';
$l['warning'] = 'אזהרה';
$l['date_issued'] = 'תאריך האזהרה';
$l['expires'] = 'יפוג ב';
$l['expiry_date'] = 'תאריך תפוגה';
$l['issued_date'] = 'תאריך הפעולה';
$l['issued_by'] = 'הוזהר ע"י';
$l['details'] = 'פרטים';
$l['filter_warning_logs'] = 'סנן רישומי אזהרות';
$l['filter_warned_user'] = 'משתמש מוזהר:';
$l['filter_issued_by'] = 'ניתנה ע"י:';
$l['filter_reason'] = 'סיבה מכילה:';
$l['sort_by'] = 'סדר ע"פ:';
$l['results_per_page'] = 'תוצאות לעמוד:';
$l['view'] = 'תצוגה';
$l['no_warning_logs'] = 'אין רישומי אזהרות לצפייה';
$l['revoked'] = 'בטל';
$l['post'] = 'פוסט';
$l['asc'] = 'עלייה';
$l['desc'] = 'ירידה';
$l['in'] = 'ב';
$l['order'] = 'סדר';
$l['warning_details'] = 'פרטי אזהרה';
$l['warning_note'] = 'רישומי מנהל המערכת';
$l['already_expired'] = 'פג תוקף';
$l['warning_revoked'] = 'נשלל';
$l['warning_active'] = 'פעיל';
$l['error_invalid_warning'] = 'An invalid warning was specified.';
$l['revoke_warning'] = 'שלול אזהרה זו';
$l['revoke_warning_desc'] = 'To revoke this warning please enter a reason below. This will not remove any bans or suspensions imposed by this warning.';
$l['reason'] = 'סיבה:';
$l['warning_is_revoked'] = 'האזהרה בוטלה';
$l['revoked_by'] = 'בוטל ע"י:';
$l['date_revoked'] = 'תאריך ביטול:';
$l['error_already_revoked'] = 'This warning has already been revoked.';
$l['error_no_revoke_reason'] = 'You did not enter a reason as to why you want to revoke this warning.';
$l['redirect_warning_revoked'] = 'This warning has been revoked and the users warning points decreased successfully.';
