<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Fri, 01 May 2015 13:32:21 +0000
// --------------------------------------------------------------------------------

$l['file_verification'] = 'בדיקת תקינות קבצים';
$l['checking'] = 'בודק...';
$l['file_verification_message'] = 'תהליך זה יבדוק את כל קבצי MyBB הרגילים עמ"נ לוודא תקינות. לחץ על "כן" עמ"נ להמשיך.<br/>
<small>שים לב, תהליך זה לא יכול להפריד בין שינויים מותאמים אישית לפגימה מכוונת בקבצים. לכן, עליך להיזהר בעת שחזור קבצים שהתהליך מסמן כ"פגומים".</small>';
$l['error_communication'] = 'התרחשה תקלה בתקשורת עם שרת MyBB. אנא נסה שוב בעוד מספר דקות.';
$l['file'] = 'קובץ';
$l['no_corrupt_files_found'] = 'ברכות! לא נמצאו קבצים פגומים בהתקנה שלך!';
$l['found_problems'] = 'בעיות שנמצאו';
$l['no_problems_found'] = 'לא נמצאו בעיות';
$l['changed'] = 'שונה';
$l['missing'] = 'חסר';
$l['status'] = 'מצב';
