<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Sun, 26 Apr 2015 11:46:34 +0000
// --------------------------------------------------------------------------------

$l['tools_and_maintenance'] = 'כלים ותחזוקה';
$l['maintenance'] = 'תחזוקה';
$l['logs'] = 'רישומים';
$l['system_health'] = 'בריאות מערכת';
$l['cache_manager'] = 'מנהל מטמון';
$l['task_manager'] = 'מנהל משימות';
$l['recount_and_rebuild'] = 'ספירה ובנייה מחדש';
$l['view_php_info'] = 'צפה במידה PHP';
$l['database_backups'] = 'גיבויי מסד הנתונים';
$l['optimize_database'] = 'אופטימיזציית מסד';
$l['file_verification'] = 'תקינות קבצים';
$l['administrator_log'] = 'רישומי אדמין';
$l['moderator_log'] = 'רישומי מנהל';
$l['user_email_log'] = 'רישומי דוא"ל של משתמשים';
$l['system_mail_log'] = 'רישומי דוא"ל מערכת';
$l['user_warning_log'] = 'רישומי אזהרות משתמשים';
$l['spam_log'] = 'רישומי ספאם';
$l['statistics'] = 'סטטיסטיקות';
$l['can_access_system_health'] = 'Can access system health?';
$l['can_manage_cache'] = 'Can manage cache?';
$l['can_manage_tasks'] = 'Can manage scheduled tasks?';
$l['can_manage_db_backup'] = 'Can manage backup database?';
$l['can_optimize_db'] = 'Can optimize database?';
$l['can_recount_and_rebuild'] = 'Can recount and rebuild?';
$l['can_manage_admin_logs'] = 'Can manage administrator log?';
$l['can_manage_mod_logs'] = 'Can manage moderator log?';
$l['can_manage_user_mail_log'] = 'Can manage user mail Log?';
$l['can_manage_system_mail_log'] = 'Can manage system mail log?';
$l['can_manage_user_warning_log'] = 'Can manage user warning logs?';
$l['can_manage_spam_log'] = 'Can manage spam logs?';
$l['can_view_php_info'] = 'יכול לראות מידע על PHP?';
$l['can_manage_file_verification'] = 'Can manage file verification?';
$l['can_view_statistics'] = 'יכול לצפות בסטטיסטיקות?';
