<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Fri, 01 May 2015 13:50:51 +0000
// --------------------------------------------------------------------------------

$l['spam_logs'] = 'רישומי ספאם';
$l['spam_logs_desc'] = 'אזור זה מאפשר לך לצפות בהיסטוריה או משתמשים שנחסמו על ידי מסנני הספאם.';
$l['prune_spam_logs'] = 'השמט רישומי ספאם';
$l['prune_spam_logs_desc'] = 'Here you can prune the spam logs matching a specified criteria.';
$l['spam_username'] = 'שם משתמש';
$l['spam_email'] = 'כתובת EMAIL';
$l['spam_ip'] = 'כתובת IP';
$l['spam_date'] = 'תאריך';
$l['spam_confidence'] = 'בטחון';
$l['no_spam_logs'] = 'אף משתמש לא נחסם עדיין על ידי מסנני הספאם עדיין';
$l['success_pruned_spam_logs'] = 'רישומי הספאם הושמטו בהצלחה';
$l['note_logs_locked'] = 'לצרכי אבטחה, רישומים של לפני פחות מ24 שעות לא יכולים להמחק.';
$l['all_usernames'] = 'כל שמות המשתמשים';
$l['all_emails'] = 'כל כתובות הEMAIL';
$l['date_range'] = 'טווח תאריך:';
$l['days'] = 'ימים';
$l['filter_spam_logs'] = 'סנן רישומי ספאם';
$l['asc'] = 'עולה';
$l['desc'] = 'יורד';
$l['in'] = 'ב';
$l['order'] = 'סדר';
$l['sort_by'] = 'סדר ע"פ';
$l['results_per_page'] = 'תוצאות לעמוד';
