<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Fri, 01 May 2015 13:22:34 +0000
// --------------------------------------------------------------------------------

$l['database_backups'] = 'גיבויי מסד נתונים';
$l['database_backups_desc'] = 'כאן תוכל למצוא רשימה של כל גיבויי המסד שכרגע נמצאים על השרת שלך בתיקיית הגיבויים של MyBB.';
$l['new_database_backup'] = 'גיבוי מסד חדש';
$l['new_backup'] = 'גיבוי חדש';
$l['new_backup_desc'] = 'כאן תוכל לגבות עותק של מסד הנתונים שלך';
$l['backups'] = 'גיבויים';
$l['existing_database_backups'] = 'גיבויי מסד קיימים';
$l['backup_saved_to'] = 'הגיבוי נשמר ל:';
$l['download'] = 'הורדה';
$l['table_selection'] = 'בחירת טבלה';
$l['backup_options'] = 'אפשרויות גיבוי';
$l['table_select_desc'] = 'You may select the database tables you wish to perform this action on here. Hold down CTRL to select multiple tables.';
$l['select_all'] = 'בחר הכל';
$l['deselect_all'] = 'בטל את כל הבחירות';
$l['select_forum_tables'] = 'בחר טבלאות פורום';
$l['file_type'] = 'סוג קובץ';
$l['file_type_desc'] = 'בחר את סוג הקובץ בו תרצה לשמור את הגיבוי';
$l['gzip_compressed'] = 'מכווץ GZIP';
$l['plain_text'] = 'טקסט פשוט';
$l['save_method'] = 'שיטת שמירה';
$l['save_method_desc'] = 'בחר את שיטת הגיבוי בה המסד יגובה.';
$l['backup_directory'] = 'תיקיית גיבוי';
$l['backup_contents'] = 'תוכן גיבוי';
$l['backup_contents_desc'] = 'בחר את המידע שהיית רוצה לכלול בגיבוי.';
$l['structure_and_data'] = 'מבנה ומידע';
$l['structure_only'] = 'מבנה בלבד';
$l['data_only'] = 'מידע בלבד';
$l['analyze_and_optimize'] = 'תחקר וייעל טבלאות נבחרות';
$l['analyze_and_optimize_desc'] = 'תרצה שהטבלאות הנבחרות יתוחקרו וייעולו במהלך הגיבוי?';
$l['perform_backup'] = 'בצע גיבוי';
$l['backup_filename'] = 'שם קובץ הגיבוי';
$l['file_size'] = 'גודל הקובץ';
$l['creation_date'] = 'תאריך יצירה
';
$l['no_backups'] = 'לא נוצרו גיבויים עדיין.';
$l['error_file_not_specified'] = 'You did not specify a database backup to download.';
$l['error_invalid_backup'] = 'The back up file you selected is either invalid or does not exist.';
$l['error_backup_doesnt_exist'] = 'The specified backup does not exist';
$l['error_backup_not_deleted'] = 'The backup has not been deleted.';
$l['error_tables_not_selected'] = 'You did not select any tables to backup.';
$l['error_no_zlib'] = 'The zlib library for PHP is not enabled - you cannot create GZIP compressed backups.';
$l['alert_not_writable'] = 'Your backups directory (within the Admin CP directory) is not writable. You cannot save backups on the server.';
$l['confirm_backup_deletion'] = 'האם אתה בטוח שברצונך למחוק גיבוי זה?';
$l['success_backup_deleted'] = 'הגיבוי נמחק בהצלחה';
$l['success_backup_created'] = 'הגיבוי נוצר בהצלחה';
