<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Fri, 01 May 2015 13:28:31 +0000
// --------------------------------------------------------------------------------

$l['task_manager'] = 'מנהל משימות';
$l['add_new_task'] = 'הוסף משימה חדשה';
$l['add_new_task_desc'] = 'כאן תוכל ליצור משימות מתוזמנות אוטומטיות חדשות שירוצו בלוח שלך';
$l['edit_task'] = 'ערוך משימה';
$l['edit_task_desc'] = 'למטה תוכל לערוך הגדרות שונות עבור משימה מתוזמנת זו';
$l['task_logs'] = 'רישומי משימה';
$l['view_task_logs'] = 'צפה ברישומי משימה';
$l['view_task_logs_desc'] = 'כשמשימה רצה ורישומים מופעלים, כל תוצר או שגיאה שלה יירשמו למטה.
רישומים מלפני יותר מ30 יום נמחקים אוטומטית.';
$l['scheduled_tasks'] = 'משימות מתוזמנות';
$l['scheduled_tasks_desc'] = 'כאן תוכל לנהל משימות שרצות אוטומטית על הלוח שלך. כדי להריץ מטלה לחץ על הסמלון מימין למשימה שלך.';
$l['title'] = 'כותרת';
$l['short_description'] = 'תיאור קצר';
$l['task_file'] = 'קובץ משימה';
$l['task_file_desc'] = 'בחר את המשימה שברצונך להריץ';
$l['time_minutes'] = 'זמן: דקות';
$l['time_minutes_desc'] = 'Enter a comma separated list of minutes (0-59) for which this task should run on. Enter \'*\' if this task should run on every minute.';
$l['time_hours'] = 'זמן: שעות';
$l['time_hours_desc'] = 'Enter a comma separated list of hours (0-23) for which this task should run on. Enter \'*\' if this task should run on every hour.';
$l['time_days_of_month'] = 'זמן: ימי החודש';
$l['time_days_of_month_desc'] = 'Enter a comma separated list of days (1-31) for which this task should run on. Enter \'*\' if this task should run on every day or you wish to specify a weekday below.';
$l['every_weekday'] = 'כל שבוע';
$l['sunday'] = 'ראשון';
$l['monday'] = 'שני';
$l['tuesday'] = 'שלישי';
$l['wednesday'] = 'רביעי';
$l['thursday'] = 'חמישי';
$l['friday'] = 'שישי';
$l['saturday'] = 'שבת';
$l['time_weekdays'] = 'זמן: סופי שבוע';
$l['time_weekdays_desc'] = 'Select which weekdays this task should run on. Holding down CTRL selects multiple weekdays. Select \'Every weekday\' if you want this task to run each weekday or you have entered a predefined day above.';
$l['every_month'] = 'כל חודש';
$l['time_months'] = 'זמן: חודשים';
$l['time_months_desc'] = 'Select which months this task should run on. Holding down CTRL selects multiple months. Select \'Every month\' if you want this task to run each month.';
$l['enabled'] = 'מטלה פעילה?';
$l['enable_logging'] = 'לאפשר רישומים?';
$l['save_task'] = 'שמור מטלה';
$l['task'] = 'מטלה';
$l['date'] = 'תאריך';
$l['data'] = 'מידע';
$l['no_task_logs'] = 'There are currently no log entries for any of the scheduled tasks.';
$l['next_run'] = 'ריצה הבאה';
$l['run_task_now'] = 'הרץ מטלה זו כעת';
$l['disable_task'] = 'בטל מטלה';
$l['run_task'] = 'הרץ מטלה';
$l['enable_task'] = 'אפשר מטלה';
$l['delete_task'] = 'מחק מטלה';
$l['error_invalid_task'] = 'המטלה שצויינה אינה קיימת';
$l['error_missing_title'] = 'You did not enter a title for this scheduled task';
$l['error_missing_description'] = 'You did not enter a description for this scheduled task';
$l['error_invalid_task_file'] = 'The task file you selected does not exist.';
$l['error_invalid_minute'] = 'The minute you\'ve entered is invalid.';
$l['error_invalid_hour'] = 'The hour you\'ve entered is invalid.';
$l['error_invalid_day'] = 'The day you\'ve entered is invalid.';
$l['error_invalid_weekday'] = 'The weekday you\'ve selected is invalid.';
$l['error_invalid_month'] = 'The month you\'ve selected is invalid.';
$l['success_task_created'] = 'The task has been created successfully.';
$l['success_task_updated'] = 'The selected task has been updated successfully.';
$l['success_task_deleted'] = 'The selected task has been deleted successfully.';
$l['success_task_enabled'] = 'The selected task has been enabled successfully.';
$l['success_task_disabled'] = 'The selected task has been disabled successfully.';
$l['success_task_run'] = 'The selected task has been run successfully.';
$l['confirm_task_deletion'] = 'Are you sure you wish to delete this scheduled task?';
$l['confirm_task_enable'] = '<strong>אזהרה:</strong> אתה עומד להריץ מטלה שאמורה לרוץ רק ע"י cron (אנא בדוק את
<a href="http://docs.mybb.com/Help-Task_System.html" target="_blank">MyBB דוקומנטציית</a> לעוד מידע).
 להמשיך?';
$l['no_tasks'] = 'לא רצות מטלות כרגע בפורום שלך.';
