<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Fri, 01 May 2015 13:44:18 +0000
// --------------------------------------------------------------------------------

$l['system_email_log'] = 'רישומי דוא"ל של המערכת';
$l['system_email_log_desc'] = 'כל המיילים שנשלחו ע"י MyBB וחזרו עם שגיאה נשלחים לכןא ונרשמים על ידי MyBB למטה.
אזור זה הוא שימושי במיוחד עמ"נ לזהות הגדרות SMTP בעייתיות או לזהות את תמיכת המיילים של השרת שלך.';
$l['prune_system_email_log'] = 'השמט רישומי דו"אל של המערכת';
$l['filter_system_email_log'] = 'סנן רישומי דו"אל של המערכת';
$l['close_window'] = 'סוג חלון';
$l['user_email_log_viewer'] = 'תצפית ברישומי דוא"ל המשתמש';
$l['smtp_code'] = 'קוד SMTP:';
$l['smtp_server_response'] = 'תשובת שרת הSMTP:';
$l['to'] = 'אל';
$l['from'] = 'מ';
$l['subject'] = 'נושא';
$l['date'] = 'תאריך';
$l['email'] = 'אימייל';
$l['date_sent'] = 'מידע שנשלח';
$l['error_message'] = 'הודעת שגיאה';
$l['fine'] = 'מצא';
$l['no_logs'] = 'לא נמצאו פריטים המתאימים לקריטריונים שהוזנו';
$l['subject_contains'] = 'נושא מכיל';
$l['error_message_contains'] = 'הודעת שגיאה מכילה';
$l['to_address_contains'] = 'כתובת נמען מכילה';
$l['from_address_contains'] = 'כתובת מוען מכילה';
$l['find_emails_to_addr'] = 'מצא את כל המיילים שנשלחו לכתובת זו';
