<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Fri, 01 May 2015 13:38:15 +0000
// --------------------------------------------------------------------------------

$l['mod_logs'] = 'רישומי משגיח';
$l['mod_logs_desc'] = 'כאן תוכל לצפות, להשמיט ולחפש את רישומי המשגיחים. רישומים אלה מכילים את הפעולות של משתמש רגיל (אם מחיקה של פוסטים/נושאים של עצמך מאופשר) ופעולות ניהול.';
$l['prune_mod_logs'] = 'השמט רישומי משגיח';
$l['prune_mod_logs_desc'] = 'כאן תוכל להשמיט רישומי משגיח שמתאימים לקריטריונים מסוייימים';
$l['no_modlogs'] = 'אין רישומים המתאימים לקריטיריונים אלו';
$l['username'] = 'שם משתמש';
$l['date'] = 'תאריך';
$l['action'] = 'פעולה';
$l['information'] = 'מידע';
$l['ipaddress'] = 'כתובת IP';
$l['forum'] = 'פורום:';
$l['thread'] = 'נושא:';
$l['post'] = 'פוסט:';
$l['user_info'] = 'משתמש:';
$l['announcement'] = 'הכרזה:';
$l['filter_moderator_logs'] = 'סנן רישומי משגיח';
$l['forum_moderator'] = 'מנהל פורום:';
$l['sort_by'] = 'סדר ע"פ:';
$l['results_per_page'] = 'תוצאות לדף"';
$l['all_moderators'] = 'כל המנהלים';
$l['older_than'] = 'ישן יותר מ';
$l['forum_name'] = 'שם הפורום';
$l['thread_subject'] = 'נושא האשכול';
$l['asc'] = 'עולה';
$l['desc'] = 'יורד';
$l['in'] = 'ב';
$l['order'] = 'סדר';
$l['days'] = 'ימים';
$l['prune_moderator_logs'] = 'השמט רישומי משגיח';
$l['date_range'] = 'טווח תאריך:';
$l['success_pruned_mod_logs'] = 'רישומי המשגיח הושמטו בהצלחה';
$l['note_logs_locked'] = 'For security reasons, logs less than 24 hours old cannot be pruned.';
