<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Fri, 01 May 2015 13:23:49 +0000
// --------------------------------------------------------------------------------

$l['recount_rebuild'] = 'ספירה מחדש &amp; בנייה מחדש';
$l['recount_rebuild_desc'] = 'כאן תוכל לספור מחדש ולבנות מחדש מידע עמ"נ לתקן בעיות ושגיאות סנכרון בפורום שלך.';
$l['data_per_page'] = 'פריטים בעמוד';
$l['recount_stats'] = 'אסוף מחדש סטטיסטיקות';
$l['recount_stats_desc'] = 'This will recount and update your forum statistics on the forum index and statistics pages.';
$l['recount_reputation'] = 'ספור מחדש מוניטין';
$l['recount_reputation_desc'] = 'This will recount the reputation of each user.';
$l['recount_warning'] = 'ספור מחדש אזהרות';
$l['recount_warning_desc'] = 'This will recount the active warning points of each user.';
$l['recount_private_messages'] = 'ספור מחדש הודעות פרטיות';
$l['recount_private_messages_desc'] = 'This will recount the private message count for each user.';
$l['recount_referrals'] = 'ספור מחדש הפניות';
$l['recount_referrals_desc'] = 'This will recount the referral count of each user.';
$l['recount_thread_ratings'] = 'ספור מחדש דירוגי אשכולות';
$l['recount_thread_ratings_desc'] = 'This will recount the rating of each thread.';
$l['rebuild_forum_counters'] = 'בנה מחדש מוני פורום';
$l['rebuild_forum_counters_desc'] = 'When this is run, the post/thread counters and last post of each forum will be updated to reflect the correct values.';
$l['rebuild_thread_counters'] = 'בנה מחדש מוני נושאים';
$l['rebuild_thread_counters_desc'] = 'When this is run, the post/view counters and last post of each thread will be updated to reflect the correct values.';
$l['rebuild_poll_counters'] = 'בנה מחדש מוני סקרים';
$l['rebuild_poll_counters_desc'] = 'When this is run, the vote counters and total number of votes of each poll will be updated to reflect the correct values.';
$l['recount_user_posts'] = 'ספור מחדש מונה פוסטים של משתמשים';
$l['recount_user_posts_desc'] = 'When this is run, the post count for each user will be updated to reflect its current live value based on the posts in the database, and forums that have post count disabled.';
$l['recount_user_threads'] = 'ספור מחדש מונה נושאים של משתמשים';
$l['recount_user_threads_desc'] = 'When this is run, the thread count for each user will be updated to reflect its current live value based on the threads in the database, and forums that have thread count disabled.';
$l['rebuild_attachment_thumbs'] = 'Rebuild Attachment Thumbnails';
$l['rebuild_attachment_thumbs_desc'] = 'This will rebuild attachment thumbnails to ensure they\'re using the current width and height dimensions and will also rebuild missing thumbnails.';
$l['success_rebuilt_forum_counters'] = 'The forum counters have been rebuilt successfully.';
$l['success_rebuilt_thread_counters'] = 'The thread counters have been rebuilt successfully.';
$l['success_rebuilt_poll_counters'] = 'The poll counters have been rebuilt successfully.';
$l['success_rebuilt_user_post_counters'] = 'The user posts count have been recounted successfully.';
$l['success_rebuilt_user_thread_counters'] = 'The user threads count have been recounted successfully.';
$l['success_rebuilt_attachment_thumbnails'] = 'The attachment thumbnails have been rebuilt successfully.';
$l['success_rebuilt_forum_stats'] = 'The forum statistics have been rebuilt successfully.';
$l['success_rebuilt_reputation'] = 'The user reputation has been rebuilt successfully.';
$l['success_rebuilt_warning'] = 'The user warning points have been rebuilt successfully.';
$l['success_rebuilt_private_messages'] = 'The user private message count has been recounted successfully.';
$l['success_rebuilt_referral'] = 'The user referral count have been recounted successfully.';
$l['success_rebuilt_thread_ratings'] = 'The thread ratings have been recounted successfully.';
$l['confirm_proceed_rebuild'] = 'Click "Proceed" to continue the recount and rebuild process.';
$l['automatically_redirecting'] = 'מפנה מחדש אוטומטית...';
