<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Fri, 01 May 2015 13:20:50 +0000
// --------------------------------------------------------------------------------

$l['system_health'] = 'בריאות המערכת';
$l['system_health_desc'] = 'כאן תוכל למצוא מידע אודות בריאות המערכת שלך';
$l['utf8_conversion'] = 'המרת UTF-8';
$l['utf8_conversion_desc'] = 'אתה כרגע ממיר את מסדי הנתונים לפורמט UTF-8. אנא שים לב שהתהליך עשוי לקחת מספר שעות תלוי בגודל הפורום שלך והטבלאות שלו. כשהתהליך יסתיים אתה תוחזר לדף המרת הUTF-8.';
$l['utf8_conversion_desc2'] = 'כלי זה בודק אם מסדי הנתונים בפורמט UTF-8 ומאפשרים להמיר אותם אם הם לא.';
$l['convert_all'] = 'המר הכל';
$l['converting_to_utf8'] = 'MyBB is currently converting "{1}" table to UTF-8 language encoding from {2} encoding.';
$l['convert_to_utf8'] = 'You are about to convert the "{1}" table to UTF-8 language encoding from {2} encoding.';
$l['convert_all_to_utf'] = 'You are about to convert ALL tables to UTF-8 language encoding from {1} encoding.';
$l['convert_all_to_utf8mb4'] = 'You are about to convert ALL tables to 4-Byte UTF-8 Unicode language encoding from {1} encoding.';
$l['converting_to_utf8mb4'] = 'MyBB is currently converting "{1}" table to 4-Byte UTF-8 Unicode language encoding from {2} encoding.';
$l['please_wait'] = 'אנא המתן...';
$l['converting_table'] = 'טבלת המרה:';
$l['convert_table'] = 'המר טבלה';
$l['convert_tables'] = 'המר את כל הטבלאות';
$l['convert_database_table'] = 'המר טבלת מסד נתונים';
$l['convert_database_tables'] = 'המר כל טבלאות מסד הנתונים';
$l['table'] = 'טבלה';
$l['status_utf8'] = 'מצב הUTF-8';
$l['status_utf8mb4'] = '4-Byte UTF-8 Support<br />(requires MySQL 5.5.3 or above)';
$l['not_available'] = 'לא זמין';
$l['all_tables'] = 'כל הטבלאות';
$l['convert_now'] = 'המר כעת';
$l['totals'] = 'סה"כ';
$l['attachments'] = 'קבצים מצורפים';
$l['total_database_size'] = 'סה"כ גודל מסד נתונים';
$l['attachment_space_used'] = 'גודל אחסון שנוצל ע"י קבצים מצורפים';
$l['total_cache_size'] = 'סה"כ גודל Cache';
$l['estimated_attachment_bandwidth_usage'] = 'גודל תעבורה משוער של קבצים מצורפים ';
$l['max_upload_post_size'] = 'גודל העלאה/פרסום מקסימליים';
$l['average_attachment_size'] = 'גודל קבצים מצורפים ממוצע';
$l['stats'] = 'נתונים';
$l['task'] = 'מטלה';
$l['run_time'] = 'זמן ריצה';
$l['next_3_tasks'] = '3 המטלות הבאות';
$l['no_tasks'] = 'אין מטלות הרצות כרגע';
$l['backup_time'] = 'זמן גיבוי';
$l['no_backups'] = 'לא נוצרו גיבויים עדיין';
$l['existing_db_backups'] = 'גיבוי מסד קיימים';
$l['writable'] = 'ניתן לכתיבה';
$l['not_writable'] = 'לא ניתן לכתיבה';
$l['please_chmod_777'] = 'אנא שנה CHMOD ל777';
$l['chmod_info'] = 'Please change the CHMOD settings to the ones specified with the file below. For more information on CHMODing, see the';
$l['file'] = 'קובץ';
$l['location'] = 'מיקום';
$l['settings_file'] = 'קובץ הגדרות (SETTINGS)';
$l['config_file'] = 'קובץ תצורה (CONFIG)';
$l['file_upload_dir'] = 'תיקיית העלאות קבצים';
$l['avatar_upload_dir'] = 'תיקיית העלאות אווטרים';
$l['language_files'] = 'קבצי שפה';
$l['backup_dir'] = 'תיקיית גיבוי';
$l['cache_dir'] = 'תיקיית Cache';
$l['themes_dir'] = 'תיקיית ערכות נושא';
$l['chmod_files_and_dirs'] = 'קבצי ותקיות CHMOD';
$l['notice_process_long_time'] = 'This process may take up to several hours depending on the size of your forum and this table. <strong>It is highly recommend to create a database backup as this process can\'t be undone.</strong>';
$l['notice_mb4_warning'] = '4-Byte UTF-8 Support requires MySQL 5.5.3 or above. You will not be able to import your database on a MySQL server with another version.';
$l['check_templates'] = 'בדוק תבניות';
$l['check_templates_desc'] = 'בודק אם כל התבניות המותקנות ידועות בבעיות אבטחה.';
$l['check_templates_title'] = 'בדוק אבטחת תבניות';
$l['check_templates_info'] = 'תהליך זה יבדוק את התבניות שלך כנגד בעיות אבטחה שיכולות להשפיע על הפורום שלך והשרת המריץ אותו.
זה עשוי לקחת זמן מה אם התקנת הרבה ערכות נושא<br/>
כדי להתחיל את התהליך לחץ על כפתור "המשך" שלמטה.';
$l['check_templates_info_desc'] = 'אנא בדוק את התבניות הבאות. תבניות אלו נמצאו כבעלי בעיות אבטחה.';
$l['full_edit'] = 'עריכה מלאה';
$l['error_chmod'] = 'of the required files and directories do not have proper CHMOD settings.';
$l['error_invalid_table'] = 'The specified table does not exist.';
$l['error_db_encoding_not_set'] = 'Your current setup of MyBB is not setup to use this tool yet. Please see the <a href="http://docs.mybb.com/Utf8_setup.html">MyBB Docs</a> for more information on how to set it up.';
$l['error_not_supported'] = 'Your current Database Engine is not supported by the UTF-8 Conversion Tool.';
$l['error_invalid_input'] = 'There was a problem checking the templates. Please try again or contact the MyBB Group for support.';
$l['error_master_templates_altered'] = 'The Master Templates have been altered. Please contact the MyBB Group for support on how to alter these.';
$l['error_utf8mb4_version'] = 'Your MySQL version doesn\'t support 4-Byte UTF-8 encoding.';
$l['warning_multiple_encodings'] = 'It is recommend not to use different encodings in your database. This may cause unexpected behavior or MySQL errors.';
$l['warning_utf8mb4_config'] = 'For full 4-Byte UTF-8 support you need to change <i>$config[\'database\'][\'encoding\'] = \'utf8\';</i> to <i>$config[\'database\'][\'encoding\'] = \'utf8mb4\';</i> in your inc/config.php.';
$l['success_templates_checked'] = 'לא נמצאו בעיות אבטחה בתניות!';
$l['success_all_tables_already_converted'] = 'כל הטבלאות הומרו או שכבר היו בפורמט UTF-8.';
$l['success_table_converted'] = 'The selected table "{1}" has been converted to UTF-8 successfully.';
$l['success_chmod'] = 'כל הקבצים הנחוצים והתיקיות בעלי הגדרות CHMOD (גישה) מתאימות.';
