<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Fri, 01 May 2015 11:29:53 +0000
// --------------------------------------------------------------------------------

$l['banning'] = 'הרחקה';
$l['banned_accounts'] = 'משתמשים מורחקים';
$l['banned_accounts_desc'] = 'כאן תוכל לנהל חשבונות משתמשים מושעים.';
$l['ban_a_user'] = 'הרחק משתמש';
$l['ban_a_user_desc'] = 'כאן תוכל להרחיק משתמש';
$l['edit_ban'] = 'ערוך הרחקה';
$l['edit_ban_desc'] = 'כאן תוכל לערוך את סיבת ההרחקה וארוכה של משתמשים מורחקים.';
$l['banned_ips'] = 'IPים מורחקים';
$l['disallowed_usernames'] = 'שמות משתמש אסורים';
$l['disallowed_email_addresses'] = 'כתובות EMAIL אסורות';
$l['error_invalid_ban'] = 'You have selected an invalid ban to edit.';
$l['error_invalid_username'] = 'The username you have entered is invalid and does not exist.';
$l['error_no_perm_to_ban'] = 'You do not have permission to ban this user.';
$l['error_already_banned'] = 'This user already belongs to a banned group and cannot be added to a new one.';
$l['error_ban_self'] = 'You cannot ban yourself.';
$l['error_no_reason'] = 'You did not enter a reason to ban this user.';
$l['success_ban_lifted'] = 'ההרחקה הוסרה בהצלחה.
';
$l['success_banned'] = 'המשתמש הנבחר הורחק בהצלחה.';
$l['success_ban_updated'] = 'ההרחקה שנבחרה עודכנה בהצלחה.';
$l['success_pruned'] = 'The selected user\'s posts and threads have been pruned successfully.';
$l['confirm_lift_ban'] = 'Are you sure you want to lift this ban?';
$l['confirm_prune'] = 'Are you sure you want to prune all threads and posts created by this user?';
$l['ban_username'] = 'שם משתמש<em>*</em>';
$l['autocomplete_enabled'] = 'השלמה אוטומטית מופעלת בשדה זה';
$l['ban_reason'] = 'Ban Reason';
$l['ban_group'] = 'קבוצה מורחקת <em>*</em>';
$l['ban_group_desc'] = 'In order for this user to be banned they must be moved to a banned group.';
$l['ban_time'] = 'אורך הרחקה <em>*</em>';
$l['user'] = 'משתמש';
$l['moderation'] = 'ניהול';
$l['ban_lifts_on'] = 'ההרחקה מוסרת ב';
$l['time_left'] = 'זמן שנותר';
$l['permenantly'] = 'לצמיתות';
$l['na'] = 'לא זמין';
$l['for'] = 'עבור';
$l['bannedby_x_on_x'] = '<strong>{1}</strong><br /><small>Banned by {2} on {3} {4}</small>';
$l['lift'] = 'הסר';
$l['no_banned_users'] = 'אין לך משתמשים מושעים נכון לעכשיו.';
$l['prune_threads_and_posts'] = 'השמט נושאים &amp; פוסטים';
$l['ban_user'] = 'הרחק משתמש';
$l['update_ban'] = 'עדכן הרחקה';
$l['search_user'] = 'חפש משתמש';
