<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Fri, 01 May 2015 11:28:19 +0000
// --------------------------------------------------------------------------------

$l['admin_permissions'] = 'הרשאות מנהל המערכת';
$l['user_permissions'] = 'הרשאות משתמש';
$l['user_permissions_desc'] = 'כאן תוכל לנהל את הרשאות מנהל המערכת עבור משתמשים ספציפיים. זה מאפשר לך במילים פשוטות לנעול בפני משתמשים מסויימים מסכים שונים של פאנל הניהול של מנהל המערכת.';
$l['group_permissions'] = 'הרשאות קבוצה';
$l['group_permissions_desc'] = 'הרשאות מנהל מערכת יכולות גם להינתן לקבוצות משתמשים שיש להם גישה לפאנל הניהול של מנהל המערכת.
באופן דומה אתה יכול להשתמש בכלי זה לנעול קבוצות מנהלי מערכת שלמות מלגשת לאזורים שונים של פאנל ניהול זה.';
$l['default_permissions'] = 'הרשאות ברירת מחדל';
$l['default_permissions_desc'] = 'The default administrative permissions are those applied to users who do not have custom administrator permissions set for them or are not inheriting group administrator permissions.';
$l['admin_permissions_updated'] = 'הרשאות מנהל המערכת עודכנו בהצלחה';
$l['revoke_permissions'] = 'בטל הרשאות';
$l['edit_permissions'] = 'ערוך הרשאות';
$l['set_permissions'] = 'הגדר הרשאות';
$l['edit_permissions_desc'] = 'Here you can restrict access to entire tabs or individual pages. Be aware that the "Home" tab is accessible to all administrators.';
$l['update_permissions'] = 'עדכן הרשאות';
$l['view_log'] = 'צפה ברישומים';
$l['permissions_type_group'] = 'סוג הרשאות של הקבוצה';
$l['permissions_type_user'] = 'סוג הרשאות של משתמש';
$l['no_group_perms'] = 'There are currently no set group permissions.';
$l['no_user_perms'] = 'There are currently no set user permissions.';
$l['edit_user'] = 'ערוך פרופיל משתמש';
$l['using_individual_perms'] = 'שימוש בהרשאות יחידות';
$l['using_custom_perms'] = 'שימוש בהרשאות מותאמות אישית';
$l['using_group_perms'] = 'שימוש בהרשאות קבוצה';
$l['using_default_perms'] = 'שימוש בהרשאות ברירת מחדל';
$l['last_active'] = 'פעיל לאחרונה';
$l['user'] = 'משתמש';
$l['edit_group'] = 'ערוך קבוצה';
$l['default'] = 'ברירת מחדל';
$l['group'] = 'קבוצה';
$l['error_super_admin'] = 'Sorry, but you cannot perform this action on the specified user as they are a super administrator.<br /><br />To be able to perform this action, you need to add your user ID to the list of super administrators in inc/config.php.';
$l['error_delete_no_uid'] = 'You did not enter a admin user/usergroup permission id';
$l['error_delete_invalid_uid'] = 'You did not enter a valid admin user/usergroup permission id';
$l['success_perms_deleted'] = 'The admin user/usergroup permissions has been revoked successfully.';
$l['confirm_perms_deletion'] = 'Are you sure you wish to revoked this admin user/usergroup permissions?';
$l['confirm_perms_deletion2'] = 'האם אתה בטוח שברצונך לבטל הרשאות משתמש זה?';
