<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Fri, 01 May 2015 11:20:26 +0000
// --------------------------------------------------------------------------------

$l['users_and_groups'] = 'משתמשים וקבוצות';
$l['users'] = 'משתמשים';
$l['groups'] = 'קבוצות';
$l['user_titles'] = 'כותרות משתמשים';
$l['banning'] = 'השעיות';
$l['admin_permissions'] = 'הרשאות אדמינים';
$l['mass_mail'] = 'מייל המוני';
$l['group_promotions'] = 'קידומי קבוצה';
$l['can_manage_users'] = 'Can manage users?';
$l['can_manage_user_groups'] = 'Can manage user groups?';
$l['can_manage_user_titles'] = 'Can manage user titles?';
$l['can_manage_user_bans'] = 'Can manage User Bans?';
$l['can_manage_admin_permissions'] = 'Can manage admin permissions?';
$l['can_send_mass_mail'] = 'Can send mass mail?';
$l['can_manage_group_promotions'] = 'Can manage group promotions?';
