<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Fri, 01 May 2015 12:43:51 +0000
// --------------------------------------------------------------------------------

$l['user_groups'] = 'קבוצות משתמש';
$l['manage_user_groups'] = 'נהל קבוצות משתמש';
$l['manage_user_groups_desc'] = 'כאן תוכל לנהל את קבוצות המשתמשים השונות בלוח שלך. בנוסף, עבור קבוצות צוות האתר תוכל לנהל את סדר התצוגה של עמוד צוות הפורום. אם תשאיר הכל ב"0" הקבוצות יסודרו בסדר אלפביתי. אם תשנה את סדר הקבוצות וודא שאתה שולח את הבקשה לשינוי מתחתית הדף.
';
$l['add_user_group'] = 'הוסף קבוצת משתמש חדש';
$l['add_user_group_desc'] = 'כאן תוכל ליצור קבוצת משתמשים חדשה ואופציונאלית להעתיק את ההרשאות מקבוצת משתמשים אחרת. אחרי שמירת קבוצת המשתמש תועבר לדף עריכה מלאה של קבוצת משתמשים זאת.';
$l['group_join_requests'] = 'בקשות הצטרפות לקבוצה';
$l['group_join_requests_desc'] = 'Below is a list of users who are requesting access to this user group. From here, you can either approve or deny their request.';
$l['manage_group_leaders'] = 'נהל ראשי קבוצה';
$l['manage_group_leaders_desc'] = 'Here you can manage the group leaders for this user group. Depending on the options you enable for the leader, these users can manage the users who are a member of this group and can moderate any join requests if this group is publicly joinable.';
$l['edit_user_group'] = 'ערוך קבוצת משתמש';
$l['edit_user_group_desc'] = 'כאן תוכל לערוך קבוצת משתמשים קיימת.';
$l['edit_group_leader'] = 'ערוך ראש קבוצה';
$l['edit_group_leader_desc'] = 'Here you can change the permissions for this group leader in regards to what actions they\'re allowed to perform.';
$l['group_leaders'] = 'ראשי הקבוצה';
$l['delete_group'] = 'מחק קבוצה';
$l['edit_group'] = 'ערוך קבוצה';
$l['no_groups'] = 'There are currently no user groups on your forum';
$l['join_requests'] = 'נהל בקשות הצטרפות';
$l['update_groups_order'] = 'עדכן סדר קבוצות';
$l['reset'] = 'אתחל (RESET)';
$l['number_of_users'] = '# משתמשים';
$l['order'] = 'סדר';
$l['group'] = 'קבוצה';
$l['custom_user_group'] = 'קבוצת משתמש מותאמת אישית';
$l['default_user_group'] = 'קבוצת משתמש ברירת מחדל';
$l['join_requests_for'] = 'בקשות הצטרפות עבור';
$l['users'] = 'משתמשים';
$l['reason'] = 'סיבה';
$l['date_requested'] = 'תאריך בקשה';
$l['approve'] = 'אשר';
$l['deny'] = 'דחה';
$l['approve_selected_requests'] = 'אשר בקשות מסומנות';
$l['deny_selected_requests'] = 'דחה בקשות מסומנות';
$l['group_leaders_for'] = 'ראשי קבוצות עבור';
$l['can_manage_members'] = 'יכול לנהל חברי קבוצה?';
$l['can_manage_join_requests'] = 'יכול לנהל בקשות הצטרפות?';
$l['can_invite_members'] = 'יכול להזמין חברי קבוצה?';
$l['user'] = 'משתמש';
$l['can_manage_group_members'] = 'יכול לנהל קבוצות משתמשים?';
$l['can_manage_group_members_desc'] = 'If this user should be able to manage the members within a group, set to Yes.';
$l['can_manage_group_join_requests'] = 'יכול לנהל בקשות הצטרפות לקבוצות משתמשים?';
$l['can_manage_group_join_requests_desc'] = 'Should this user be able to approve or deny new membership requests for this group?';
$l['can_invite_group_members'] = 'יכול להזמין חברי קבוצה?';
$l['can_invite_group_members_desc'] = 'Should this user be able to invite new members to join this group?';
$l['add_group_leader'] = 'הוסף משתמש קבוצה ל';
$l['save_group_leader'] = 'שמור ראש קבוצה';
$l['edit_leader'] = 'ערוך ראש קבוצה:';
$l['title'] = 'כותרת';
$l['short_description'] = 'תיאור קצר';
$l['username_style'] = 'סגנון שם משתמש';
$l['username_style_desc'] = 'This option allows you to set a custom username style for users who have this user group as their display group. <strong>Use {username} to represent the user\'s name.</strong>';
$l['user_title'] = 'כותרת משתמש ברירת מחדל';
$l['user_title_desc'] = 'If the user has nothing entered in their custom user title field, the user title entered here will be displayed. If you leave this option blank, users will have their title and stars taken from the User Titles configuration.';
$l['do_not_copy_permissions'] = 'Don\'t copy permissions from another group';
$l['copy_permissions_from'] = 'העתק הרשאות מ...';
$l['copy_permissions_from_desc'] = 'If you wish, you can copy the forum and group permissions from another group. To make use of this, select a group to copy permissions from.';
$l['save_user_group'] = 'שמור קבוצת משתמש';
$l['list_users'] = 'הצג משתמשים';
$l['general'] = 'כללי';
$l['forums_posts'] = 'פורומים ופוסטים';
$l['users_permissions'] = 'משתמשים והרשאות';
$l['misc'] = 'שונות';
$l['mod_cp'] = 'פאנל למנהל';
$l['stars'] = '# כוכבים';
$l['star_image'] = 'תמונת כוכב';
$l['user_stars'] = 'כוכבי משתמש';
$l['user_stars_desc'] = 'If you enter a number of stars and the location of a star image, this star image will be shown for this particular user group. If you want to use different star images for different themes, please use <strong>{theme}</strong> to represent the image directory of each theme. The number of stars only takes effect if Default User Title is not blank.';
$l['group_image'] = 'תמונת קבוצה';
$l['group_image_desc'] = 'Here you can set a group image which will show on each post made by users in this group. Please use <strong>{lang}</strong> to represent the user\'s chosen language if translated group images are available';
$l['general_options'] = 'אפשרויות כלליות';
$l['member_list'] = 'הצג משתמשי קבוצה זו ברשימת החברים';
$l['forum_team'] = 'הצג קבוצה זו בדף "קבוצות האתר"';
$l['is_banned_group'] = 'Yes, this is a banned group<br /><small>If this group is a \'banned\' user group, users will be able to be \'banned\' in to this user group.</small>';
$l['publicly_joinable_options'] = 'אפשרויות הצרטפות פומביות';
$l['user_joinable'] = 'אפשר הצטרפות ועזיבה חופשית של הקבוצה';
$l['moderate_join_requests'] = 'Yes, all new join requests need to be moderated first<br /><small>Users must be able to freely join and leave this group for this to take effect.</small>';
$l['invite_only'] = 'Yes, users must be invited in order to join this group<br /><small>Users must be able to freely join and leave this group for this to take effect.</small>';
$l['can_set_as_display_group'] = 'Yes, users can set this group as their display group<br /><small>If set to yes, users will be able to set this user group as their display group for user titles, stars, name style and group images.</small>';
$l['moderation_administration_options'] = 'אפשרויות ניהול/ניהול מתקדם';
$l['is_super_mod'] = 'כן, משתמשי קבוצה זו הם משגיחים';
$l['can_access_mod_cp'] = 'כן, משתמשי קבוצה זו יכולים לגשת לפאנל המשגיחים';
$l['can_access_admin_cp'] = 'כן, משתמשי קבוצה זו יכולים לגשת לפאנל מנהל המערכת';
$l['viewing_options'] = 'אפשרויות תצוגה';
$l['can_view_board'] = 'יכול לצפות בלוח?';
$l['can_view_threads'] = 'יכול לצפות בנושאים?';
$l['can_search_forums'] = 'יכול לחפש פורומים?<';
$l['can_view_profiles'] = 'יכול לצפות בפורופילי משתמשים?';
$l['can_download_attachments'] = 'יכול להוריד קבצים מצורפים?';
$l['can_view_board_closed'] = 'יכול לצפות בלוח כשהוא סגור?';
$l['posting_rating_options'] = 'אפשרויות פרסום/דירוג?';
$l['can_post_threads'] = 'יכול לפרסם נושאים חדשים?';
$l['can_post_replies'] = 'יכול להשיב בנושאים?';
$l['can_rate_threads'] = 'יכול לדרג נושאים?';
$l['moderation_options'] = 'אפשרויות ניהול?';
$l['mod_new_posts'] = 'ניהול פוסטים חדשים?';
$l['mod_new_threads'] = 'ניהול נושאים חדישם?';
$l['mod_new_attachments'] = 'ניהול קבצים מצורפים חדשים?';
$l['mod_after_edit'] = 'ניהול פוסטים לאחר עריכה?';
$l['poll_options'] = 'אפשרויות סקר';
$l['max_posts_per_day'] = 'מקסימום פוסטים ליום';
$l['max_posts_per_day_desc'] = 'מספר הפוסטים האפשריים ליום. 0 אומר בלתי מוגבל.';
$l['can_post_polls'] = 'יכול לפרסם סקרים?';
$l['can_vote_polls'] = 'יכול להצביע בסקרים?';
$l['can_undo_votes'] = 'יכול לבטל סקרים?';
$l['attachment_options'] = 'אפשרויות קבצים מצורפים';
$l['can_post_attachments'] = 'יכול לפרסם קבצים מצורפים';
$l['attach_quota'] = 'אפשרויות ציטוט';
$l['attach_quota_desc'] = 'Here you can set the attachment quota that each user in this group will receive. If set to 0, there is no limit.';
$l['editing_deleting_options'] = 'אפשרויות עריכה/מחיקה';
$l['can_edit_posts'] = 'יכול לערוך את הפוסטים של עצמו?';
$l['can_delete_posts'] = 'יכול למחוק פוסטים של עצמו?';
$l['can_delete_threads'] = 'רשאי למחוק נושאים של עצמו?';
$l['can_edit_attachments'] = 'יכול לעדכן קבצים מצורפים של עצמו?';
$l['account_management'] = 'ניהול משתמש';
$l['edit_time_limit'] = 'ערוך זמן הגבלה';
$l['edit_time_limit_desc'] = 'The number of minutes until regular users cannot edit their own posts (if they have the permission). Enter 0 (zero) for no limit.';
$l['can_be_reported'] = 'ניתן לדווח עליו?';
$l['can_access_usercp'] = 'יכול לגשת ללוח הבקרה למשתמש?';
$l['can_change_username'] = 'יכול לשנות שם משתמש?';
$l['can_change_website'] = 'יכול לשנות שדה "אתר"?';
$l['can_use_usertitles'] = 'יכול להשתמש בכותרת מותאמת אישית?';
$l['can_upload_avatars'] = 'יכול להעלות אווטרים?';
$l['can_use_signature'] = 'יכול להוסיף חתימה?';
$l['can_use_signature_posts'] = 'יכול להוסיף חתימה אחרי X פוסטים?';
$l['required_posts'] = 'מס\' פוסטים הדרושים לפני הוספה של חתימה:';
$l['required_posts_desc'] = 'Here you can enter the minimum number of posts a user must have before they can add a signature. If set to 0, users can add a signature at any post count.';
$l['uses_no_follow'] = 'Signature links have nofollow enabled?';
$l['reputation_system'] = 'מוניטין מערכת';
$l['can_use_pms'] = 'יכול להשתמש בהודעות פרטיות?';
$l['can_send_pms'] = 'יכול לשלוח הודעות פרטיות?';
$l['can_track_pms'] = 'יכול לעקוב אחר הודעות פרטיות שנשלחו?';
$l['can_deny_reciept'] = 'רשאי לבטל התראות הודעה?';
$l['can_override_pms'] = 'יכול לשלוח הודעה פרטית גם אם  נמענים מבטלים את האפשרות?';
$l['message_quota'] = 'ציטוט הודעה:';
$l['message_quota_desc'] = 'Maximum number of private messages that can be stored by users in this group. If empty, users can store unlimited messages.';
$l['max_recipients'] = 'מכסימום נמענים להודעה:';
$l['max_recipients_desc'] = 'Maximum number of recipients a user can send a private message to at one time. If empty, users can send private messages to an unlimited number of recipients.';
$l['show_reputations'] = 'להראות מוניטין למשתמשים בקבוצה זו?';
$l['can_give_reputation'] = 'יכול לתת מוניטין למשתמשים?';
$l['points_to_award_take'] = 'נק\' לזכות/לשלול:';
$l['points_to_award_take_desc'] = 'Here you need to enter the number of points to give or take away on each reputation given by users of this group.';
$l['max_reputations_daily'] = 'מכסימום מוניטין ליום:';
$l['max_reputations_daily_desc'] = 'Here you can enter the maximum number of reputations that users in this group can give per day. To allow unlimited reputations per day, enter 0.';
$l['max_reputations_perthread'] = 'מכסימום מוניטין לנושא:';
$l['max_reputations_perthread_desc'] = 'When \'Allow Post Reputation\' is allowed, you can set the maximum amount of reputations that users in this group can give to the same user, in the same thread, in the box below. To allow unlimited reputations for a user, per thread, enter 0.';
$l['max_reputations_peruser'] = 'מכסימום מוניטין למשתמש:';
$l['max_reputations_peruser_desc'] = 'Along with a per thread maximum, you can enter a maximum number of reputations that users in this group can give to the same user per day. To allow unlimited reputations for a user, enter 0.';
$l['warning_system'] = 'מערכת אזהרה';
$l['can_send_warnings'] = 'יכול לשלוח אזהרות למשתמשים אחרים?';
$l['can_receive_warnings'] = 'יכול לקבל אזהרות ממשתמשים אחרים?';
$l['warnings_per_day'] = 'מס\' אזהרות מרבי ליום:';
$l['private_messaging'] = 'הודעות פרטיות?';
$l['calendar'] = 'לוח שנה';
$l['can_view_calendar'] = 'יכול לצפות בלוח שנה?';
$l['can_post_events'] = 'יכול לפרסם אירועים בלוח שנה?';
$l['can_bypass_event_moderation'] = 'יכול לפרסם אירועים בלוח שנה מבלי אישור מפורש?';
$l['can_moderate_events'] = 'יכול לנהל אירועי לוח שנה?';
$l['whos_online'] = 'מי מחובר';
$l['can_view_whos_online'] = 'יכול לצפות במי מחובר?';
$l['can_view_invisible'] = 'יכול לצפות במשתמשים בלתי נראים?';
$l['can_view_ips'] = 'יכול לראות כתובות IP במשתמשים בלתי נראים?';
$l['can_view_member_list'] = 'יכול לצפות ברשימת חברים?';
$l['show_in_birthday_list'] = 'יכול להיראות ברשימת ימי הולדת?';
$l['can_email_users'] = 'יכול לשלוח נושאים לחברים ואימייל למשתמשים?';
$l['can_email_users_override'] = 'יכול לכתוב מייל למשתמשים גם אם הם חסמו אותו?';
$l['max_emails_per_day'] = 'מכסימום מיילים ליום:';
$l['max_emails_per_day_desc'] = 'The maximum number of emails users can send using the \'Email User\' and \'Send Thread to Friend\' features. If set to 0, there is no limit.';
$l['email_flood_time'] = 'זמן הצפה של אימייל:';
$l['email_flood_time_desc'] = 'The number of minutes a user must wait after sending an email before they can send another. If set to 0, there is no wait.';
$l['forum_post_options'] = 'פוסטים ופורומים';
$l['user_options'] = 'משתמשים';
$l['can_manage_announce'] = 'יכול לנהל הכרזות?<br /><small>Please note that forum moderators must be assigned to at least one forum in order to manage announcements.</small>';
$l['can_manage_mod_queue'] = 'יכול לנהל רשימת (תור) ניהול?<br /><small>Please note that forum moderators must be assigned to at least one forum in order to manage the moderator queue.</small>';
$l['can_manage_reported_content'] = 'יכול לנהל תוכן מדווח?<br /><small>Please note that forum moderators must be assigned to at least one forum in order to manage reported content.</small>';
$l['can_view_mod_logs'] = 'יכול לצפות ברישומי מנהל?<br /><small>Please note that forum moderators must be assigned to at least one forum in order to view the moderator logs.</small>';
$l['can_edit_profiles'] = 'יכול לערוך פרופילים?<br /><small>Please note that forum moderators cannot edit the profiles of super moderators or administrators regardless of this permission.</small>';
$l['can_ban_users'] = 'יכול להרחיק משתמשים?<br /><small>Please note that forum moderators cannot ban super moderators or administrators regardless of this permission.</small>';
$l['can_view_warnlogs'] = 'יכול לצפות ברישומי אזהרות?';
$l['can_use_ipsearch'] = 'יכול לחפש IP?';
$l['outstanding_join_request'] = 'outstanding join requests';
$l['no_join_requests'] = 'There are no outstanding join requests for this user group.';
$l['no_assigned_leaders'] = 'You haven\'t assigned any users as leaders of this group yet. To create a leader for this group, fill in the form below.';
$l['error_missing_title'] = 'You did not enter a title for this new user group.';
$l['error_invalid_user_group'] = 'You have selected an invalid user group.';
$l['error_invalid_join_request'] = 'You have selected an invalid join request.';
$l['error_invalid_username'] = 'The username you entered is invalid.';
$l['error_already_leader'] = 'The user is already a leader of this user group.';
$l['error_invalid_group_leader'] = 'You specified an invalid group leader.';
$l['error_missing_namestyle_username'] = 'The username style must contain {username}';
$l['error_disallowed_namestyle_username'] = 'You can\'t use script, meta or base tags in the username style.';
$l['error_default_group_delete'] = 'Default groups cannot be deleted';
$l['error_cannot_have_both_types'] = 'You cannot have a joinable group that is both moderated and invite only. Please choose one or the other.';
$l['success_group_created'] = 'The new user group has been created successfully.';
$l['success_group_updated'] = 'The selected user group has been updated successfully.';
$l['success_group_deleted'] = 'The selected user group has been deleted successfully.';
$l['success_groups_disporder_updated'] = 'The user group display orders have been updated successfully.';
$l['success_join_request_approved'] = 'The selected join request has been approved successfully. The user is now a member of this user group.';
$l['success_join_request_denied'] = 'The selected join request has been denied successfully.';
$l['success_selected_requests_approved'] = 'The selected join requests have been approved successfully. The users are now part of this group.';
$l['success_selected_requests_denied'] = 'The selected join requests have been denied successfully.';
$l['success_user_made_leader'] = 'was successfully made a group leader for this user group.';
$l['success_group_leader_updated'] = 'The selected group leader has been updated successfully.';
$l['success_group_leader_deleted'] = 'The selected user has been removed from the group leaders list for this group successfully.';
$l['confirm_group_deletion'] = 'Are you sure you want to delete this user group?';
$l['confirm_group_leader_deletion'] = 'Are you sure you want to delete this group leader?';
