<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Fri, 01 May 2015 12:45:54 +0000
// --------------------------------------------------------------------------------

$l['user_titles'] = 'כותרות משתמשים';
$l['user_titles_desc'] = 'מאפשר לנהל את כותרות המשתמש. כותרות משתמש משויכות למשתמשים ע"פ מספר  הפוסטים שלהם ומאפשר כוכב מותאם אישית שיוצג בהתחשב במספר הפוסטים שיש למשתמש.';
$l['add_new_user_title'] = 'הוסף כותרת משתמש חדשה';
$l['add_new_user_title_desc'] = 'כאן תוכל להוסיף כותרת משתמש חדשה. <i>הערה: זוהי <strong>לא</strong><u><a href="index.php?module=user-group_promotions"> מערכת הקידום</a></u></i>';
$l['error_missing_title'] = 'You did not enter a title for this user title';
$l['error_missing_posts'] = 'You did not enter the minimum number of posts for this user title';
$l['error_cannot_have_same_posts'] = 'This user title cannot have the same minimum number of posts as another title';
$l['error_invalid_user_title'] = 'You have specified an invalid user title';
$l['success_user_title_created'] = 'כותרת המשתמש נוצרה בהצלחה';
$l['success_user_title_updated'] = 'כותרת המשתמש עודכנה בהצלחה';
$l['success_user_title_deleted'] = 'כותרת המשתמש שנבחרה הוסרה בהצלחה';
$l['title_to_assign'] = 'כותרת להחלה';
$l['title_to_assign_desc'] = 'This title will be shown for users underneath their name if they do not have a custom title set.';
$l['minimum_posts'] = 'מינימום פוסטים';
$l['minimum_posts_desc'] = 'The minimum number of posts for a user to have before they\'re assigned this user title.';
$l['number_of_stars'] = 'מספר כוכבים';
$l['number_of_stars_desc'] = 'Enter the number of stars to be shown under this user title. Set to 0 to show no stars.';
$l['star_image'] = 'תמונת כוכב';
$l['star_image_desc'] = 'If this user title should show stars, enter the path to the star image here. If empty, the user group star image will be shown. Use {theme} to specify the image directory for the viewers current theme.';
$l['save_user_title'] = 'שמור כותרת משתמש';
$l['edit_user_title'] = 'ערוך כותרת משתמש';
$l['edit_user_title_desc'] = 'עריכת כותרת משתמש';
$l['user_title_deletion_confirmation'] = 'אתה בטוח שברצונך למחוק כותרת משתמש זו?';
$l['manage_user_titles'] = 'נהל כותרות משתמשים';
$l['user_title'] = 'כותרת משתמש';
$l['no_user_titles'] = 'אין לך כותרות משתמשים מוגדרות כרגע';
