<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Fri, 01 May 2015 11:24:53 +0000
// --------------------------------------------------------------------------------

$l['mass_mail'] = 'מייל המוני';
$l['mass_mail_queue'] = 'רשימה (תור) מייל מסיבי';
$l['mass_mail_queue_desc'] = 'כאן תוכל לנהל מייל מאסיבי שנשלחים או ממתינים.';
$l['create_mass_mail'] = 'צור מייל המוני חדש';
$l['create_mass_mail_desc'] = 'כאן תוכל ליצור מייל חדש והגדיר את האפשרויות שלו.
';
$l['mass_mail_archive'] = 'ארכיון מיילים המוניים';
$l['mass_mail_archive_desc'] = 'כאן תוכל לצפות ברישומי המיילים ההמוניים שכבר נשלחו.';
$l['edit_mass_mail'] = 'ערוך מייל מסיבי';
$l['edit_mass_mail_desc'] = 'כאן תוכל לערוך מייל המוני ואת אפשרויותיו.';
$l['send_mass_mail'] = 'שלח מייל מסיבי';
$l['email_addr'] = 'כתובת EMAIL';
$l['board_name'] = 'שם הלוח';
$l['board_url'] = 'כתובת לוח';
$l['personalize_message'] = 'הפוך הודעה זו לאישית:';
$l['message_settings'] = 'הגדרות הודעות';
$l['subject'] = 'נושא';
$l['subject_desc'] = 'אנא הכנס את נושא ההודעה';
$l['send_via_email'] = 'שלח ע"י אימייל';
$l['send_via_pm'] = 'שלח ע"י הודעה פרטית';
$l['message_type'] = 'סוג הודעה';
$l['deliver_immediately'] = 'שלח מיידית';
$l['deliver_specific'] = 'שלח בתאריך מסויים';
$l['delivery_date'] = 'תאריך שליחה';
$l['delivery_date_desc'] = 'אנא בחר תאריך וזמן בו תרצה שהמייל ישלח
';
$l['per_page'] = 'בכל עמוד';
$l['per_page_desc'] = 'Please enter the number of mass mailings to run per page.';
$l['plain_text_only'] = 'טקסט פשוט בלבד';
$l['html_only'] = 'רק HTML';
$l['html_and_plain_text'] = 'HTML וטקסט פשוט';
$l['message_format'] = 'תצורת הודעה';
$l['define_html_message'] = 'הגדר את הודעת הHTML';
$l['define_html_message_desc'] = 'הכנס את גרסאת הHTML של ההודעה';
$l['auto_gen_plain_text'] = 'נסה לייצר גרסא טקסטואלית אוטומטית.';
$l['define_text_version'] = 'הגדרת את גרסאת הטקסט';
$l['define_text_version_desc'] = 'הכנס גרסא טקסטואלית של ההודעה';
$l['define_the_recipients'] = 'הגדר נמענים';
$l['username_contains'] = 'שם משתמש מכיל...';
$l['email_addr_contains'] = 'כתובת מייל מכילה...';
$l['members_of'] = 'חברי הקבוצה...';
$l['greater_than'] = 'גדול מ';
$l['is_exactly'] = 'בדיוק';
$l['less_than'] = 'קטן מ';
$l['more_than'] = 'יותר מ';
$l['post_count_is'] = 'מונה הודעות הינו';
$l['hours'] = 'שעות';
$l['days'] = 'ימים';
$l['weeks'] = 'שבועות';
$l['months'] = 'חודשים';
$l['years'] = 'שנים';
$l['ago'] = '';
$l['user_last_active'] = 'משתמש היה פעיל לאחרונה';
$l['user_registered'] = 'משתמש רשום';
$l['save_mass_mail'] = 'שמור מייל המוני';
$l['step_four'] = 'שלב 4';
$l['delivery_method'] = 'שיטת שליחה';
$l['private_message'] = 'הודעה פרטית';
$l['email'] = 'אימייל';
$l['message'] = 'הודעה';
$l['text_based'] = 'מבוסס טקסט';
$l['preview'] = 'תצוגה מקדימה';
$l['mass_mail_preview'] = 'תצוגה מקדימה של מייל המוני';
$l['html_based'] = 'מבוסס HTML';
$l['total_recipients'] = 'סה"כ נמענים';
$l['change_recipient_conds'] = 'שנה תנאי נמענים';
$l['review_message'] = 'סקור את ההודעה שלך';
$l['define_delivery_date'] = 'הגדר תאריך שליחה';
$l['schedule_for_delivery'] = 'תזמון עבור השליחה';
$l['username'] = 'שם משתמש';
$l['step_three'] = 'שלב 3';
$l['next_step'] = 'השלב הבא';
$l['step_two'] = 'שלב 2';
$l['review_text_version'] = 'סקור גרסא טקסטואלית';
$l['review_text_version_desc'] = 'Please review the automatically generated text version';
$l['step_one'] = 'שלב 1';
$l['status'] = 'מצב';
$l['recipients'] = 'נמענים';
$l['delivered'] = 'נשלח';
$l['canceled'] = 'בוטל';
$l['resend'] = 'שלח מחדש';
$l['no_archived_messages'] = 'אין לך מייל המוני שנשלח או בוטל בעבר.';
$l['draft'] = 'טיוטה';
$l['queued'] = 'ממתין';
$l['delivering'] = 'שולח';
$l['na'] = 'לא זמין';
$l['mass_mail_cancel_confirmation'] = 'Are you sure you wish to cancel the delivery of this mass mailing?';
$l['no_unsent_messages'] = 'אין לך מיילים המוניים שנשלחים , ממתינים או שנשלחו בעבר.';
$l['error_invalid_mid'] = 'בחרת מייל המוני לא תקין';
$l['error_only_in_future'] = 'You can only deliver mass mailings in the future.';
$l['error_no_users'] = 'Your search criteria did not return any users. Please adjust your criteria and try again.';
$l['error_missing_plain_text'] = 'You did not enter a plain text version of this message.';
$l['error_missing_subject'] = 'You did not enter a subject for this mass mailing.';
$l['error_missing_message'] = 'You did not enter a message to send.';
$l['error_missing_html'] = 'You did not enter a HTML version of this message.';
$l['error_delete_invalid_mid'] = 'You have selected an invalid mass mailing to delete.';
$l['success_mass_mail_saved'] = 'The mass mailing has been saved successfully.';
$l['success_mass_mail_deleted'] = 'The selected mass mailing has been deleted successfully.';
$l['success_mass_mail_resent'] = 'The mass mailing has been copied successfully. Please review it below.';
$l['success_mass_mail_canceled'] = 'The mass mailing delivery has been canceled successfully.';
$l['mass_mail_deletion_confirmation'] = 'Are you sure you want to delete this mass mailing?';
