<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Fri, 01 May 2015 11:23:34 +0000
// --------------------------------------------------------------------------------

$l['user_group_promotions'] = 'קידום קבוצות משתמשים';
$l['user_group_promotions_desc'] = 'כאן תוכל לנהל קידומי קבוצות משתמשים';
$l['edit_promotion'] = 'ערוך קידום';
$l['edit_promotion_desc'] = 'כאן תוכל לערוך קידומים שרצים אוטומטית בלוח שלך.';
$l['add_new_promotion'] = 'הוסף קידום חדש';
$l['add_new_promotion_desc'] = 'כאן תוכל ליצור קידום חדש שרץ אוטומטית.';
$l['title'] = 'כותרת';
$l['short_desc'] = 'תיאור קצר';
$l['post_count'] = 'מונה פוסטים';
$l['thread_count'] = 'מונה נושאים';
$l['reputation'] = 'מוניטין';
$l['referrals'] = 'הפניות';
$l['time_registered'] = 'זמן הרשמה';
$l['time_online'] = 'זמן Online';
$l['promo_requirements'] = 'דרישות קידום';
$l['promo_requirements_desc'] = 'Select which criteria must be met for this promotion. Holding down CTRL selects multiple criteria.';
$l['greater_than_or_equal_to'] = 'גדול מ או שווה ל';
$l['greater_than'] = 'גדול מ';
$l['equal_to'] = 'שווה ל';
$l['less_than_or_equal_to'] = 'קטן מ או שווה ל';
$l['less_than'] = 'קטן מ';
$l['reputation_count'] = 'מונה מוניטין';
$l['reputation_count_desc'] = 'Enter the amount of reputation to be required. Reputation must be selected as a required value for this to be included. Select the type of comparison for reputation.';
$l['referral_count'] = 'מונה הפניות';
$l['referral_count_desc'] = 'Enter the number of referrals required. Referral count must be selected as a required value for this to be included. Select the type of comparison for referrals.';
$l['warning_points'] = 'נקודות אזהרה';
$l['warning_points_desc'] = 'Enter the number of warning points required. Warning Points must be selected as a required value for this to be included. Select the type of comparison for warning points.';
$l['post_count_desc'] = 'Enter the number of posts required. Post count must be selected as a required value for this to be included. Select the type of comparison for posts.';
$l['thread_count_desc'] = 'Enter the number of threads required. Thread count must be selected as a required value for this to be included. Select the type of comparison for threads.';
$l['hours'] = 'שעות';
$l['days'] = 'ימים';
$l['weeks'] = 'שבועות';
$l['months'] = 'חודשים';
$l['years'] = 'שנים';
$l['time_registered_desc'] = 'Enter the number of hours, days, weeks, months, or years that this user must have been registered for. Time registered must be selected as a required value for this to be included. Select whether the time registered should be counted in hours, days, weeks, months, or years.';
$l['time_online_desc'] = 'Enter the number of hours, days, weeks, months, or years that this user must have been online for. Time online must be selected as a required value for this to be included. Select whether the time spend online should be counted in hours, days, weeks, months, or years.';
$l['all_user_groups'] = 'כל קבוצות המשתמשים';
$l['orig_user_group'] = 'קבוצת משתמשים מקורית';
$l['orig_user_group_desc'] = 'Select which user group or user groups that the user must be in for the promotion to run. Holding down CTRL selects multiple groups.';
$l['new_user_group'] = 'קבוצת משתמש חדשה';
$l['new_user_group_desc'] = 'Select the user group that the user will be moved into after this promotion.';
$l['primary_user_group'] = 'קבוצת משתמש עיקרית';
$l['secondary_user_group'] = 'קבוצת משתמש משנית';
$l['user_group_change_type'] = 'שנה סוג קבוצת משתמש';
$l['user_group_change_type_desc'] = 'Select \'Primary User Group\' if the user should have their primary user group changed to the new user group. Select \'Secondary User Group\' if the user should have the new user group added as an secondary user group to their profile.';
$l['enabled'] = 'מופעל?';
$l['enable_logging'] = 'לאפשר רישומים?';
$l['promotion_logs'] = 'רישומי קידומים?';
$l['view_promotion_logs'] = 'צפה ברישומי קידומים?';
$l['view_promotion_logs_desc'] = 'כאן תוכל לצפות ברישומים של קידום שרצו בעבר.';
$l['promoted_user'] = 'משתמש מקודם';
$l['time_promoted'] = 'זמן קידום';
$l['no_promotion_logs'] = 'לא נרשמו קידומים בינתיים';
$l['promotion_manager'] = 'מנהל הקידומים';
$l['promotion'] = 'קידום';
$l['disable_promotion'] = 'בטל קידום';
$l['enable_promotion'] = 'הפעל קידום';
$l['delete_promotion'] = 'מחק קידום';
$l['no_promotions_set'] = 'אין כרגע קידומים מוגדרים.';
$l['update_promotion'] = 'שמור קידום';
$l['multiple_usergroups'] = 'מספר קבוצות משתמש';
$l['secondary'] = 'משני';
$l['primary'] = 'עיקרי';
$l['error_no_promo_id'] = 'You did not enter a promotion id';
$l['error_invalid_promo_id'] = 'You did not enter a valid promotion id';
$l['error_no_title'] = 'You did not enter a title for this promotion';
$l['error_no_desc'] = 'You did not enter a description for this promotion';
$l['error_no_requirements'] = 'You did not select at least one requirement for this promotion';
$l['error_no_orig_usergroup'] = 'You did not select at least one original user group for this promotion';
$l['error_no_new_usergroup'] = 'You did not select at least one new user group for this promotion';
$l['error_no_usergroup_change_type'] = 'You did not select at least one user group change type for this promotion';
$l['success_promo_disabled'] = 'The selected group promotion has been disabled successfully.';
$l['success_promo_deleted'] = 'The selected group promotion has been deleted successfully.';
$l['success_promo_enabled'] = 'The selected group promotion has been enabled successfully.';
$l['success_promo_updated'] = 'The selected group promotion has been updated successfully.';
$l['success_promo_added'] = 'The promotion has been created successfully.';
$l['confirm_promo_disable'] = 'Are you sure you want to disable this promotion?';
$l['confirm_promo_deletion'] = 'Are you sure you wish to delete this promotion?';
