<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Sun, 26 Apr 2015 12:31:56 +0000
// --------------------------------------------------------------------------------

$l['contact'] = 'צור קשר';
$l['contact_no_message'] = 'לא הזנת הודעה לשליחה';
$l['contact_no_subject'] = 'אתה מתבקש להכניס נושא';
$l['contact_no_email'] = 'אתה חייב להזין כתובת אימייל חוקית';
$l['contact_success_message'] = 'הודעתך נשלחה למנהל המערכת';
$l['contact_subject'] = 'נושא';
$l['contact_subject_desc'] = 'תמצת את נושא הודעתך';
$l['contact_message'] = 'הודעה';
$l['contact_message_desc'] = 'תאר את דאגתך בנושא בפירוט';
$l['contact_email'] = 'אימייל';
$l['contact_email_desc'] = 'הכנס את האימייל שלך עמ"נ שנוכל לחזור אלייך';
$l['contact_send'] = 'שלח';
$l['image_verification'] = 'מנגנון תמונה';
$l['verification_note'] = 'אנא הכנס את הטקסט המופיע בתמונה לתוך התיבה שלמטה. הודעה זו מונעת שליחת הודעות אוטומטית.';
$l['verification_subnote'] = '(לא רגיש לאותיות גדולות וקטנות)';
$l['invalid_captcha'] = 'הכנסת קוד תמונה שגוי. אנא הכנס את הקוד בדיוק כפי שמופיע בתמונה.';
$l['subject_too_long'] = 'הנושא ארוך מדיי אנא הכנס נושא שקצר מ{1} תווים. (הוכנסו {2})';
$l['message_too_short'] = 'ההודעה קצרה מדיי. אנא הכנס הודעה בעלת לפחות {1} תווים. (הוזנו {2} תווים)';
$l['message_too_long'] = 'ההודעה ארוכה מדיי. אנא הכנס הודעה קצרה יותר מ{1} תווים. (הוכנסו {2})';
$l['error_stop_forum_spam_spammer'] = 'מצטערים, האימייל או IP שלך תואמים לזה של ספאמר ידוע.
לכן הודעתך נחסמה.';
$l['error_stop_forum_spam_fetching'] = 'מצטערים. משהו השתבש בזיהוי ההודעה שלך אל מול מסד הספאמרים.
כפי הנראה מסד הנתונים לא ניתן לגישה כעת. אנא נסה במועד אחר.';
