<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Sun, 26 Apr 2015 12:26:29 +0000
// --------------------------------------------------------------------------------

$l['logindata_invalidpwordusername'] = 'שם משתמש או ססמה שגויים.<br />
אם שכחת את ססמתך אנא  <a href="member.php?action=lostpw">קבל אחת חדשה</a>.';
$l['logindata_invalidpwordusernameemail'] = 'הזנת אימייל או ססמה שגויים.<br />
אם שכחת את ססמתך אנא  <a href="member.php?action=lostpw">קבל אחת חדשה</a>.';
$l['logindata_invalidpwordusernamecombo'] = 'הכנסת שם משתמש או ססמה, או אימייל וססמה שגויים.
אם שכחת את ססמתך אנא  <a href="member.php?action=lostpw">קבל אחת חדשה</a>.';
$l['logindata_regimageinvalid'] = 'קוד התמונה שהזנת הינו שגוי. אנא הכנס אותו בדיוק כפי שמופיע בתמונה.';
$l['logindata_regimagerequired'] = 'אנא הזן את הקוד שבתמונה עמ"נ להמשיך בתהליך ההתחברות.
אנא הכנס אותו בדיוק כפי שמופיע בתמונה.';
