<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Sun, 26 Apr 2015 12:07:36 +0000
// --------------------------------------------------------------------------------

$l['nav_editpost'] = 'ערוך תגובה';
$l['edit_post'] = 'ערוך תגובה';
$l['delete_post'] = 'מחק תגובה';
$l['delete_q'] = 'מחק?';
$l['delete_1'] = 'על מנת למחוק הודעה זו, יש לסמן את תיבת הבחירה מימין ולאחר מכן ללחוץ על כפתור המחיקה בצד שמאל.';
$l['delete_2'] = '<b>הערה:</b> אם הודעה זו היא ההודעה הראשונה של האשכול, יוסר עמה כל האשכול לצמיתות.';
$l['subject'] = 'נושא';
$l['your_message'] = 'ההודעה שלך';
$l['post_options'] = 'אפשרויות:';
$l['options_sig'] = '<strong>חתימה:</strong> כלול את חתימתך בהודעה.';
$l['options_emailnotify'] = '<strong>התראת דוא"ל:</strong> קבל הודעה לדואר האלקטרוני כאשר תכתב תגובה חדשה לאשכול.';
$l['options_disablesmilies'] = '<strong>כבה סמיילים:</strong> מנע מסמיילים להופיע בהודעה זו.';
$l['preview_post'] = 'הודעה קודמת';
$l['update_post'] = 'עדכן הודעה';
$l['poll'] = 'סקר:';
$l['poll_desc'] = 'ניתן להוסיף סקר לאשכול זה.<!-- http://myhebb.org/ -->';
$l['poll_check'] = 'ברצוני לצרף סקר';
$l['num_options'] = 'מספר אפשרויות הצבעה:';
$l['max_options'] = '(מקסימום: {1})';
$l['delete_now'] = 'מחק';
$l['edit_time_limit'] = 'מצטערים, אך אינך רשאי לערוך את ההודעה הזו. האדמין הגביל את אפשרות העריכה לאפשרית לעד {1} דקות לאחר הכתיבה.';
$l['no_prefix'] = 'ללא תיוג';
$l['redirect_nodelete'] = 'ההודעה לא נמחקה מכיוון שאינך סימנת את תיבת הבחירה של המחיקה.<!-- http://myhebb.org/ -->';
$l['redirect_postedited'] = 'ההודעה נערכה בהצלחה.<br />';
$l['redirect_postedited_redirect'] = 'כעת תועבר בחזרה לאשכול.';
$l['redirect_postedited_poll'] = 'ההודעה נערכה בהצלחה.<br />מכיוון שבחרת לצרף סקר לאשכול, כעת תועבר לעמוד יצירת הסקר.';
$l['error_invalidpost'] = 'מצטערים, נראה כי הכתובת שגוייה.';
$l['redirect_threaddeleted'] = 'האשכול נערך בהצלחה.<br />כעת תועבר בחזרה לפורום.';
$l['redirect_postdeleted'] = 'ההודעה נמחקה בהצלחה.<br />כעת תועבר בחזרה לאשכול.';
$l['redirect_threadclosed'] = 'לא ניתן לערוך הודעות באשכול זה מכיוון שהוא ננעל.';
$l['redirect_post_moderation'] = 'האדמין החליט כי כל העריכות דורשות לעבור אימות. כעת תועבר בחזרה לאשכול.';
$l['redirect_thread_moderation'] = 'האדמין החליט כי כל העריכות דורשות לעבור אימות. כעת תועבר בחזרה לפורום.';
$l['thread_deleted'] = 'אשכול מחוק לנצח';
$l['post_deleted'] = 'הודעה מחוקה לנצח';
$l['editreason'] = 'סיבת עריכה:';
$l['redirect_norestore'] = 'The post was not restored because you didn\'t check the "Restore" checkbox.';
$l['redirect_threadrestored'] = 'Thank you, the thread has been restored.<br />You will now be returned to the forum.';
$l['redirect_postrestored'] = 'Thank you, the post has been restored.<br />You will now be returned to the thread.';
$l['error_already_delete'] = 'מצטערים, אבל הפוסט הזה כבר מחוק';
$l['thread_soft_deleted'] = 'נושא מחוק';
$l['post_soft_deleted'] = 'פוסט מחוק';
$l['thread_restored'] = 'נושא משוחזר';
$l['post_restored'] = 'פוסט משוחזר';
$l['error_already_deleted'] = 'הפוסט הנבחר כבר נמחק';
