<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Sat, 25 Apr 2015 14:26:41 +0000
// --------------------------------------------------------------------------------

$l['boardstats'] = 'סטטיסטיקות המערכת';
$l['new_posts'] = 'הפורום מכיל הודעות חדשות';
$l['no_new_posts'] = 'הפורום אינו מכיל הודעות חדשות';
$l['forum_locked'] = 'הפורום סגור לתגובות חדשות';
$l['forum_unapproved_posts_count'] = 'יש כרגע {1} הודעות לא מאושרות בפורום זה.';
$l['forum_unapproved_post_count'] = 'יש כרגע הודעה אחת לא מאושרת בפורום זה.';
$l['forum_unapproved_threads_count'] = 'יש כרגע {1} אשכולות לא מאושרים בפורום זה.';
$l['forum_unapproved_thread_count'] = 'יש כרגע אשכול אחד לא מאושר בפורום זה.';
$l['markread'] = 'סמן פורומים כנקראו';
$l['forumteam'] = 'צוות הפורום';
$l['forumstats'] = 'סטטיסטיקות פורום';
$l['todays_birthdays'] = 'ימי הולדת';
$l['birthdayhidden'] = 'חבוי';
$l['quick_login'] = 'התחברות מהירה:';
$l['index_logout'] = 'התנתק';
$l['private_messages'] = 'הודעות פרטיות';
$l['pms_new'] = 'יש לך {1} הודעות חדשות מאז ביקורך האחרון.';
$l['pms_unread_total'] = '(יש לך {1} הודעות שלא נקראו ו-{2} סה"כ הודעות בכל התיקיות.)';
$l['stats_posts_threads'] = 'המשתמשים שלנו כתבו {1} תגובות בכ-{2} אשכולות.
';
$l['stats_numusers'] = 'נכון לעכשיו יש במערכת {1} משתמשים רשומים.';
$l['stats_newestuser'] = 'ברוכים הבאים למשתמש החדש ביותר, <b>{1}</b>.';
$l['stats_mostonline'] = 'שיא מספר המשתמשים המחוברים בו-זמנית הוא {1} משתמשים, בתאריך ה-{2} בשעה {3}';
$l['whos_online'] = 'מי מחובר
';
$l['complete_list'] = 'רשימה מלאה';
$l['online_online_plural'] = 'משתמשים';
$l['online_online_singular'] = 'משתמש';
$l['online_member_plural'] = 'משתמשים';
$l['online_member_singular'] = 'משתמש';
$l['online_anon_plural'] = 'הם';
$l['online_anon_singular'] = 'הוא';
$l['online_guest_plural'] = 'אורחים';
$l['online_guest_singular'] = 'אורח';
$l['online_note'] = '{1} {2} פעילים ב-{3} הדקות האחרונות ({4} {5}, {6} מתוכם {7} בלתי נראים, ו-{8} {9}).';
$l['subforums'] = '<strong>תת פורומים:</strong>
';
