<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Sun, 26 Apr 2015 12:00:56 +0000
// --------------------------------------------------------------------------------

$l['nav_memberlist'] = 'רשימת משתמשים';
$l['memberlist_disabled'] = 'רשימת המשתמשים כובתה על ידי האדמין.';
$l['member_list'] = 'רשימת משתמשים';
$l['avatar'] = 'סמלון';
$l['username'] = 'שם משתמש';
$l['joined'] = 'הצטרף בתאריך';
$l['lastvisit'] = 'ביקור אחרון';
$l['posts'] = 'מונה תגובות';
$l['threads'] = 'מונה אשכולות';
$l['referrals'] = 'הפניות';
$l['search_members'] = 'חיפוש רשימת משתמשים';
$l['website'] = 'אתר';
$l['sort_by'] = 'מיין לפי';
$l['contains'] = 'מכיל:';
$l['sort_by_username'] = 'מיין לפי: שם משתמש';
$l['sort_by_regdate'] = 'מיין לפי: תאריך ההרשמה';
$l['sort_by_lastvisit'] = 'מיין לפי: מועד ביקור אחרון';
$l['sort_by_posts'] = 'מיין לפי: מונה תגובות';
$l['sort_by_threads'] = 'מיין לפי: מונה אשכולות';
$l['sort_by_referrals'] = 'מיין לפי: מספר הפניות';
$l['order_asc'] = 'סדר עולה';
$l['order_desc'] = 'סדר יורד';
$l['asc'] = 'עולה';
$l['desc'] = 'יורד';
$l['forumteam'] = 'הצג את צוות הפורום';
$l['advanced_search'] = 'חיפוש מתקדם';
$l['nav_memberlist_search'] = 'חיפוש';
$l['search_member_list'] = 'חיפוש רשימת משתמשים';
$l['search_criteria'] = 'קריטריונים לחיפוש';
$l['begins_with'] = 'מתחיל עם';
$l['username_contains'] = 'מכיל';
$l['search_website'] = 'כתובת אתר';
$l['search_aim'] = 'משתמש AIM';
$l['search_skype'] = 'Skype';
$l['search_google'] = 'Google Talk';
$l['search_yahoo'] = 'שם משתמש ב-Yahoo!';
$l['search_icq'] = 'מספר ICQ';
$l['search_options'] = 'אפשרויות חיפוש';
$l['per_page'] = 'תוצאות בכל עמוד';
$l['search'] = 'חיפוש';
$l['search_user'] = 'חפש משתמש';
$l['error_no_members'] = '<p>לא נמצאו משתמשים אשר עונים לקריטריונים שציינת.</p><p>אנא נסה שוב עם קריטריונים שונים.</p>';
$l['a'] = 'A';
$l['b'] = 'B';
$l['c'] = 'C';
$l['d'] = 'D';
$l['e'] = 'E';
$l['f'] = 'F';
$l['g'] = 'G';
$l['h'] = 'H';
$l['i'] = 'I';
$l['j'] = 'J';
$l['k'] = 'K';
$l['l'] = 'L';
$l['m'] = 'M';
$l['n'] = 'N';
$l['o'] = 'O';
$l['p'] = 'P';
$l['q'] = 'Q';
$l['r'] = 'R';
$l['s'] = 'S';
$l['t'] = 'T';
$l['u'] = 'U';
$l['v'] = 'V';
$l['w'] = 'W';
$l['x'] = 'X';
$l['y'] = 'Y';
$l['z'] = 'Z';
