<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Sun, 26 Apr 2015 10:52:37 +0000
// --------------------------------------------------------------------------------

$l['nav_newreply'] = 'הגב לאשכול';
$l['post_reply_to'] = 'הגב ל {1}';
$l['post_new_reply'] = 'פרסם תגובה חדשה';
$l['reply_to'] = 'הגב לאשכול: {1}';
$l['post_subject'] = 'כותרת התגובה:';
$l['your_message'] = 'הודעתך:';
$l['post_options'] = 'אפשרויות תגובה:';
$l['options_sig'] = '<b>חתימה:</b> כלול את החתימה שלך (מחוברים בלבד).';
$l['options_emailnotify'] = '<b>התראות אימייל:</b> קבלת הודעת אימייל ברגע שיש הודעות חדשות באשכול שלך (מחוברים בלבד).';
$l['options_disablesmilies'] = '<b>בטל סמיילים:</b> לבטל הצגת סמיילים באשכול זה.';
$l['post_reply'] = 'פרסם תגובה';
$l['preview_post'] = 'תצוגה מקדימה';
$l['mod_options'] = 'אפשרויות מנהל:';
$l['close_thread'] = '<b>סגור אשכול</b>: מנע מתגובות באשכול זה בעתיד.';
$l['stick_thread'] = '<b>אשכול נעוץ:</b> נעץ אשכול זה מעל כל האשכולות בפורום.';
$l['forum_rules'] = 'חוקי - {1}';
$l['thread_review'] = 'סקירת אשכול (הודעות חדשות קודם)';
$l['thread_review_more'] = 'לאשכול יש יותר מ- {1} תגובות. <a href="{2}">קרא את כל האשכול.</a>';
$l['posted_by'] = 'נכתב ע"י';
$l['draft_saved'] = 'התגובה החדשה נשמרה בהצלחה כטיוטה.<br />אתה מועבר לרשימת הטיוטות שלך.';
$l['image_verification'] = 'אימות תמונה';
$l['verification_note'] = 'אנא הקלד את הטקסט שבתמונה. התהליך הזה נועד למנוע כתיבת הודעות אוטומטית על ידי בוטים.';
$l['verification_subnote'] = '(רגיש לאותיות קטנות וגדולות)';
$l['invalid_captcha'] = 'אימות התמונה שרשמת אינו נכון. אנא הקש את האותיות בדיוק כפי שהן מופיעות בתמונה.';
$l['error_post_already_submitted'] = 'כבר הגבת תגובה זו באשכול זה. אנא בקר באשכול בכדי לראות את תגובתך.';
$l['multiquote_external_one'] = 'ציטטת הודעה אחת מאשכול אחר.';
$l['multiquote_external'] = 'ציטטת {1} הודעות מאשכול אחר.';
$l['multiquote_external_one_deselect'] = 'בטל בחירת הודעה זו';
$l['multiquote_external_deselect'] = 'בטל בחירת הודעות אלו';
$l['multiquote_external_one_quote'] = 'צטט הודעה זו גם';
$l['multiquote_external_quote'] = 'צטט הודעות אלו גם';
$l['redirect_newreply'] = 'תודה לך, תגובתך התפרסמה.';
$l['redirect_newreply_moderation'] = '<br />מנהל המערכת החליט שכל ההודעות בפורום זה מחוייבות באישור מנהל, ולכן אתה מועבר כעט לאשכול.';
$l['redirect_newreply_post'] = '<br />אתה מועבר לתגובה שלך';
$l['redirect_newreplyerror'] = 'מצטערים, אך תגובתך נדחתה עקב חוסר תוכן.<br />אתה מועבר לאשכול.';
$l['redirect_threadclosed'] = 'אינך יכול להגיב לאשכול זה מכיוון שהאשכול ננעל ע"י מנהל.';
$l['error_post_noperms'] = 'אין לך הרשאות לעריכת טיוטה זו.';
$l['error_stop_forum_spam_spammer'] = 'Sorry, your username or IP address matches that of a known spammer. If you feel this is a mistake, please contact an administrator';
$l['error_stop_forum_spam_fetching'] = 'Sorry, something went wrong verifying your reply against a spammer database. Most likely the database couldn\'t be accessed. Please try again later.';
$l['error_suspendedposting'] = 'Your posting privileges are currently suspended {1}.<br /><br />

Suspension Date: {2}';
$l['error_suspendedposting_temporal'] = 'until {1}';
$l['error_suspendedposting_permanent'] = 'לצמיתות';
