<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.2)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1801
// Last edited in MyBB Editor by : Elfassy
// Last edited date : Mon, 17 Nov 2014 15:50:26 +0000
// --------------------------------------------------------------------------------

$l['nav_pms'] = 'הודעות פרטיות';
$l['nav_send'] = 'יצירת הודעה';
$l['nav_tracking'] = 'מעקב הודעות';
$l['nav_folders'] = 'ניהול תיקיות';
$l['nav_empty'] = 'תיקיות ריקות';
$l['nav_export'] = 'ייצוא הודעות';
$l['nav_search'] = 'חיפוש';
$l['nav_results'] = 'תוצאות';
$l['new_pm'] = 'הודעה חדשה';
$l['old_pm'] = 'הודעה ישנה';
$l['reply_pm'] = 'השיב';
$l['fwd_pm'] = 'הודעה שהועברה';
$l['pms_disabled'] = 'You cannot use the private messaging functionality as it has been disabled by the Administrator.';
$l['private_messaging'] = 'הודעות פרטיות';
$l['inbox'] = 'דואר נכנס';
$l['compose_message2'] = 'צור הודעה';
$l['manage_folders'] = 'ניהול תיקיות';
$l['pm_search_results'] = 'תוצאות חיפוש הודעות';
$l['message_title'] = 'כותרת ההודעה';
$l['sender'] = 'שולח';
$l['sentto'] = 'נמען';
$l['date_sent'] = 'מועד';
$l['desc'] = 'סדר יורד';
$l['asc'] = 'סדר עולה';
$l['delete_pm'] = 'מחק';
$l['move_to'] = 'העבר';
$l['or'] = 'או';
$l['selected_messages'] = 'ההודעות שנבחרו';
$l['go'] = 'שלח';
$l['pmspaceused'] = 'of PM space used.';
$l['jump_folder'] = 'עבור לתיקייה:';
$l['archive_messages'] = 'Export Private Messages';
$l['archive_note'] = 'The following tool will let you mass download your private messages out of a selected folder, messages sent after a particular date, your read messages, and drafted messages for later viewing.';
$l['folders'] = 'תיקיות:';
$l['all_folders'] = 'כל התיקיות';
$l['date_limit'] = 'Date Limitation:';
$l['date_limit_older'] = 'Export messages older than';
$l['date_limit_newer'] = 'Export messages newer than';
$l['date_limit_disregard'] = 'Disregard date';
$l['date_limit_days'] = 'days';
$l['export_unread'] = 'Export Unread Messages?';
$l['delete_archived'] = 'Delete Exported Messages?';
$l['delete_archived_note'] = 'Do you want to delete the messages from your folders once they have been exported?';
$l['export_format'] = 'Export File Format:';
$l['export_format_note'] = 'Please choose the file type of which to download attachments.';
$l['export_html'] = 'HTML File (.html)';
$l['export_txt'] = 'Text File (.txt)';
$l['export_csv'] = 'Importable MS Excel File (.csv)';
$l['private_messages_for'] = 'Private Messages for {1}';
$l['exported_date'] = 'Exported: {1}, {2}';
$l['subject'] = 'כותרת:';
$l['to'] = 'נמען:';
$l['from'] = 'שולח:';
$l['sent'] = 'נשלח:';
$l['export_messages2'] = 'הורד הודעות';
$l['empty_folders'] = 'Empty Private Messaging Folders';
$l['empty_folders2'] = 'רוקן הודעות';
$l['empty_note'] = 'Here you can delete private messages from selected folders at one time. Simply select the folders you wish the messages to be deleted from and click \'Delete\'. You cannot undo these changes.<br /><strong>Note: Once these messages are deleted there is no way to recover them.</strong>';
$l['num_messages'] = 'Message Count';
$l['empty_q'] = 'Empty Folder?';
$l['keep_unread'] = 'Keep Unread Messages';
$l['pm_folders'] = 'Private Messaging Folders';
$l['existing_folders'] = 'תיקיות קיימות';
$l['edit_folder_note'] = 'באפשרותך לשנות את השמות של תיקיות ההודעות פרטיות הנוכחיות שלך כאן. בשביל למחוק תיקיה, מחק את השם שלה. ישנן תיקיות אשר אי אפשר למחוק.<br /><strong>זכור: מחיקת תיקייה תמחק את כל ההודעות שבתוכה.</strong>';
$l['new_folders'] = 'הוסף תיקיות חדשות';
$l['add_folders_note'] = 'כאן אתה יכול ליצור תיקיות חדשות. אתה לא חייב למלא את כל השדות.';
$l['update_folders'] = 'עדכן תיקיות';
$l['cannot_be_removed'] = 'אי אפשר למחוק';
$l['reached_warning'] = 'Warning. You have reached your message limit.';
$l['reached_warning2'] = 'To be able to receive messages you will need to delete old messages.';
$l['deny_receipt'] = '[התעלם מהשולח]';
$l['viewing_pm'] = 'צפייה בהודעה פרטית:';
$l['reply'] = 'השב';
$l['reply_to_all'] = 'השב לכולם';
$l['forward'] = 'העבר';
$l['compose_pm'] = 'יצירת הודעה חדשה';
$l['compose_to'] = 'נמענים:';
$l['compose_bcc'] = 'עותק מוסתר:';
$l['compose_bcc_show'] = 'עותק מוסתר';
$l['compose_bcc_show_title'] = 'Show the BCC input box allowing you to blind carbon copy messages to other users.';
$l['separate_names'] = 'יש להפריד מספר מרובה של נמענים באמצעות פסיק.';
$l['max_recipients'] = '<br />You may send this message to a maximum of <strong>{1}</strong> people.';
$l['compose_subject'] = 'נושא:';
$l['compose_message'] = 'הודעה:';
$l['compose_options'] = 'אפשרויות:';
$l['message_icon'] = 'אייקון הודעה:';
$l['options_sig'] = '<strong>חתימה:</strong> כלול את החתימה שלך בהודעה זו.';
$l['options_disable_smilies'] = '<strong>ביטול סמיילים:</strong> בטל הצגת סמיילים בהודעה זו.';
$l['options_save_copy'] = '<strong>שמור עותק:</strong> שמור עותק של הודעה זו לתיקיית דואר שנשלח.';
$l['options_read_receipt'] = '<strong>בקש אישור קריאה:</strong> קבל הודעה כאשר ההודעה שלך נקראה.';
$l['send_message'] = 'שלח הודעה';
$l['save_draft'] = 'שמור כטיוטה';
$l['preview'] = 'תצוגה מקדימה';
$l['select_buddy'] = 'Or Select a Buddy:';
$l['pm_tracking'] = 'Private Message Tracking';
$l['read_messages'] = 'הודעות שנקראו';
$l['unread_messages'] = 'הודעות שלא נקראה';
$l['q'] = '?';
$l['dateread'] = 'תאריך שנקרא';
$l['stop_tracking'] = 'הפסק מעקב';
$l['datesent'] = 'תאריך שליחה';
$l['cancel'] = 'ביטול';
$l['export_date_sent'] = 'תאריך';
$l['export_folder'] = 'תיקייה';
$l['export_subject'] = 'כותרת';
$l['export_to'] = 'אל';
$l['export_from'] = 'מ';
$l['export_message'] = 'הודעה';
$l['not_sent'] = 'N/A (not sent)';
$l['at'] = 'at';
$l['nomessages'] = 'אין הודעות פרטיות בתיקיה זו.';
$l['details'] = 'פרטין';
$l['message'] = 'הודעה';
$l['buddy_list'] = 'Buddy List';
$l['multiple_recipients'] = '<em>Multiple recipients</em>';
$l['bcc'] = 'BCC:';
$l['reply_title'] = 'Reply to this private message';
$l['forward_title'] = 'Forward this private message to another user';
$l['delete_title'] = 'Delete this private message';
$l['you_replied_on'] = 'You replied to this message on {1}';
$l['you_forwarded_on'] = 'You forwarded this message on {1}';
$l['you_replied'] = 'You replied to this message {1}';
$l['you_forwarded'] = 'You forwarded this message {1}';
$l['select_from_buddies'] = 'בחר מרשימת החברים';
$l['no_readmessages'] = 'כרגע אין לך הודעות במעקב שנקראו.';
$l['no_unreadmessages'] = 'כרגע אין לך הודעות במעקב שלא נקראו.';
$l['stop_tracking_all'] = 'עצור מעקב אחר כל ההודעות';
$l['enter_keywords'] = 'הזן מילות מפתח';
$l['advanced_search'] = 'חיפוש מתקדם';
$l['search_pms'] = 'חפש הודעות פרטיות';
$l['advanced_private_message_search'] = 'חיפוש הודעות פרטיות מתקדם';
$l['search_criteria'] = 'קריטריוני חיפוש';
$l['keywords'] = 'מילות מפתח';
$l['search_in_subject'] = 'חפש בכותרת ההודעה';
$l['search_in_message'] = 'חפש בגוף ההודעה';
$l['message_status'] = 'סטטוס הודעה';
$l['message_status_new'] = 'חדשה';
$l['message_status_replied_to'] = 'תגובה';
$l['message_status_forwarded'] = 'מועברת';
$l['message_status_read'] = 'נקראה';
$l['folder'] = 'תיקייה';
$l['search_options'] = 'אפשרויות חיפוש';
$l['sort_by'] = 'מיין לפי';
$l['sort_by_subject'] = 'מיין לפי: כותרת';
$l['sort_by_sender'] = 'מיין לפי: שולח';
$l['sort_by_date'] = 'מיין לפי: תאריך';
$l['ascending_order'] = 'סדר עולה';
$l['descending_order'] = 'סדר יורד';
$l['search_private_messages'] = 'חפש הודעות פרטיות';
$l['check_all'] = 'Check All';
$l['search_user'] = 'חפש משתמש';
$l['error_nopmsarchive'] = 'Sorry, but there are no private messages matching the criteria you specified.';
$l['error_invalidpmfoldername'] = 'Sorry, but a folder name you have entered contains characters which are not allowed.';
$l['error_emptypmfoldername'] = 'Sorry, but a folder name you have entered does not contain any text.  Please enter a name for the folder, or completely blank the name to delete the folder.';
$l['error_invalidpmrecipient'] = 'The recipient you entered is either invalid or doesn\'t exist. Please go back and enter a correct one.';
$l['error_invalidpm'] = 'Invalid PM';
$l['error_pmrecipientreachedquota'] = 'You cannot send a private message to {1} because he/she has reached their private messaging quota. They cannot be sent any message until their messages have been cleared out. An email has been sent to the user about this. Please try sending your message at a later stage.';
$l['error_recipientpmturnedoff'] = '{1} has chosen not to receive private messages or may not be allowed to do so. Therefore you may not send your private message to this user.';
$l['error_pmsturnedoff'] = 'You currently have private messages disabled in your profile.<br />To be able to use the private messaging system this setting must be enabled.';
$l['error_recipientignoring'] = 'We are sorry but we cannot process your private message to {1}. You do not have permission to perform this action.';
$l['error_pm_already_submitted'] = 'You have already submitted the same private message to the same recipient within the last 5 minutes.';
$l['error_nopms'] = 'You must have one or more private messages in order to access this function.';
$l['error_minsearchlength'] = 'One or more of your search terms were shorter than the minimum length. The minimum search term length is {1} characters.<br /><br />If you\'re trying to search for an entire phrase, enclose it within double quotes. For example "The quick brown fox jumps over the lazy dog".';
$l['error_nosearchresults'] = 'Sorry, but no results were returned using the query information you provided. Please redefine your search terms and try again.';
$l['error_no_search_support'] = 'This database engine does not support searching.';
$l['error_nosearchterms'] = 'You did not enter any search terms. At a minimum, you must enter either some search terms or a username to search by.';
$l['error_searchflooding_1'] = 'Sorry, but you can only perform one search every {1} seconds. Please wait another 1 second before attempting to search again.';
$l['error_searchflooding'] = 'Sorry, but you can only perform one search every {1} seconds. Please wait another {2} seconds before attempting to search again.';
$l['error_invalidsearch'] = 'An invalid search was specified.  Please go back and try again.';
$l['redirect_pmsaved'] = 'The private message has been saved in your Drafts folder.';
$l['redirect_pmstrackingstopped'] = 'Tracking of the selected PMs has been stopped.';
$l['redirect_pmstrackingcanceled'] = 'The selected unread PMs have been deleted from the recipient\'s inbox.';
$l['redirect_allpmstrackingstopped'] = 'Tracking of all read PMs has been stopped.';
$l['redirect_pmsmoved'] = 'The selected private messages have been moved.';
$l['redirect_pmsdeleted'] = 'The selected private messages have been deleted.';
$l['redirect_pmsent'] = 'תודה לך, ההודעה הפרטית נשלחה בהצלחה.<br />כעת תועבר לעמוד הדואר הנכנס שלך.';
$l['redirect_pmfoldersupdated'] = 'Thank you, your private messaging folders have successfully been updated.<br />You will now be returned to your private message Inbox.';
$l['redirect_pmfoldersemptied'] = 'The selected private messaging folders have successfully been emptied.<br />You will now be taken back to your Private Messaging Inbox.';
$l['redirect_searchresults'] = 'Thank you, your search has been submitted and you will now be taken to the results list.';
$l['quick_reply'] = 'תגובה מהירה';
$l['message_note'] = 'הזן את התגובה שלך להודעה זו.';
$l['send_reply'] = 'שלח תגובה';
$l['quickreply_signature'] = 'חתימה';
$l['quickreply_disable_smilies'] = 'בטל סמיילים';
$l['quickreply_save_copy'] = 'שמור עותק';
$l['quickreply_read_receipt'] = '<strong>בקש אישור קריאה</strong>';
