<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.2)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1801
// Last edited in MyBB Editor by : Elfassy
// Last edited date : Mon, 17 Nov 2014 18:02:56 +0000
// --------------------------------------------------------------------------------

$l['nav_reputation'] = 'דוח מוניטין';
$l['nav_profile'] = 'הפרופיל של {1}';
$l['reputation_disabled'] = 'מערכת המוניטין הושבתה על ידי מנהל האתר.';
$l['reputation'] = 'מוניטין';
$l['error'] = 'שגיאה';
$l['add_no_uid'] = 'לא צוין משתמש אשר לו מיועד המוניטין.';
$l['add_no_permission'] = 'אינך רשאי להעניק דירוגי מוניטין למשתמשים.';
$l['add_disabled'] = 'אינך רשאי להעניק דירוגי מוניטין למשתמשים בקבוצת המשתמשים הזו.';
$l['add_yours'] = 'אינך יכול להוסיף לעצמך מוניטין, תחשוב כמה מביך זה יראה מהצד.';
$l['add_invalidpower'] = 'דירוג לא תקין נבחר מהרשימה.';
$l['add_maxperday'] = 'הגעת למכסת המוניטין שברשותך להעניק למשתמשים בקהילה מדי יום.';
$l['add_maxperuser'] = 'הגעת למכסת המוניטין שברשותך להעניק למשתמש זה מדי יום.';
$l['add_maxperthread'] = 'הגעת למכסת המוניטין שברשותך להעניק למשתמש זה (מאותו האשכול) באותו יום.';
$l['add_no_comment'] = 'על סיבת הענקת המוניטין להכיל לפחות 10 תווים.';
$l['add_toolong'] = 'על סיבת הענקת המוניטין להכיל עד {1} תווים.';
$l['add_negative_disabled'] = 'מנהל האתר ביטל את אפשרות המוניטין השלילי.';
$l['add_neutral_disabled'] = 'מנהל האתר ביטל את אפשרות המוניטין הניטרלי.';
$l['add_positive_disabled'] = 'מנהל האתר ביטל את אפשרות המוניטין החיובי.';
$l['add_all_rep_disabled'] = 'מנהל האתר ביטל את מערכת המוניטין, אינך רשאי לדרג את המשתמש.';
$l['reputation_report'] = 'דוח מוניטין עבור {1}';
$l['reputation_members'] = 'מוניטין ממשתמשים:';
$l['reputation_posts'] = 'מוניטין מתגובות:';
$l['summary'] = 'סיכום<!-- http://myhebb.org/ -->';
$l['total_reputation'] = 'סה"כ מוניטין';
$l['post_reputation'] = 'הענק מוניטין';
$l['positive_count'] = 'חיוביים';
$l['neutral_count'] = 'ניטרליים';
$l['negative_count'] = 'שליליים';
$l['last_week'] = 'שבוע אחרון';
$l['last_month'] = 'חודש אחרון';
$l['last_6months'] = 'מחצית השנה האחרונה';
$l['all_time'] = 'בכל הזמנים';
$l['comments'] = 'פירוט<!-- http://myhebb.org/ -->';
$l['close_window'] = 'סגור חלון';
$l['add_reputation_vote'] = 'הענק דירוג מוניטין עבור {1}';
$l['add_reputation_to_post'] = 'דירוג מוניטין זה הוא עבור {1}.<br />';
$l['neg_rep_disabled'] = '<span class="smalltext">* - <em>לא ניתן לדרג במוניטין שלילי נכון לעכשיו</em></span>';
$l['pos_rep_disabled'] = '<span class="smalltext">* - <em>לא ניתן לדרג במוניטין חיובי נכון לעכשיו</em></span>';
$l['neu_rep_disabled'] = '<span class="smalltext">* - <em>לא ניתן לדרג במוניטין ניטרלי נכון לעכשיו</em></span>';
$l['no_comment_needed'] = 'הענקת המוניטין לתגובה זו תוצג בפרופיל האישי של מחבר ההודעה. במידה ותבחר לפרט את הסיבה להענקת המוניטין, תוכל לכתוב זאת בשדה הפירוט.<br />';
$l['no_comment'] = '[ללא פירוט]';
$l['vote_added'] = 'הדירוג הוענק';
$l['vote_updated'] = 'הדירוג עודכן';
$l['vote_deleted'] = 'הדירוג הוסר';
$l['vote_added_message'] = 'דירוג מוניטין זה התווסף בהצלחה.';
$l['vote_updated_message'] = 'דירוג מוניטין זה עודכן בהצלחה.';
$l['vote_deleted_message'] = 'דירוג מוניטין זה נמחק מהמשתמש בהצלחה.';
$l['update_reputation_vote'] = 'מעדכן את דירוג המוניטין שלך עבור {1}';
$l['positive'] = 'חיובי';
$l['negative'] = 'שלילי';
$l['neutral'] = 'נייטרלי';
$l['user_comments'] = 'סיבת הענקת המוניטין ל-{1}:';
$l['add_vote'] = 'הענק מוניטין';
$l['update_vote'] = 'עדכן מוניטין';
$l['delete_vote'] = 'הסר';
$l['report_vote'] = 'דווח';
$l['power_positive'] = 'חיובי ({1})';
$l['power_neutral'] = 'נייטרלי';
$l['power_negative'] = 'שלילי ({1})';
$l['show_all'] = 'הצג: כל הדירוגים';
$l['show_positive'] = 'הצג: דירוגים חיוביים';
$l['show_neutral'] = 'הצג: דירוגים נייטרלים';
$l['show_negative'] = 'הצג: דירוגים שליליים';
$l['sort_updated'] = 'מיין לפי: מועד העדכון האחרון';
$l['sort_username'] = 'מיין לפי: שם משתמש';
$l['last_updated'] = 'עודכן לאחרונה ב-{1}';
$l['postrep_given'] = 'דירוג הניתן עבור התגובה של <a href="{1}">{2}</a> {3}<br />';
$l['postrep_given_thread'] = 'ב-<a href="{1}">{2}</a>';
$l['no_reputation_votes'] = 'לא נמצאו כל דירוגי מוניטין אשר עונים על תנאי החיפוש שצוינו.';
$l['delete_reputation_confirm'] = 'האם אתה בטוח שברצונך להסיר דירוג מוניטין זה?';
$l['delete_reputation_log'] = 'דירוג מוניטין שהוסר על ידי: {1} (מזהה המשתמש: {2})';
$l['reputations_disabled_group'] = 'מערכת המוניטין סגורה לשימוש עבור משתמשים בקבוצת המשתמש שלך.';
$l['rate_user'] = 'דרג משתמש';
