<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Sun, 26 Apr 2015 12:04:34 +0000
// --------------------------------------------------------------------------------

$l['all_forums'] = 'כל הפורומים';
$l['forum'] = 'פורום:';
$l['posted_by'] = 'נכתב על ידי:';
$l['on'] = 'ב-';
$l['portal'] = 'פורטל';
