<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : עברית (ישראל) (1.3)
// Author of the language pack : MyHeBB
// Language pack translators website : http://www.myhebb.org/
// Compatible version of MyBB : 1803
// Last edited in MyBB Editor by : nir
// Last edited date : Sat, 25 Apr 2015 14:18:04 +0000
// --------------------------------------------------------------------------------

$l['ucp_nav_width'] = '180';
$l['ucp_nav_menu'] = 'תפריט';
$l['ucp_nav_messenger'] = 'דואר אישי';
$l['ucp_nav_compose'] = 'צור הודעה חדשה';
$l['ucp_nav_tracking'] = 'מעקב';
$l['ucp_nav_edit_folders'] = 'ערוך תקיות';
$l['ucp_nav_profile'] = 'פרופיל אישי';
$l['ucp_nav_edit_profile'] = 'ערוך פרופיל';
$l['ucp_nav_edit_options'] = 'ערוך אפשרויות';
$l['ucp_nav_change_email'] = 'שנה כתובת דוא"ל';
$l['ucp_nav_change_pass'] = 'שנה סיסמה';
$l['ucp_nav_change_username'] = 'שנה שם משתמש';
$l['ucp_nav_edit_sig'] = 'ערוך חתימה';
$l['ucp_nav_change_avatar'] = 'שנה סמלון אישי';
$l['ucp_nav_misc'] = 'שונות';
$l['ucp_nav_editlists'] = 'רשימת חברים\\התעלמויות';
$l['ucp_nav_favorite_threads'] = 'אשכולות מועדפים';
$l['ucp_nav_subscribed_threads'] = 'אשכולות רשומים';
$l['ucp_nav_forum_subscriptions'] = 'פורומים רשומים';
$l['ucp_nav_drafts'] = 'טיוטות שמורות';
$l['ucp_nav_drafts_active'] = '<strong>טיוטות שמורות ({1})</strong>';
$l['ucp_nav_notepad'] = 'פנקס רשימות אישי';
$l['ucp_nav_view_profile'] = 'צפה בפרופיל';
$l['ucp_nav_home'] = 'לוח בקרת משתמש';
$l['ucp_nav_usergroups'] = 'חברות בקבוצות';
$l['ucp_nav_attachments'] = 'נהל קבצים מצורפים';
